### ISSUE TITLE
DropdownMenu remounts menu items when toggling open state

### ISSUE THREAD

**Issue by SachaG** [react-bootstrap/react-bootstrap#1808] opened 2016-04-14 06:55 UTC
I have a button inside a dropdown that opens a modal. So far so good, except clicking inside the modal not only closes the dropdown, but also closes the modal itself:

![http://g.recordit.co/NV2JPU1i8G.gif](http://g.recordit.co/NV2JPU1i8G.gif)

What can I do to prevent this?

**Comment by taion** [comment] 2016-04-14 06:59
Don't set the container of the modal to the dropdown.

**Comment by SachaG** [comment] 2016-04-14 07:07
Wait what do you mean? Can you give me a little more details?

**Comment by taion** [comment] 2016-04-14 07:09
Don't set `container` on the `<Modal>`.

**Comment by SachaG** [comment] 2016-04-14 07:12
I'm not setting `container`. Here's the relevant Modal code: 

https://github.com/TelescopeJS/Telescope/blob/nova/packages/nova-core/lib/components/ModalTrigger.jsx#L66-L73

And here's where I call the modal:

https://github.com/TelescopeJS/Telescope/blob/nova/packages/nova-base-components/lib/categories/CategoriesList.jsx#L12-L14

**Comment by taion** [comment] 2016-04-14 07:32
I see – this is because we lazily wrap the list in a `<RootCloseWrapper>` only when open: https://github.com/react-bootstrap/react-bootstrap/blob/v0.28.5/src/DropdownMenu.js#L113-L119. We should probably just always keep that `RootCloseWrapper` around. @jquense thoughts?

**Comment by jquense** [comment] 2016-04-14 11:24
I am fairly certain root close wrapper is like that because otherwise it intercepts clicks when the dropdown is closed, leading to certain cases where it opens and immediately closes again... but that may also just be Overlay I'm thinking of.

to me this is a perfect example of why a modal trigger component is flawed, the Modal should live outside the dropdown entirely so that it's mount state is independent of the dropdowns open state. that being said think it's a bit weird that we unmount Dropdown Menus when closed its a source of easy gotchas

**Comment by jquense** [comment] 2016-04-14 11:32
I would add that the alernatives also have some sot of trade off in terms of extra DOM nodes, or suboptimal encapsulation, Perhaps this is good case for needing some imperative version of modal?

Sort of but not exactly like: https://github.com/jquense/react-dialog/blob/master/src/dialogs/dialog.js for situations where the extra wrapping DOM node makes no sense or isn't feasible.

**Comment by SachaG** [comment] 2016-04-14 14:16
I can see why a modal trigger component would create some complications, but on the other hand it's worked pretty well up to now. 

I guess I could try taking the modals out of the menu, but I'm not quite sure how to do it since the loop over the list of categories happens inside the dropdown. 

Do you think this issue is likely to be fixed soon? Otherwise maybe I just shouldn't use modals here for now?

**Comment by jquense** [comment] 2016-04-14 14:22
I am not sure there is an issue to fix here until we decide if Dropdown menu's should stay mounted when closed.

For this use I would just use Modal directly and onSelect pass the modal content up, so a parent can then pass it to a Modal.

**Comment by SachaG** [comment] 2016-04-14 14:30
> For this use I would just use Modal directly and onSelect pass the modal content up, so a parent can then pass it to a Modal.

Thanks for the advice! By any chance, is there any code example of this somewhere?

**Comment by taion** [comment] 2016-04-14 14:58
@jquense The dropdown menu remains mounted regardless. The problem is that all the components re-mount, because we add the `<RootCloseWrapper>` only when the menu opens. This is sufficient to nuke all the component state, including the "shown" bit for the modal in this case.

**Comment by jquense** [comment] 2016-04-14 15:07
> because we add the <RootCloseWrapper> only when the menu opens

O duh, I do think that is there for a specific reason, but it does sound like something that may be worth fixing. perhap we just noop on `onRootClose` while the dropdown is closed

**Comment by taion** [comment] 2016-04-14 15:10
Yeah – it's going to require rewriting RCW to not attach the document click listener in appropriate cases though.

On that topic, WDYT of changing `noWrap` to `componentClass` on there?

**Comment by jquense** [comment] 2016-04-14 15:16
> On that topic, WDYT of changing noWrap to componentClass on there?

sounds good to me, makes more sense anyway

**Comment by SachaG** [comment] 2016-04-14 22:33
Well it sounds like you guys got this covered, but let me know if I can do anything to help out :)

**Comment by taion** [comment] 2016-04-14 22:42
This is not a priority for me to fix. As noted by the labels, this issue will probably stay open for a while, unless you care to contribute the relevant PRs.

**Comment by SachaG** [comment] 2016-04-15 00:21
Well, I ended up removing the modals from the dropdown and now it works. I have to pass an `openModal` handler to each child component but overall it's not that bad :)

![http://g.recordit.co/WW46BhvSX2.gif](http://g.recordit.co/WW46BhvSX2.gif)

Here's the code just in case anybody's curious: 

https://github.com/TelescopeJS/Telescope/blob/nova/packages/nova-base-components/lib/categories/CategoriesList.jsx

**Comment by larrydahooster** [comment] 2016-08-26 16:15
I also encountered a problem with the lazily added RootCloseWrapper in the Overlay Component https://github.com/react-bootstrap/react-overlays/blob/master/src/Overlay.js#L79

I have a scenario where I want to control the rootClose prop of an overlay while it is open. Changing the prop causes the concrete overlay component to remount.

I think it would be better too always keep that RootCloseWrapper around as @taion already suggested. So a Component that supports RootCloseWrapper should not Mount the wrapper in case it needs it, But the wrapper should decide if the eventhandlers should be activated, in case rootClose is activated.

**Comment by taion** [comment] 2016-10-01 21:12
This was fixed in https://github.com/react-bootstrap/react-bootstrap/pull/2241.

**Closed by taion** 2016-10-01 21:12 UTC
Labels: bug, help wanted

**Comment by SachaG** [comment] 2016-10-02 00:45
Great work, thanks for fixing this :)

**Comment by victsant** [comment] 2017-07-24 23:00
I am having a similar issue using a popover and then triggering a modal from the popover, where clicking inside the modal closes everything. Is there a fix or workaround for this?
