### ISSUE TITLE
Nav/Navbar/Carousel error on IE10 

### ISSUE THREAD

**Issue by valissalim** [react-bootstrap/react-bootstrap#3330] opened 2018-10-15 04:10 UTC
Anyone have any idea what I'm doing wrong or why I'm getting this error?

![screen shot 2018-10-10 at 3 55 48 pm](https://user-images.githubusercontent.com/6657691/46929402-101d3980-d072-11e8-9340-4d8d8f49b8bf.jpg)

`import React from 'react';`
`import Container from 'react-bootstrap/lib/Container';`
`import Navbar from 'react-bootstrap/lib/Navbar';`
`import Nav from 'react-bootstrap/lib/Nav';`

`export default class Header extends React.Component {`
`  render() {`
`    return (`
`      <Container>`
`        <h1>Navbar</h1>`
`        <Button>Button</Button>`

`        <Navbar bg="light" expand="lg">`
`          <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>`
`          <Navbar.Toggle aria-controls="basic-navbar-nav" />`
`          <Navbar.Collapse id="basic-navbar-nav">`
`            <Nav className="mr-auto">`
`              <Nav.Link href="#home">Home</Nav.Link>`
`              <Nav.Link href="#link">Link</Nav.Link>`
`            </Nav>`
`          </Navbar.Collapse>`
`        </Navbar>`
`      </Container>`
`    );`
`  }`
`}`

**Comment by taion** [comment] 2018-10-15 22:11
Do you have a repro here?

**Comment by mirzalikic** [comment] 2018-10-22 22:21
same here, navbar throws error in ie10 @ "react-bootstrap": "^1.0.0-beta.1"

**Comment by mxschmitt** [comment] 2019-08-03 22:31
Please provide us a working minimal reproducible example on e.g. Codesandbox. Otherwise we can't reproduce it. I will close this here for now. Just ping me, once you have a minimal example. Thanks!

**Closed by mxschmitt** 2019-08-03 22:31 UTC
