### ISSUE TITLE
NavDropdown does not pass `id` or other props to DropdownToggle

### ISSUE THREAD

**Issue by atsolberg** [react-bootstrap/react-bootstrap#4828] opened 2019-11-15 17:31 UTC
## Describe the bug

Trying to add an id prop to top level navs items.  The 'id' prop and other data attributes are ignored.

## To Reproduce

You can see this on the documentation examples for the Navbar component. 
1. Go to https://react-bootstrap.github.io/components/navbar/#navbars-mobile-friendly
2. Notice the `<NavDropdown>` in the example code has an 'id' attribute.
3. Inspect the example ui and notice the `<a>` element has no id.

## Reproducible Example

Example [CodeSandbox](https://codesandbox.io/s/code-sandbox-examples-r78qd?fontsize=14&hidenavigation=1&theme=dark).

## Expected behavior

The id prop and any other un-used prop should pass through to the anchor element.

## Screenshots

![image](https://user-images.githubusercontent.com/2157412/68962958-73a8f780-079b-11ea-9bfd-69cb237c1084.png)

## Environment (please complete the following information)

- macOS
- Chrome 78.0.3904.97 (Official Build) (64-bit)
- React-Bootstrap Version 1.0.0-beta.14

**Comment by taion** [comment] 2019-11-15 19:27
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/3940

**Closed by taion** 2019-11-15 19:27 UTC
