### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by ranneyd** [react-bootstrap/react-bootstrap#4534] opened 2019-09-27 01:26 UTC
## Describe the bug

I've been running into this in a bunch of React libraries recently. They've deprecated this function and renamed it to `UNSAFE_componentWillReceiveProps`. This library doesn't use the old version, but still gets the console warnings when using certain components.

Through a lot of digging and grep-ing I've found that these warnings are coming from two dependencies:

1. https://github.com/react-bootstrap/react-overlays (clearly related to this lib)
2. https://github.com/FezVrasta/react-popper

The problems are actually with the dependencies of _these_ libraries

1. `react-overlays` uses https://github.com/jquense/uncontrollable. This library needs to be updated
2. `react-popper` uses https://github.com/jamiebuilds/create-react-context, which needs to be updated

The `react-popper` issue seems easily fixable since this is a polyfill for a feature that's since been officially added to React. I didn't dig into the `react-overlays` problem, but getting a PR into `uncontrollable` adding the `UNSAFE_` prefix and updating a ton of version numbers should fix it.

**Comment by taion** [comment] 2019-09-27 02:24
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/4368, https://github.com/react-bootstrap/react-bootstrap/issues/4306, &c.

**Closed by taion** 2019-09-27 02:24 UTC
