### ISSUE TITLE
Standalone Dropdown Menu is never visible

### ISSUE THREAD

**Issue by p0wl** [react-bootstrap/react-bootstrap#5065] opened 2020-03-25 11:39 UTC
## Describe the bug

Rendering only a Dropdown Menu is not possible, because it always gets 'opacity: 0'

## To Reproduce

1. Go to https://react-bootstrap.netlify.com/components/dropdowns/#menu-headers
2. See error

## Screenshots

![Bildschirmfoto 2020-03-25 um 12 36 58](https://user-images.githubusercontent.com/596578/77532574-6d3b3280-6e95-11ea-8fc1-07e83e793ab0.png)

## Environment (please complete the following information)

- Operating System: mac OS
- Browser, Version Firefox 74, Chrome 80.0.3987.149
- React-Bootstrap Version 1.0.0

**Comment by 0x29a** [comment] 2020-04-03 13:14
I've encountered the same issue.
@p0wl do you have any workaround?

**Comment by taion** [comment] 2020-04-03 19:47
cc @jquense – i think this is from the changes w/popper?

we should probably merge in `props.style` here. but we should fix the examples, at least

**Comment by LennyLip** [comment] 2020-04-16 08:47
Same here!
```
  <Dropdown
        id={`dropdown-menu-` + this.props.uuid}
        onToggle={this.onToggle}
        show={this.state.menuOpen}
      >
        <Dropdown.Toggle as={this.MenuToggle} />
        <Dropdown.Menu>
          {menus}
        </Dropdown.Menu>
      </Dropdown>
```
Dropdown.Menu add and remove 'show' css class, but opacity: 0; for both cases
![image](https://user-images.githubusercontent.com/955994/79435165-fe568280-7fd7-11ea-8580-a1fffc32b844.png)

**Comment by bluematter** [comment] 2020-04-22 20:26
Having this same issue in v1.0.0. Going to downgrade a few versions. The issue I am facing is that .show is never added and opacity stays at 0.

```
<Nav.Item>
        <Dropdown alignRight show={show}>
          <Dropdown.Toggle
            image={user.picture}
            name={user.name}
            email={user.email}
            onClick={handleClick}
            onClose={handleClose}
            isOpened={show}
            as={AvatarButton}
            id="profile-dropdown"
          />

          <Dropdown.Menu className="shadow border-0">
            <Link href="/dashboard" as="dashboard">
              <a className="dropdown-item">Dashboard</a>
            </Link>
            {/* <Link href="/profile" as="profile">
              <a className="dropdown-item">Profile</a>
            </Link> */}
            <Dropdown.Item onClick={onLogout}>Sign Out</Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
      </Nav.Item>
```

**Comment by jquense** [comment] 2020-04-22 21:02
@bluematter are you running into this somewhere in an app? This Issue is really just about a bug in  our Docs, not a bug in the library.

(one i've fixed in #5132 btw)

**Comment by kosmiq** [comment] 2020-04-27 08:03
@jquense @bluematter can we close this? It's fixed in docs and it shouldn't be used in a live app anyway I guess?

**Closed** 2020-04-27 11:51 UTC
Labels: bug

**Comment by 0x29a** [comment] 2020-04-29 10:32
@jquense @kosmiq  
Hello. Please consider this code example: https://codesandbox.io/s/react-bootstrap-playground-tyvzo?fontsize=14&hidenavigation=1&theme=dark

**Comment by jquense** [comment] 2020-04-29 12:26
@0x29a you need to override the default styles on DropdownMenu like we did in the docs. using it like this isn't really a supported use case

**Comment by jmaheshkumar** [comment] 2020-10-12 07:26
Having the same issue in v1.3.0 too...... Can anyone help me to fix this soon?

**Comment by pavel-martynov** [comment] 2021-02-16 10:38
And it's still not working

**Comment by hyper1** [comment] 2021-03-16 11:36
+1

**Comment by carautenbach** [comment] 2021-06-23 07:12
This worked for me:
```
.dropdown-menu.show {
  opacity: 1 !important;
  pointer-events: auto !important;
}
```
