### ISSUE TITLE
bsPrefix has side effects for the Popover styling 

### ISSUE THREAD

**Issue by SailingSteve** [react-bootstrap/react-bootstrap#3335] opened 2018-10-18 02:36 UTC
Take any example code from the 1.00 branch (I took the overlay [trigger)](url) and then pass in any completely harmless style like
`.card-test {
  color: white;
}`

and what happens is popper.js adds an unwanted translate3d(), that looks to the html dom element's scrollWidth, and if you have any hidden overflow, it treats the device size as being wider than it is and renders the popover with part of the box off of the screen.  You can see the popup with the Listening button in the dialog.  Without bsPrefix, it looks decent and is centered on the screen with the default styling.

<img width="426" alt="screen shot 2018-10-17 at 7 34 15 pm" src="https://user-images.githubusercontent.com/6923653/47127871-c4ba8500-d243-11e8-872d-b41b5a689d1f.png">

**Comment by jquense** [comment] 2018-10-19 13:08
> and what happens is popper.js adds an unwanted translate3d()

Why do you say unwanted? The translate is what is positioning the poppover (via Popper) without it, it wouldn't be in the right position overall. I'm not quite sure what the issue is here, please provide a runnable repro thanks!

**Comment by SailingSteve** [comment] 2018-10-19 17:29
My app, (at the url http://wevote.us shows the way it was before converting to 1.00), looks like it is fully contained within the screen of a phone (using chrome dev tools), and when I use the default Popover styling (no bsPrefix), the pane appears in the middle of the screen and the styling that shows up for the popper does not have the translate3d, so all is well.  Stepping through all the elements in the debugger shows everything is contained within the screen size, but I suspect something like a slider is putting some hidden elements out to the right beyond the screen.

When I do use bsStyle, I can see deep in Popper.js, that it is looking at the size of the screen, and also the scrollableWidth, that is about 150px wider than the 375px wide screen.  You can't actually scroll out there, since there is nothing visible, but only when I add the bsStyle, popper within react-bootstrap, does the location math including that scrollable width, and draws the pop-up partially off the screen.

This did not happen on the 0.3x branch.

I'll make a repo on Monday.

**Comment by kosmiq** [comment] 2020-03-11 10:17
Closing since no feedback has been given for a long time.

**Closed by kosmiq** 2020-03-11 10:17 UTC
