### ISSUE TITLE
Browser Support: Modal and Alert does not work in IE11

### ISSUE THREAD

**Issue by pcast01** [react-bootstrap/react-bootstrap#3637] opened 2019-04-11 19:57 UTC
# Browser Support: Modal and Alert does not work in IE11

Both of these components do not render in IE11.

Here are my dependencies:
```javascript
"dependencies": {
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "react": "^16.8.6",
    "react-bootstrap": "^1.0.0-beta.6",
    "react-dom": "^16.8.3",
    "react-dropzone": "^10.0.6",
    "react-flip-move": "^3.0.3",
    "react-icons": "^3.5.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-dev-server": "^3.2.1",
    "whatwg-fetch": "^3.0.0"
  },
  "devDependencies": {
    "webpack-cli": "^3.2.3"
  }
````

Modal and Alert basic Code in my component

```javascript
import Modal from "react-bootstrap/Modal";
import Alert from "react-bootstrap/Alert";

...
<Alert show={this.state.showMessage} variant="success">
	Superhero added
</Alert>
<Modal show={this.state.show} onHide={this.handleClose} keyboard>
	<Modal.Header closeButton>
		<Modal.Title>Upload a Superhero form</Modal.Title>
	</Modal.Header>
	<Modal.Body>Looks like your forgot to add an Image!</Modal.Body>
		<Modal.Footer>
		<Button variant="secondary" onClick={this.handleClose}>
			Close
		</Button>
	</Modal.Footer>
</Modal>
...
```

Error in Console:

*SCRIPT1002: Syntax error*

clicking on the line of code the error occurs is on `(0, _react.useLayoutEffect)(() => {`
```javascript
function useCommittedRef(value) {
  const ref = (0, _react.useRef)(value);
  (0, _react.useLayoutEffect)(() => { 
    ref.current = value;
  }, [value]);
  return ref;
}
```

I have tried to fix this using the polyfill react-app-polyfill(https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill)

I have since removed these two components but wanted to post the issue to let you know and also to see if anyone else gets this same error.

**Comment by mxschmitt** [comment] 2019-04-11 20:02
Duplicate of #3620 and should be fixed in the next release. You can use the polyfill as a workaround.

**Closed by mxschmitt** 2019-04-11 20:02 UTC

**Comment by pcast01** [comment] 2019-04-11 22:04
@mxschmitt, 

I am unable to use the react-app-polyfill  `import 'react-app-polyfill/ie11';` in my app to use the Modal and Alert components. I am also not using CRA. 

I have put this in my index.js file at the top as suggested but it still errors out.

Any suggestions to get this working?

**Comment by taion** [comment] 2019-04-11 22:15
Shoot, I think we need to cut a new release. The semver range on `@restart/hooks` doesn't include the versions with fixed ES5 builds.

**Comment by kinguzzo** [comment] 2019-04-29 15:06
Same problem here. After a day of attempts I came across this post and spot the problem. Waiting for a release. Thank you.
