### ISSUE TITLE
@babel/runtime has moved their folder structure and is breaking react-bootstrap library

### ISSUE THREAD

**Issue by mikewarrior** [react-bootstrap/react-bootstrap#3235] opened 2018-08-20 01:18 UTC
Today I reinstalled my machine, and when it was time to start my react app I find out that I had errors like:
Module not found: can't resolve '@babel/runtime/core-js/map' 

After, almost giving up I found the issue in the imports of react-bootstrap as @babel/runtime library had move their files all over the place. We need react-bootstrap correct the imports in the different components like Dropdown, Panel,etc that has @babel/runtime imports

I'm using the latest stable version 0.32.2.

**Comment by BastianVoigt** [comment] 2018-08-20 06:13
I got:

    ERROR in ./node_modules/react-bootstrap/es/DropdownMenu.js
    Module not found: Error: Can't resolve '@babel/runtime/core-js/array/from' in '/usr/src/app/node_modules/react-bootstrap/es'

Maybe it's the same problem?

**Comment by BastianVoigt** [comment] 2018-08-20 06:27
Quickfix: I was able to build my project by downgrading to 0.32.1:

    "dependencies": {
        "react-bootstrap": "0.32.1"
    }

**Comment by krayush** [comment] 2018-08-20 07:57
Need a permanent solution to this.
Seems like a lot of dependencies were moved and no one did a thorough testing before releasing a newer version
@taion: Can someone from your team check this?

**Comment by mikewarrior** [comment] 2018-08-20 13:35
@BastianVoigt Yes that's the exact error

**Comment by jaapspiering** [comment] 2018-08-20 15:17
Isn't this a duplicate of #3231 ?

**Closed as completed** 2018-08-20 15:19 UTC
Labels: duplicate

**Comment by Frozzy6** [comment] 2018-08-20 15:51
@jaapspiering, I've got the same error with babel-runtime@6.26.0
