### ISSUE TITLE
Nav Tag inside Navbar cause the browser to stop??

### ISSUE THREAD

**Issue by saher-elgendy** [react-bootstrap/react-bootstrap#4171] opened 2019-08-03 19:34 UTC
Simply, using react-bootstrap navbar cause a problem in my project, it cause the browser to stop and crash finally:

This code cause the problem:

```
   <Navbar >
            <Navbar.Brand href="/">
                <img src={images.logo} alt="microsoft_logo" />
            </Navbar.Brand>

            <Navbar.Toggle aria-controls="main-navbar-nav" />
            <Navbar.Collapse >
                <Nav className="mr-auto">
                    <Nav.Link href="#home">Home</Nav.Link>
                    <Nav.Link href="#link">Link</Nav.Link>
                </Nav>
            </Navbar.Collapse>
   </Navbar>
```
While this does not:

```
   <Navbar >
            <Navbar.Brand href="/">
                <img src={images.logo} alt="microsoft_logo" />
            </Navbar.Brand>

            <Navbar.Toggle aria-controls="main-navbar-nav" />
            <Navbar.Collapse >
       
            </Navbar.Collapse>
   </Navbar>

```

So why i guessed that the problem comes from React-bootstrap **Nav** component??

is it a bug , i  am using 4.3.1 version of bootstrap??

**Comment by mxschmitt** [comment] 2019-08-03 20:55
Hi @saher-elgendy can you try to make a minimal reproducible example on Codesandbox?

You can use this template: https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic

**Comment by saher-elgendy** [comment] 2019-08-12 21:19
@mxschmitt ok this is the codesandbox example and it produce the same problem

https://codesandbox.io/s/charming-architecture-pr0ky

**Comment by nortonwong** [comment] 2019-08-13 18:18
Your component `<Nav />` is rendering itself. React is recursively constructing a larger and larger tree and consuming a lot of memory.

You should rename your component and `import { Nav } from 'react-bootstrap'`.

**Comment by mxschmitt** [comment] 2019-08-13 20:28
@nortonwong thanks for digging into this issue and explaining the root cause.

I will close this one here.

**Closed by mxschmitt** 2019-08-13 20:28 UTC
Labels: needs more info
