### ISSUE TITLE
OverlayTrigger - findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by brvaland** [react-bootstrap/react-bootstrap#5519] opened 2020-11-13 18:36 UTC
Hi

I am using Tooltip overlay from react-bootstrap but getting error `findDOMNode is deprecated in StrictMode`. As per [documentation](https://react-bootstrap.github.io/components/overlays/) using the function form of overlaytrigger avoids a React.findDOMNode call, for those trying to be strict mode compliant but I am still getting the error as below.

```
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Tooltip)
    in Tooltip (at NavMenu.tsx:31)
    in Transition (created by Fade)
    in Fade (created by Overlay)
    in Overlay (created by Overlay)
    in Overlay (created by OverlayTrigger)
    in OverlayTrigger (at NavMenu.tsx:28)
    in div (created by ForwardRef)
    in ForwardRef (created by Nav)
    in Nav (at NavMenu.tsx:27)
    in div (created by Context.Consumer)
    in Transition (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in NavbarCollapse (at NavMenu.tsx:23)
    in nav (created by Navbar)
    in Navbar (at NavMenu.tsx:18)
    in StrictMode (at src/index.tsx:13)
```

**Code for OverLayTrigger**
```
<OverLayTrigger 
     key="left" 
     placement="left" 
     overlay={<Tooltip id="tooltip-initials">{`Logged in as ${this.context.user?.name}`}</Tooltip>}>

{
    ({ref, ...triggerHandler}) => (
        <div className="avatar-circle" {...triggerHandler} >
            <span className="initials" id="initials" ref={ref}>
                {`${this.context.user?.given_name.substring(0,1)}${this.context.user?.family_name.substring(0,1)}`}
            </span>
        </div>
    )
}
</OverLayTrigger>
```

Can you please advise what I am missing above ?

**Comment by douglasduartetb** [comment] 2020-11-14 14:27
When you start a new react project, by default now came with strict mode. Im still waiting a solution for that to, is ugly the errors on console 

`
<React.StrictMode>
        <App />
</React.StrictMode>
`

**Comment by kyletsang** [comment] 2020-11-16 17:45
Your callstack also includes `NavbarCollapse` which will emit this warning.  We do have another issue that currently tracks this: #5075

**Comment by brvaland** [comment] 2020-11-16 19:01
@kyletsang i did try to add it to new CRA project without `NavbarCollapse` but still getting the error - [Gist](https://gist.github.com/brvaland/51e7ec0767fb52e7dc2c6b20916dbcf2).

**Comment by kyletsang** [comment] 2020-11-16 19:13
Just checked the code and the `Overlay` component includes the `Fade` animation by default and this would also emit the warning unfortunately. Setting `animation={null}` in the `OverlayTrigger` should hide the warning, but you'll lose the fade animation.

You're not missing anything in your code - RTG exposed a new nodeRef API that would need to be consumed by react-bootstrap in order to truly fix this.

**Comment by brvaland** [comment] 2020-11-16 19:24
@kyletsang - I did try but getting an error `Property 'animation' does not exist on type 'IntrinsicAttributes & Pick<Pick<OverlayTriggerProps`

**Comment by kyletsang** [comment] 2020-11-16 19:34
Oh sorry, the actual line should be `transition={false}`.  And on that note, I just tried it on my side briefly and the overlay isn't showing.  I'll look into this when I get a moment and update you later.

**Comment by brvaland** [comment] 2020-11-16 19:44
@kyletsang Thanks for quick reply.

**Comment by kyletsang** [comment] 2020-11-16 20:36
@jquense, just wanted to confirm something with you since you are more familiar with the Overlays.  When setting `transition={false}` for cases where `children` is a function, I noticed that we aren't setting the `.show` class - is this because it's up to the user to set this according to the `show` bool prop we pass them?  Also noticed that we don't do any style merging when `children` is a function. 

https://github.com/react-bootstrap/react-bootstrap/blob/072e7c5fb01b492735a9db2409909058a9976190/src/Overlay.tsx#L202-L226

**Comment by thom-ek** [comment] 2020-11-21 23:59
Duplicate of #5075

**Comment by mmomtchev** [comment] 2021-01-09 17:19
@kyletsang I added `transition={false}` which solved the `findDOMNode` error from `react-transition-group` each time the popover is displayed, but I still get an error when the popup is initially created and that one is coming from `react-overlays@4.1.1` - is `react-overlays` supposed to be free of `findDOMNode` now?
This issue is almost an year old, is there something blocking it? I can try to look into it.

**Comment by kyletsang** [comment] 2021-01-10 19:27
Don't think there's any more references to `findDOMNode` in react-overlays.  For the initial `findDOMNode` warning you're seeing, you can avoid that by passing a function child to the `OverlayTrigger`.  See https://react-bootstrap.github.io/components/overlays/#customizing-trigger-behavior

PRs are welcome!  We need to migrate to using the `nodeRef` API in react-transition-group to get rid of the remaining `findDOMNode` warnings.

**Comment by mmomtchev** [comment] 2021-01-11 08:35
@kyletsang Ok, I will try to come up with something

I tried passing a child function, but I still get the warning

**Comment by mmomtchev** [comment] 2021-01-11 09:15
My other warning besides the one from `react-transition-group` that can be avoided with `transition={false}` comes from here:
<https://github.com/react-bootstrap/react-overlays/blob/f03763d16566448e16ade41d6e5d515166c38189/src/safeFindDOMNode.ts#L7>
And I am using a function chiild for `OverlayTrigger` that goes as 

```js
{({ ref, ...triggerHandler }) => (
    <span {...triggerHandler} ref={ref} className='popover-link'><em>{this.state.title}</em></span>
)}
```

As this piece of code dates from about the same time as the original issue and it is authored by the person who closed that discussion - @jquense , I guess that I might be missing something, thus my question?

**Comment by mmomtchev** [comment] 2021-01-11 12:16
Ok, I was able to fix cleanly the first occurrence, I will look into `react-transition-group` but that one seems a little bit deeper

**Comment by mmomtchev** [comment] 2021-01-11 16:29
@jquense @kyletsang Looking at `Fade.tsx`, there is one problematic case - when `children` already contains a reference
In this case the only solution I see is to replace that reference with a function that combines the new references, the one that will be passed to `nodeRef` with the existing one in `children`
Unless you see a better solution?

**Comment by kyletsang** [comment] 2021-05-28 04:45
Fixed in v2 alpha

**Closed by kyletsang** 2021-05-28 04:45 UTC
