### ISSUE TITLE
Modal has issues when invoked in a class: Cannot read property 'getDialogElement' of null

### ISSUE THREAD

**Issue by turboki** [react-bootstrap/react-bootstrap#2600] opened 2017-04-27 21:11 UTC
Hey all,

Im trying to use the modal in a react class and I'm running into `Cannot read property 'getDialogElement' of null` and `Cannot read property 'remove' of null`.

here is my code snippet, lifted directly from your site, but adopted for a component:

```
import React from 'react';
import ReactDOM from 'react-dom';
import {Modal} from 'react-bootstrap';

export default class ModalDemo extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      showModal: false
    }
    this.close = this.close.bind(this);
    this.open = this.open.bind(this);
  }

  close() {
    this.setState({ showModal: false });
  }

  open() {
    this.setState({ showModal: true });
  }
  render() {
    return (
        <div>
          <p>Click to get the full Modal experience!</p>

          <Button
            bsStyle="primary"
            bsSize="large"
            onClick={this.open}
          >
            Launch demo modal
        </Button>

          <Modal show={this.state.showModal} onHide={this.close}>
            <Modal.Header closeButton>
              <Modal.Title>Modal heading</Modal.Title>
            </Modal.Header>
            <Modal.Body>
              <h4>Text in a modal</h4>
              <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
            </Modal.Body>
            <Modal.Footer>
              <Button onClick={this.close}>Close</Button>
            </Modal.Footer>
          </Modal>
        </div>
    );
  }
}
```

When this code executes however I get the first error on show and the transition animation does not play and its this line `var dialogNode = this._modal.getDialogElement();` in Modal.js that triggers it, because _modal is `null`. Breakpointing through the code, the issue seems to be happening because when the render method is called. When the page first loads, the render method is called, and this function `ref={c => { this._modal = c; }}` is invoked with `c` being the Modal object. However when the state changes (in this case pushing the button, `c` resolved to null and overrides the initial prop. Any functions that have to call Modal properties on _modal now fail.

It's very possible I missed something here and there is an issue with my code, but I can't seem to get this working properly within my context.

**Comment by gmfvpereira** [comment] 2017-04-28 18:50
+1
I have the same issue

**Comment by gmfvpereira** [comment] 2017-04-28 19:16
I couldn't replicate the issue with a brand new setup, though.
https://github.com/gmfvpereira/bootstrap-modal-issue

We are probably missing something here.

**Comment by turboki** [comment] 2017-05-01 22:23
very possible...I have a feeling there is a scoping issue somewhere and the way we're using it is causing issues.

**Comment by jquense** [comment] 2017-05-01 23:59
Try nuking node_modules and reinstalling. It sounds like you have an old copy over react-overlays and a new react-bootstrap

**Comment by ml242** [comment] 2017-05-04 16:41
working here with react-bootstrap@0.30.10.

**Comment by ElTav** [comment] 2017-05-05 03:35
Also getting `Cannot read property 'getDialogElement' of null`  and `Cannot read property remove of undefined` on `react-bootstrap@0.31.0`, have the same basic setup

**Comment by jdarling** [comment] 2017-05-08 17:40
I've managed to narrow this down to you have to create a wrapper around Modal and have it in a different unit than where you are using that wrapper.

So lets say you have a basic component (excuse the ugly, I've been hacking around trying to get down to reproducible):

```js
import React, {Component} from 'react';
import PropTypes from 'prop-types';

import {Modal} from 'react-bootstrap';

class Dialog extends Component{
  constructor({
      visible = false,
      title,
      message,
      children,
      footer,
      onHide
    }){
    super();
    this.contents = message || children;
    this.state = {visible};
    this.footer = footer?<Modal.Footer>{footer}</Modal.Footer>:'';
  }

  close(){
    return this.setState({visible: false});
  }

  open(){
    return this.setState({visible: true});
  }

  render(){
    const {
      title
    } = this.props;
    const {
      visible
    } = this.state;
    const {
      contents,
      footer
    } = this;
    return (
      <Modal show={visible} onHide={this.close.bind(this)}>
        <Modal.Header>
          <Modal.Title>{title}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {contents}
        </Modal.Body>
        {footer}
      </Modal>
    );
  }
};

Dialog.propTypes = {
  visible: PropTypes.bool,
  onHide: PropTypes.func,
  title: PropTypes.string,
  message: PropTypes.string,
  children: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.element,
    PropTypes.func,
    PropTypes.array
  ])
};

export default Dialog;
```

Now some place else you try and use that wrapper:

```js
import React from 'react';
import MyDialog from './dialog';
import {
  Button
} from 'react-bootstrap';

class MyInfoButton extends React.Component{
  constructor(){
    this.footer=(
      <Button onClick={this.hideDialog.bind(this)}>Close</Button>
    );
  }
  
  showDialog(){
    this.dialog.open();
  }

  hideDialog(){
    this.dialog.close();
  }
  
  render(){
    return (
      <span>
        <Button onClick={this.showDialog.bind(this)}>Show Dialog</Button>
        <MyDialog
          ref={dialog=>this.dialog=dialog}
          title="test"
          message="Something important"
          footer={footer}
          />
      </span>
    );
  }
};
```

When you click to show the dialog it will show but you will get this error:

```
Uncaught TypeError: Cannot read property 'getDialogElement' of null
```

When you click the close button the dialog will close but you get this error:

```
Uncaught TypeError: Cannot read property 'remove' of undefined
```

Now, if you go through the trouble of adding in a bunch of log statements to get to the bottom of things
what you quickly come to notice is that because of the state change the dialog gets rendered, the updateStyle handler in the dialog that is going away still gets kicked off, but a new version is created that works successfully. Unfortunately that still leaves things in a broke state and later pages/renders fail all over the place.

Similar happens during close except that this time it is onHide the onDocumentKeyupListener.remove gets called and for the one that has already been destroyed.

Seems like under the hood you are not using componentDidMount and componentWillUnmount to attach/detach listeners and that is causing the malfunction.

Then again, haven't dug that far into React-Bootstrap actual code.

**Comment by StJohn3D** [comment] 2017-05-22 21:26
+1 having the same issue just trying to use jest test on a simple modal.
I tried to create a simple reproducible scenario and discovered a clue to what the bug might be. I noticed that the component name used in the rendering has something to do with it's success. ultimately it came down to whether or not the name has a capital letter.

**The component under test: ConfirmModal.jsx**

```jsx
import React from 'react'
import Modal from 'react-bootstrap/lib/Modal'

export default ({show, onCancel, onConfirm, confirmTitle, confirmBody}) => (
  <Modal show backdrop={true} onHide={onCancel}>
    <Modal.Header>
      <Modal.Title>
        {confirmTitle}
      </Modal.Title>
    </Modal.Header>
    {!confirmBody ? null : <Modal.Body>
      {confirmBody}
    </Modal.Body>}
    <Modal.Footer>
      {/*Custom cancel and delete buttons here, but not relevant to this test*/}
    </Modal.Footer>
  </Modal>
)
```

**The FAILING jest test**
```jsx
import React from 'react'
import renderer from 'react-test-renderer';
const noOpp = x => x

import Foo from '../../../../src/components/Common/Modals/testComponent'

describe("<foo />", () => {
  describe("When given minimum required values", () => {
    it("renders correctly", () => {
      const render = renderer.create(
        <Foo show
                      confirmTitle="Some title text"
                      confirmBody="Some body text"
                      onCancel={noOpp}
                      onConfirm={noOpp}
        />
      ).toJSON();
      expect(render).toMatchSnapshot()
    })
  })
})
```

**The PASSING jest test with a lowercase `f`**
```jsx
import React from 'react'
import renderer from 'react-test-renderer';
const noOpp = x => x

import foo from '../../../../src/components/Common/Modals/testComponent'

describe("<foo />", () => {
  describe("When given minimum required values", () => {
    it("renders correctly", () => {
      const render = renderer.create(
        <foo show
                      confirmTitle="Some title text"
                      confirmBody="Some body text"
                      onCancel={noOpp}
                      onConfirm={noOpp}
        />
      ).toJSON();
      expect(render).toMatchSnapshot()
    })
  })
})
```

**Comment by jquense** [comment] 2017-05-22 23:15
@STJohn3D that's a jsx thing. Lowercase tags are native elements i.e. Html tags while capitalized tags are custom components. The reason it doesn't work with the lowercase is that it's trying to render a html tag foo not your component

**Comment by StJohn3D** [comment] 2017-05-23 13:09
Thanks, that explains why the snapshot looks so incomplete.  Well lowercase aside, there's a repeatable way to get the `Cannot read property 'getDialogElement' of null and Cannot read property 'remove' of null.` issue

**Comment by RiccardoF** [comment] 2017-05-23 13:38
I've the same issue:
`Uncaught TypeError: Cannot read property 'getDialogElement' of null`
and
`Uncaught TypeError: Cannot read property 'remove' of undefined`

with react-bootstrap@0.30.10 and react-bootstrap@0.31.0, did someone find a solution or workaround?

**Comment by sarbull** [comment] 2017-05-24 13:04
Same issue. I'm new to React, i thought i was doing something wrong, i just:

```bash
$ npm install react-bootstrap --save
$ npm install
$ npm start
```

```js
import React, {Component} from 'react';
import {Button, Modal} from 'react-bootstrap';

export default class Example extends Component {
  componentDidMount() {
    this.setState({showModal: false});
  }

  close() {
    this.setState({showModal: false});
  }

  open() {
    this.setState({showModal: true});
  }

  render() {
    return (
      <div>
        <Button bsStyle="primary" bsSize="large" onClick={ this.open }>
          Launch demo modal
        </Button>
        <Modal show={ this.state.showModal } onHide={ this.close }>
          <Modal.Header closeButton>
            <Modal.Title>Modal heading</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            Lorem ipsum dolor.
          </Modal.Body>
          <Modal.Footer>
            <Button onClick={ this.close }>Close</Button>
          </Modal.Footer>
        </Modal>
      </div>
    );
  }
}
```
Results:
![screen shot 2017-05-24 at 16 03 59](https://cloud.githubusercontent.com/assets/1864112/26404438/a76db918-409a-11e7-96da-8e80ec5b76b0.png)

**Comment by jquense** [comment] 2017-05-24 14:12
@sarbull that is different, you are doing something wrong :P you need to initialize state in your component

**Comment by sarbull** [comment] 2017-05-24 14:24
I also added this but still didn't worked.

```js
constructor(props) {
  super(props);

  this.state = {
    showModal: false
  };
```

**Comment by jquense** [comment] 2017-05-24 14:56
Folks I made a codepen with a modal, can someone put together a version that illustrates this bug? I'm not able to recreate it.

https://codepen.io/anon/pen/QvYPKe?editors=1010

**Comment by RiccardoF** [comment] 2017-05-25 09:59
I've update the codepen, there is an example where I'm getting that bug. The problem is that in codepen is working, maybe because all is in one file. Basically I've 2 files, modal-custom.component.js and modal-demo.component.js, in realty in my implementation the first file is inside a repo "components" in github where there all the common components, so it has his package.json, the own react-boorstrap, etc.. The second file is in another repo and in order to use the custom-modal, I just include it. The modal is working, but I get that 2 errors.

**Comment by jquense** [comment] 2017-05-25 11:34
Things being in two different files wouldn't indicate a bug, you probably have two different versions of react-overlays package between your repos that don't work together

**Comment by RiccardoF** [comment] 2017-05-25 15:02
A conflict between the versions is the first thing I thought, I checked, the versions were the same:
modal-custom.component repo
 react-bootstrap@0.30.10
│ ├── classnames@2.2.5
│ ├── dom-helpers@3.2.1
│ ├── invariant@2.2.2
│ ├── keycode@2.1.9
│ ├── react-overlays@0.6.12
│ ├── react-prop-types@0.4.0
│ ├── uncontrollable@4.1.0
│ └── warning@3.0.0

modal-demo.component repo
 react-bootstrap@0.30.10
│ ├── dom-helpers@3.2.1
│ ├── keycode@2.1.9
│ ├── react-overlays@0.6.12
│ ├── react-prop-types@0.4.0
│ ├── uncontrollable@4.1.0
│ └── warning@3.0.0

**Comment by barriehadfield** [comment] 2017-06-09 17:53
Has anyone found a solution to this problem? I am also seeing `Uncaught TypeError: Cannot read property 'getDialogElement' of null` in code that I am sure worked before

**Comment by aosalias** [comment] 2017-06-13 01:39
FWIW, I encountered a similar sounding error, and it was because I wasn't loading the module correctly, viz. a viz.:
```
import { Modal } from 'react-bootstrap/lib/Modal' // <-- WRONG
import Modal from 'react-bootstrap' // <-- WRONG

import { Modal } from 'react-bootstrap' // <-- JOY
import Modal from 'react-bootstrap/lib/Modal' // <-- JOY
```

**Comment by dalpo** [comment] 2017-06-22 17:23
@barriehadfield I resolved adding the `stage-0` to the babel presets.

**Comment by Tommytto** [comment] 2017-07-27 10:04
Have the same issue(

**Comment by 89465127** [comment] 2017-07-30 03:41
Also having this issue. Anyone find a workaround?

**Comment by majidmade** [comment] 2017-08-01 03:24
I encountered this issue on my work computer this morning -- just circled back to it this evening on a personal machine, and can't reproduce! Will do my best to compare/contrast the two environments.

**Comment by pinoytech** [comment] 2017-08-03 03:00
As suggested above I nuked `node_modules` and reinstalled everything. It seems to be an old version. I am currently using, `0.31.2`

**Comment by dan-teitsort** [comment] 2017-08-07 19:29
I had this sort of issue, and determined the root of my troubles was having two different copies of react-dom coming into play on my page.

Initially, I worked around the ```can't read property '<blah>' of null``` symptom by setting my Modal's animate property to false.  That got me far enough that the Modal was visible.  But success was short-lived, because I would get a similar error (iirc, with a different property) when closing the Modal.

I am working with an older version of react-boostrap (0.13.0, I think) that still has the <ModalTrigger /> component.  I noticed it seemed my null property errors were happening in the context of mounts/unmounts, and it seemed <ModalTrigger /> might avoid the unmount, and make the modal go away via css hiding of some sort.  So, I switched to using <ModalTrigger /> to control whether or not my <Modal /> was displayed.  Since I wanted the diplay/no-display mechanism to be automatic (that is, not require a button click or something from the user), I needed to obtain a `ref` to the <ModalTrigger /> so I could call ModalTrigger.show() and ModalTrigger.hide() (or whatever...)  That led to a new, but very fortunate, problem.

The new problem was this error:  https://facebook.github.io/react/warnings/refs-must-have-owner.html

Turns out I did not have two copies of React, rather, I had two copies of react-dom.  I was building a new component separately from the rest of a my app, and in the course of building the UMD-based javascript file for my new component, I was building in a copy of react-dom (among other things).  Telling my build tools to stop including the react-dom in my UMD build artifacts solved the problem!  I was able to turn the animation back to true, and forego using my <ModalTrigger /> hack.

I recall someone earlier mentioning two copies of react were perhaps present in their case, but thinking it was fine because they were the same version.  I would interpret  https://facebook.github.io/react/warnings/refs-must-have-owner.html to mean two copies is bad, period, regardless of the versions.

Btw, in my case I was experimenting with `nwb`, specifically [following this to develop a component library](https://github.com/insin/nwb/blob/master/docs/guides/ReactComponents.md#developing-react-components-and-libraries-with-nwb).  To stop including `react-dom` in my UMD artifacts, I [modified the `nwb.config.js` file as described here.](https://github.com/insin/nwb/blob/master/docs/guides/ReactComponents.md#umd-externals), ending up with this:  ```
module.exports = {
  type: 'react-component',
  webpack: {
    extractText: {
      disable: true
    }
  },
  npm: {
    esModules: true,
    umd: {
      global: 'MyGlobalName',
      externals: {
        react: 'React',
        'react-dom': 'ReactDOM'
      }
    }
  }
}
```

**Comment by knordstrom** [comment] 2017-08-08 16:49
+1. We've tried all workarounds suggested in this thread and nothing has worked. Everything functions properly in the app itself, but the constant errors from the modal dialog are console clutter.

`  "dependencies": {
    "react": "^15.4.2",
    "react-bootstrap": "^0.31.2",
    "react-dom": "^15.6.1",
    "react-grid-layout": "^0.14.7"
  },`

**Comment by knordstrom** [comment] 2017-08-08 17:01
Not sure whether this is a clue or a distraction, but once the initial errors occur on open and close of a modal dialog, resizing the console in Chrome leads to similar errors. Note that there is no modal open when the console is being resized - in fact I can delete every non-script element on the page and the error still occurs.

This is slightly different; it occurs on the next line, ie. `this._modal` is defined but `getDialogElement()` is not available. But is it possible the component is picking up the console window and trying to attach react-bootstrap behaviors to it?

`var e=this._modal.getDialogElement(),t=e.scrollHeight`

> Uncaught TypeError: Cannot read property 'scrollHeight' of null
    at t.updateStyle (dashboard.js:7)
    at t.handleWindowResize (dashboard.js:7)
t.updateStyle @ dashboard.js:7
t.handleWindowResize @ dashboard.js:7
dashboard.js:7 Uncaught TypeError: Cannot read property 'scrollHeight' of null
    at t.updateStyle (dashboard.js:7)
    at t.handleWindowResize (dashboard.js:7)
t.updateStyle @ dashboard.js:7
t.handleWindowResize @ dashboard.js:7

**Comment by jquense** [comment] 2017-08-08 17:02
Please do not +1 this issue without providing a **working** reproduction of the error. There is nothing else we can do otherwise.

At this point tho judging from all the responses here the issue is ALMOST certainly due to having duplicates react instances, and not a bug in the RB code.

**Comment by dan-teitsort** [comment] 2017-08-08 18:10
If you are experiencing this issue, one way to to detect having multiple copies of react or react-dom in play is to simply attempt to get a ref to a component, as described here:  https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components

Maybe there is a more direct way to detect multiple copies, but, like I mentioned earlier, that's how I stumbled upon my multiple copies of react-dom and ultimately the fix that worked for me.

**Comment by DanilaRomaniuk** [comment] 2017-08-21 11:53
@jquense please take a look on this repo https://github.com/DanilaRomaniuk/react-bootstrap-modal-bug/tree/master to reproduce an issue. In case you have any questions - please feel free to ask me.

**Comment by jquense** [comment] 2017-08-21 12:43
@DanilaRomaniuk thanks for putting that together. Your repro demonstrates the problem we've been noting, that the issue is having more than one copy of react or react dom installed. 

I'm going to close this issue for now, it seems clear from folks examples and solutions that the problem is not a bug in RB, but and issue with incorrectly having to many instances of react in a bundle. Thanks for taking the time to try and track stuff down everyone.

**Closed by jquense** 2017-08-21 12:43 UTC

**Comment by timurcatakli** [comment] 2017-08-21 17:12
I was having the same issue when running jest specs and most of the time I solved the problem by adding

`jest.mock('react-bootstrap')`

at the top of the jest spec.

**Comment by dizlexik** [comment] 2017-09-29 17:09
For anyone with this issue that is using Yarn, adding this to my package.json cleared this up for me:
```json
"resolutions": {
  "react": "^15.6.1",
  "react-dom": "^15.6.1"
}
```
Reference: [Selective dependency resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions)

**Comment by elhay-av** [comment] 2017-10-01 10:13
before version 2.9.4 of react-toastr,
react-dom@15.6.1 was specified as dependence
so if you have different react-dom version in your project, you should get 2 copies of react-dom in your build.
witch caused to this error.

fixed in react-toastr@2.9.4 `react-dom` moved to peerDependencies
`
"peerDependencies": {
    "react": "^15.0.0 || ^16.0.0",
    "react-dom": "^15.0.0 || ^16.0.0"
  },
`

**Comment by marcindabrowski** [comment] 2017-10-03 13:33
In React 16 this bug is present again.

**Comment by henriquecf** [comment] 2017-10-10 17:39
In React 16 this bug is present again. (2)

**Comment by aljachimiak** [comment] 2017-10-11 12:48
I'll open a new issue to point out some of my findings.

In the mean time, here is a very simple reproduction of the issue:
[https://github.com/aljachimiak/test-react-bootstrap-modal](https://github.com/aljachimiak/test-react-bootstrap-modal)

**Comment by matt-watson90** [comment] 2017-10-19 16:32
I can confirm that the shim provided by  @aljachimiak fixes the issue for me.

**Comment by rmlevangelio** [comment] 2019-01-26 11:57
@StJohn3D Did you ever managed to make your tests work without updating the library?

**Comment by StJohn3D** [comment] 2019-06-04 19:44
@rmlevangelio I don't remember. We moved off of react-bootstrap to reactstrap a while ago because it supported bootstrap 4
