### ISSUE TITLE
Importing Tooltip results in "Invalid argument supplied to oneOf" warning

### ISSUE THREAD

**Issue by rally25rs** [react-bootstrap/react-bootstrap#3628] opened 2019-04-11 12:40 UTC
Just importing `Tooltip` into a jest test:

```javascript
import {Tooltip} from 'react-bootstrap';

describe('whatever', () => {
  test('nothing', () => {
    expect(true).toEqual(true);
  });
});
```

Results in a warning:

```
 PASS  components/whatever/whatever.spec.js
  whatever
    ✓ nothing (4ms)

  console.error node_modules/prop-types/factoryWithTypeCheckers.js:23
    Warning: Invalid argument supplied to oneOf, expected an array.

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
```

## Versions:

    "react": "16.8.6",
    "react-bootstrap": "1.0.0-beta.6",
    "react-dom": "16.8.6",
    "jest": "24.7.1",

**Comment by taion** [comment] 2019-04-11 13:12
Do you have more details on the stack trace there?

**Comment by rally25rs** [comment] 2019-04-11 13:50
Yep, I had to modify the `prop-types` source to `console.trace` instead, but then I got:

```
    Trace: Warning: Invalid argument supplied to oneOf, expected an array.
        at printWarning (/Users/jvalore/Projects/vht-react-components/node_modules/prop-types/factoryWithTypeCheckers.js:24:15)
        at Object.createEnumTypeChecker [as oneOf] (/Users/jvalore/Projects/vht-react-components/node_modules/prop-types/factoryWithTypeCheckers.js:315:11)
        at Object.<anonymous> (/Users/jvalore/Projects/vht-react-components/node_modules/react-overlays/Overlay.js:216:33)
        at Runtime._execModule (/Users/jvalore/Projects/vht-react-components/node_modules/jest-runtime/build/index.js:858:13)
        at Runtime._loadModule (/Users/jvalore/Projects/vht-react-components/node_modules/jest-runtime/build/index.js:551:12)
        at Runtime.requireModule (/Users/jvalore/Projects/vht-react-components/node_modules/jest-runtime/build/index.js:415:10)
        at Runtime.requireModuleOrMock (/Users/jvalore/Projects/vht-react-components/node_modules/jest-runtime/build/index.js:562:21)
        at Object.<anonymous> (/Users/jvalore/Projects/vht-react-components/node_modules/react-bootstrap/Overlay.js:18:39)
        at Runtime._execModule (/Users/jvalore/Projects/vht-react-components/node_modules/jest-runtime/build/index.js:858:13)
        at Runtime._loadModule (/Users/jvalore/Projects/vht-react-components/node_modules/jest-runtime/build/index.js:551:12)
```

**Comment by mxschmitt** [comment] 2019-04-11 17:39
That seems to be the root cause:

https://github.com/react-bootstrap/react-overlays/blob/8caa4236ac6d016676130d4a3258e77a3b04bd9b/src/Overlay.js#L168-L170

**Comment by bpas247** [comment] 2019-07-24 04:32
Is this still an issue in the latest version (`v1.0.0-beta.10`)?

**Comment by rally25rs** [comment] 2019-07-24 17:02
@bpas247 yes

With `beta.10`

```
    console.error node_modules/react-bootstrap/node_modules/react-overlays/node_modules/prop-types/factoryWithTypeCheckers.js:21
      Warning: Invalid argument supplied to oneOf, expected an instance of array.
```

**Comment by bpas247** [comment] 2019-07-25 08:19
hmm, I can't seem to reproduce the issue in [this CodeSandbox](https://codesandbox.io/s/importing-tooltip-invalid-argument-error-not-showing-up-jsf08).

**Comment by rally25rs** [comment] 2019-07-25 12:26
you know what, the place I always notice them is when running tests in Jest + Enzyme because they clutter up my test output

<img width="917" alt="image" src="https://user-images.githubusercontent.com/38535/61874221-d6f1df80-aeb5-11e9-8b29-191b2c51c3a0.png">

If I find time today I can try to rig up a small project to reproduce the issue...

**Comment by taion** [comment] 2019-07-25 13:29
Might be coming from `popper.js`'s `placements`, as that's the only thing we pass into `oneOf` in here or RO that isn't a literal array. But I can't see why that would be getting stripped.

**Comment by rally25rs** [comment] 2019-07-25 19:33
OK I came up with a super minimal repro project: https://github.com/rally25rs/react-bootstrap-3628

Hope that helps!

**Comment by bpas247** [comment] 2019-07-25 19:49
> OK I came up with a super minimal repro project

That code also doesn't reproduce this bug ([CodeSandbox](https://codesandbox.io/s/github/rally25rs/react-bootstrap-3628)), which doesn't surprise me since it's very similar to my original CodeSandbox.

**Comment by rally25rs** [comment] 2019-07-25 19:50
so this is really interesting... I noticed that in my `package.json` I have:

```
  "jest": {
    "setupFiles": [
      "<rootDir>/node_modules/regenerator-runtime/runtime"
    ],
    "moduleDirectories": [
      ".",
      "node_modules"
    ]
  }
```

If I remove the `.` from that list (so it's just `node_modules`) then the warning does away 😕 

I don't know what that would have to do with anything, but 🤷‍♂ 

I also don't remember why I had to add the `.` there in the first place...

**Comment by kosmiq** [comment] 2020-03-11 10:59
Closing this since no new feedback and the issue seem to be solved.

**Closed by kosmiq** 2020-03-11 10:59 UTC
