### ISSUE TITLE
npm install react-bootstrap --save does not install on node v15.2.1, npm v7.0.8

### ISSUE THREAD

**Issue by raydecastro** [react-bootstrap/react-bootstrap#5538] opened 2020-11-25 11:38 UTC
## Describe the bug

`npm install react-bootstrap --save` does not install on node v15.2.1, npm v7.0.8. 

I'm getting a 

```
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read property 'length' of undefined
```

error

## To Reproduce

1. from ubuntu terminal, execute the following command: `npm install react-bootstrap --save` 
2. the following error message is displayed: 

```
$ npm install react-bootstrap --save
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read property 'length' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     ...-debug.log
```

## Reproducible Example

not applicable

## Expected behavior

react-bootstrap should install without errors or warnings 

## Screenshots

error log file contents: 

```
0 verbose cli [
0 verbose cli   '/home/joe/.nvm/versions/node/v15.2.1/bin/node',
0 verbose cli   '/home/joe/.nvm/versions/node/v15.2.1/bin/npm',
0 verbose cli   'install',
0 verbose cli   'react-bootstrap',
0 verbose cli   '--save'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/joe/love/code/javascript/react/stanford-profiles/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/joe/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/home/joe/.nvm/versions/node/v15.2.1/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 4204655e084f11d7
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 593ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest react-bootstrap@*
26 timing arborist:ctor Completed in 0ms
27 http fetch GET 304 https://registry.npmjs.org/react-bootstrap 577ms (from cache)
28 silly fetch manifest react@^17.0.1
29 http fetch GET 304 https://registry.npmjs.org/react 47ms (from cache)
30 silly fetch manifest react-dom@^17.0.1
31 http fetch GET 304 https://registry.npmjs.org/react-dom 36ms (from cache)
32 silly placeDep ROOT react-bootstrap@1.4.0 OK for: stanford-profiles@0.1.0 want: *
33 silly fetch manifest @restart/context@^2.1.4
34 silly fetch manifest @restart/hooks@^0.3.21
35 silly fetch manifest @types/classnames@^2.2.10
36 silly fetch manifest @types/invariant@^2.2.33
37 silly fetch manifest @types/prop-types@^15.7.3
38 silly fetch manifest @types/react@^16.9.35
39 silly fetch manifest @types/react-transition-group@^4.4.0
40 silly fetch manifest @types/warning@^3.0.0
41 silly fetch manifest classnames@^2.2.6
42 silly fetch manifest dom-helpers@^5.1.2
43 silly fetch manifest invariant@^2.2.4
44 silly fetch manifest prop-types-extra@^1.1.0
45 silly fetch manifest react-overlays@^4.1.0
46 silly fetch manifest react-transition-group@^4.4.1
47 silly fetch manifest uncontrollable@^7.0.0
48 silly fetch manifest warning@^4.0.3
49 http fetch GET 200 https://registry.npmjs.org/@types%2finvariant 53ms (from cache)
50 http fetch GET 200 https://registry.npmjs.org/warning 46ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/@restart%2fhooks 103ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/uncontrollable 126ms (from cache)
53 http fetch GET 304 https://registry.npmjs.org/@types%2fprop-types 146ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/@restart%2fcontext 159ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/react-transition-group 156ms (from cache)
56 http fetch GET 304 https://registry.npmjs.org/@types%2fwarning 172ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/@types%2freact-transition-group 174ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/classnames 190ms (from cache)
59 http fetch GET 304 https://registry.npmjs.org/dom-helpers 202ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/@types%2freact 220ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/prop-types-extra 231ms (from cache)
62 http fetch GET 304 https://registry.npmjs.org/react-overlays 253ms (from cache)
63 http fetch GET 304 https://registry.npmjs.org/@types%2fclassnames 262ms (from cache)
64 http fetch GET 304 https://registry.npmjs.org/invariant 268ms (from cache)
65 timing idealTree:#root Completed in 951ms
66 silly fetch manifest react@>=16.8.0
67 http fetch GET 304 https://registry.npmjs.org/react 38ms (from cache)
68 silly fetch manifest react-dom@>=16.8.0
69 http fetch GET 304 https://registry.npmjs.org/react-dom 38ms (from cache)
70 silly placeDep ROOT @restart/context@2.1.4 OK for: react-bootstrap@1.4.0 want: ^2.1.4
71 silly placeDep ROOT @restart/hooks@0.3.25 OK for: react-bootstrap@1.4.0 want: ^0.3.21
72 silly placeDep ROOT react@17.0.1 KEEP for: @restart/hooks@0.3.25 want: ^16.8.0
73 warn ERESOLVE overriding peer dependency
74 timing idealTree Completed in 1638ms
75 timing command:install Completed in 1640ms
76 verbose stack TypeError: Cannot read property 'length' of undefined
76 verbose stack     at explainDependents (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/lib/utils/explain-dep.js:68:19)
76 verbose stack     at explainNode (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/lib/utils/explain-dep.js:13:3)
76 verbose stack     at explainEresolve (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/lib/utils/explain-eresolve.js:24:24)
76 verbose stack     at explain (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/lib/utils/explain-eresolve.js:64:38)
76 verbose stack     at EventEmitter.log.warn (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/lib/utils/setup-log.js:20:23)
76 verbose stack     at Arborist.[warnPeerConflict] (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1044:14)
76 verbose stack     at Arborist.[placeDep] (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1115:32)
76 verbose stack     at Arborist.[placeDep] (/home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1232:41)
76 verbose stack     at /home/joe/.nvm/versions/node/v15.2.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:772:46
76 verbose stack     at Array.map (<anonymous>)
77 verbose cwd /home/joe/love/code/javascript/react/stanford-profiles
78 verbose Linux 4.4.0-19041-Microsoft
79 verbose argv "/home/joe/.nvm/versions/node/v15.2.1/bin/node" "/home/joe/.nvm/versions/node/v15.2.1/bin/npm" "install" "react-bootstrap" "--save"
80 verbose node v15.2.1
81 verbose npm  v7.0.8
82 error Cannot read property 'length' of undefined
83 verbose exit 1
```

## Environment (please complete the following information)

- Operating System: Ubuntu Version 20.04
- Browser, Version 87.0.4280.66 (Official Build) (64-bit)
- React-Bootstrap Version 1.4.0
- node Version 15.2.1
- npm Version 7.0.8

## Additional context

QUESTION: what latest version of node and npm does react-bootstrap v1.4.0 work on?

**Comment by kyletsang** [comment] 2020-11-25 17:46
Dupe of #5520.  Update npm to the latest version

**Closed by kyletsang** 2020-11-25 17:46 UTC

**Comment by raydecastro** [comment] 2020-11-27 06:52
unable to install npm v7.0.11 or v7.0.14 for some reason. rolled back my npm to 6.14.9 and was able to install react-bootstrap. 

thanks for the info @kyletsang.
