### ISSUE TITLE
Broken react-overlays dependency breaks forms in Modals

### ISSUE THREAD

**Issue by tukkajukka** [react-bootstrap/react-bootstrap#2854] opened 2017-10-24 09:11 UTC
We are using `redux-form` with `react-bootstrap`'s Modal component. Unfortunately Modal uses a broken version of `react-overlays` that won't let the form inputs get focus.

Related issue in `react-overlays`: https://github.com/react-bootstrap/react-overlays/issues/217

Workaround: downgrading `react-overlays` to e.g. 0.7.0 in `npm-shrinkwrap.json` (or installing it as a dependency in your project) fixes the issue.

**Comment by taion** [comment] 2017-10-24 14:27
Effectively a dupe of https://github.com/react-bootstrap/react-overlays/issues/223, will sort out soon

**Closed by taion** 2017-10-24 14:27 UTC
