### ISSUE TITLE
a11y - NavItem with onClick should also have onKeyDown

### ISSUE THREAD

**Issue by andrewdushane** [react-bootstrap/react-bootstrap#2681] opened 2017-06-30 18:32 UTC
A NavItem component that gets an `onClick` prop will generate this warning from react-a11y:

```
SafeAnchor You have `role="button"` but did not define an `onKeyDown` handler. Add it, and have the "Space" key do the same thing as an `onClick` handler. 
```

`onClick` is an explicitly specified prop for `NavItem`, so I believe my usage here is correct. It's basically
```javascript
<NavItem onClick={callbackFunc}>
  Do stuff
</NavItem>
```

I don't see this specific issue addressed in any currently open issues or PRs. I am happy to work on this, but wanted to make sure:
a. this isn't user error
b. nobody's already working on it

**Comment by skwon-mdsol** [comment] 2017-07-06 20:32
Any reason you're not just using the onSelect prop for the nav component that is presumably wrapping your navitem?

**Comment by taion** [comment] 2017-07-06 21:52
This does seem like a potential oversight on `<SafeAnchor>`. Is there an explicit reason we're doing `role="button"` but not responding to "space" keys @jquense?

**Comment by andy-j-d** [comment] 2017-07-07 00:41
@skwon-mdsol I definitely could use `onSelect`, but I don't need `selected` state, so it adds a bit of unneeded complexity.

**Comment by skwon-mdsol** [comment] 2017-07-07 15:40
@andy-j-d hmmm, fair enough

**Comment by jquense** [comment] 2017-07-07 15:43
I think it's reasonable to add a keydown for space in SafeAnchor, if we can confirm that that is the spec'd expected behavior 👍

**Comment by taion** [comment] 2017-07-07 17:44
https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-4

looks like it... yet again upstream TWBS does the wrong thing for a11y, i guess

not fixed in TWBSv4 either

**Comment by andy-j-d** [comment] 2017-07-07 19:46
So according to that link, the keydown behavior should match `onClick` for "enter" and "space". I should be able to open a PR for that next week. Thanks for the feedback @skwon-mdsol, @taion and @jquense.

**Comment by taion** [comment] 2017-07-07 22:19
"Enter" is already handled on `<a>`, so we just need to handle "space". I think it should be safe to do this? Thoughts anyone?

**Comment by jquense** [comment] 2017-07-07 23:26
Should be OK to do yeah

**Closed** 2018-10-19 12:58 UTC
