### ISSUE TITLE
Accordion.Toggle uses deprecated findDOMNode (React.StrictMode) and throws error

### ISSUE THREAD

**Issue by pwillart** [react-bootstrap/react-bootstrap#5666] opened 2021-02-20 02:24 UTC
## Describe the bug

When using React.StrictMode an error is triggered in the browser console when using Accordion to collapse Cards.

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

## To Reproduce

1. Click on a header to collapse/expand
2. Check browser console

## Reproducible Example

https://codesandbox.io/s/crazy-fast-68p0h

## Expected behavior

No warning (error) in console when running in React.StrictMode

## Environment (please complete the following information)

    "react": "^17.0.1",
    "react-bootstrap": "^1.5.0",

**Comment by kyletsang** [comment] 2021-02-21 07:11
Dupe of #5075

**Closed by kyletsang** 2021-02-21 07:11 UTC
