### ISSUE TITLE
findDOMNode error in console when clicking tabs. 

### ISSUE THREAD

**Issue by aaa-manuelhe** [react-bootstrap/react-bootstrap#5904] opened 2021-07-03 15:57 UTC
## Describe the bug

Im using the Tabs and Tab elements from react-bootstrap and  find that even with stripped down basic JSX inside Tab elements I get a findDOMNode erro whenever I click on a tab. The functionality itself works well, but the error message displays. in the browser dev tools console.

## To Reproduce

1. Go to tabs container
2. Click on tab

index.js:1 Warning:  is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition (http://localhost/static/js/vendors~main.chunk.js:18259:30)
    at http://localhost/static/js/vendors~main.chunk.js:12916:24
    at http://localhost/static/js/vendors~main.chunk.js:16762:24
    at div
    at http://localhost/static/js/vendors~main.chunk.js:16678:23
    at TabContainer (http://localhost/static/js/vendors~main.chunk.js:16613:96)
    at Tabs (http://localhost/static/js/vendors~main.chunk.js:16945:96)
    at div
    at MyPage (http://localhost/static/js/main.chunk.js:7919:3)
    at ConnectFunction (http://localhost/static/js/vendors~main.chunk.js:51151:75)
    at Route (http://localhost/static/js/vendors~main.chunk.js:53999:29)
    at Switch (http://localhost/static/js/vendors~main.chunk.js:54201:29)
    at Router (http://localhost/static/js/vendors~main.chunk.js:53634:30)
    at div
    at App
    at Provider (http://localhost/static/js/vendors~main.chunk.js:50864:20)
## Reproducible Example

this is thereturned JSX in my react page
 ` return !myItem? (<Spinner />) : ( 
`    <div>
`      <MyForm myItem={myItem} onChange={handleChange} onSave={handleSave} saving={saving} errors={errors}  />`
`      <Tabs className="tab-section" defaultActiveKey="profile" id="uncontrolled-tab-example">`
`      <Tab eventKey="keyOne" title="One">`
`         <h1>Tab 1</h1>`
`      </Tab>`
`      <Tab eventKey="keyTwo" title=Two">`
`          <h1>Tab 2</h1>`
`       </Tab>`
`       <Tab eventKey="keyThree" title="Three">`
`          <h1>Tab 3</h1>`
`       </Tab>`
`       <Tab eventKey="keyFour" title="Four">`
`           <h1>Tab 4</h1>`
`       </Tab>`

## Expected behavior

I can view expected tab without error message in console

## Environment (please complete the following information)

- Operating System: windows 10
- Browser, Version Version 91.0.4472.124 (Official Build) (64-bit)
- React-Bootstrap Version "react-bootstrap": "^1.5.0",

**Comment by kyletsang** [comment] 2021-07-04 06:09
Dupe of #5075

This is fixed in v2 beta for bootstrap 5 if you want to use that

**Closed by kyletsang** 2021-07-04 06:09 UTC
