### ISSUE TITLE
MenuItem ids

### ISSUE THREAD

**Issue by kennyw12** [react-bootstrap/react-bootstrap#1213] opened 2015-08-25 18:45 UTC
Id props are not passed through on MenuItems. We would like to pass through an id and we think it should be on the anchor tag. Was it an intentional decision to remove it in the [Dropdown rework](https://github.com/react-bootstrap/react-bootstrap/commit/346501e736e280e1b744009412c5285087eb6c90#diff-bb70ed377da60e0f35071b688a96d337L59)?
(@mtscout6)

If not, we'll PR.

The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella

**Comment by mtscout6** [comment] 2015-08-26 02:09
I did not remove them intentionally. Looks like the first bug of the rewrite, sorry about the inconvenience on that.

**Comment by rstormsf** [comment] 2015-08-26 07:32
I've noticed that in Navbar dropdown menuitem, the first element is always `:focused` :-(

<img width="218" alt="react_github_notetaker" src="https://cloud.githubusercontent.com/assets/9360827/9487802/f734f0f4-4b89-11e5-87a7-b7d717068d24.png">

**Comment by jquense** [comment] 2015-08-26 11:31
@rstormf yes. that's a feature not a bug. it's particularly one required for Web accessibility

**Comment by AlexKVal** [comment] 2015-08-26 13:08
It seems there will be more such questions, maybe we should concider documenting of this feature ?

**Comment by jquense** [comment] 2015-08-26 13:15
its documented in the changelog, and since it mostly matches upstream bootstrap I don't think additional documentation is probably needed. But it doesn't hurt either I guess.

**Comment by mtscout6** [comment] 2015-08-26 14:40
The focus on open seems to be a different issue from the theme of IDs on the MenuItem so that should probably move to another issue. Though should only need to be focused if opened via keyboard commands, but not by mouse click right?

**Comment by AlexKVal** [comment] 2015-08-26 18:01
Resolved by https://github.com/react-bootstrap/react-bootstrap/pull/1214

**Closed by AlexKVal** 2015-08-26 18:01 UTC
Labels: bug, help wanted

**Comment by mtscout6** [comment] 2015-08-26 22:17
Did an issue get created for the focus state discussion?

**Comment by rstormsf** [comment] 2015-08-27 09:02
I've never seen any bootstrap based website if a user clicked with a mouse on a dropdown it would focus on first element.
if was opened with keyboard - true, makes sense.

I apologize if I've driven this ticket from the point of Pivotal Labs UI team regarding 
`Id props are not passed through on MenuItems`

**Comment by stubbornella** [comment] 2015-08-27 13:24
IMO, it's better not to have divergent behavior between keyboard behavior and mouse behavior unless there is a really good reason. 




I'd want to focus on the first item in either case.

**Comment by jquense** [comment] 2015-08-27 13:36
@stubbornella thanks for the input I have continued the discussion at #1233 for its own dedicated topic. I am interested in what folks think is the best way to go
