### ISSUE TITLE
onClick stopPropagation() ignored on Dropdown, DropdownButton

### ISSUE THREAD

**Issue by wheezymustafa** [react-bootstrap/react-bootstrap#4176] opened 2019-08-05 00:51 UTC
Hi all, I'm new to React and react-bootstrap, so bear with me.  I'm building a form that is sectioned off by Accordion components.  Within an Accordion, I have a Card with a body, and within that body I have a DropdownButton.  When I select a DropdownButton value, the entire Accordion section collapses.  This can be reproduced on the following simple example:

```
import React from 'react'
import {Accordion, Dropdown, Card} from 'react-bootstrap'

const Test = props => {
    return (
        <Accordion defaultActiveKey="0">
            <Accordion.Toggle as={Card.Header} eventKey="0"><strong>Transaction Details</strong></Accordion.Toggle>
            <Accordion.Collapse eventKey="0">
                <div >
                    <Card body>
                    <Dropdown >
                        <Dropdown.Toggle variant="success" id="dropdown-basic">
                            Dropdown Button
                        </Dropdown.Toggle>

                        <Dropdown.Menu  >
                            <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                            <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                            <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
                        </Dropdown.Menu>
                    </Dropdown>
                    </Card>
                </div>
            </Accordion.Collapse>
        </Accordion>
    )
}

export default Test
```

I believe this has to do with event bubbling, and that my Accordion component's onClick event is also firing.  However, I've tried to set my `stopPropagation()` method on just about every component, but the event continues to make it up to the Accordion.  Note: I've tried using DropdownButton and Dropdown with explicit inner components (Dropdown.Item, Menu, etc) with no difference in result.

I found a similar post here: https://github.com/react-bootstrap/react-bootstrap/issues/2327.  OP attempted to wrap the DropdownButton with a div with success, however I'm still having the same problem even after wrapping with a div.  Is it something I'm not setting correctly?  Thanks in advance.

**Comment by jaril5976** [comment] 2019-11-05 10:06
Same Issue, is there any solution?

**Comment by BenStadnick** [comment] 2019-11-05 20:13
I ran into this as well. It is not caused by event bubbling and onClick propagation is stopped by stopPropagation(). The accordion is collapsing because of a context error. When a DropdownItem is selected, the Dropdown component calls a function provided by SelectableContext. This allows a nested Dropdown to close the top-level Dropdown but it is calling functions provided by other components as well. In this case, the Accordion component.

I've made a fix for this in my fork and will make a pull request. 

If want a fix right now, you can wrap the Dropdown with a SelectableContext provider as a workaround. Simple example: 

```JavaScript
import React from "react";
import { Accordion, Dropdown } from "react-bootstrap";
import SelectableContext from "react-bootstrap/SelectableContext";


const Test = props => {
  return (
    <Accordion>
      <Accordion.Toggle>Toggle Accordion</Accordion.Toggle>
      <Accordion.Collapse>
        <SelectableContext.Provider value={false}>
          <Dropdown>
            <Dropdown.Toggle>Title</Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item>Item1</Dropdown.Item>
              <Dropdown.Item>Item2</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </SelectableContext.Provider>
      </Accordion.Collapse>
    </Accordion>
  );
}

export default Test
```

**Comment by sirajtahrawashmen** [comment] 2019-12-18 10:15
having the same issue here

**Comment by zinovev** [comment] 2020-02-03 19:49
I have the same issue. PR by @BenStadnick isn't merged. Any solution?

**Comment by elfatherbrown** [comment] 2020-02-23 05:08
Fix by @BenStadnick works! Thank you!

**Comment by fp-wojciech-paczula** [comment] 2020-05-25 15:41
Are there any plans to fix this?

**Closed** 2020-08-12 16:59 UTC

**Comment by afmfe-iul** [comment] 2020-10-09 21:58
This issue is also happening when there are nested Accordions. @BenStadnick fix worked for that case also.
