### ISSUE TITLE
Bug - Page Not Found for Tabs Doc Site

### ISSUE THREAD

**Issue by AYColumbia** [react-bootstrap/react-bootstrap#6748] opened 2024-01-03 14:12 UTC
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The Tabs URL references are returning the Page Not Found, e.g., [Tab Components](https://react-bootstrap.netlify.app/docs/components/navs/tabs)

### Expected behavior

When clicking on the referenced links/tabs, the page is expected to load properly.

### To Reproduce

1. Go to https://react-bootstrap.netlify.app/docs/components/navs/#tabs
2. Under "Tabs" click on the Tab Components link, i.e., "Visually represent nav items as "tabs". This style pairs nicely with tabbable regions created by our [Tab components](https://react-bootstrap.netlify.app/docs/components/navs/tabs)."
3. Also under "Tabs" in the Results sample, click on the "Option 2" tab then back to "Active" which will also navigate to the "Page Not Found" [URL](https://react-bootstrap.netlify.app/home).

### Reproducible Example

https://react-bootstrap.netlify.app/docs/components/navs/tabs

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of React-Bootstrap are you using?

2.9.1

### What version of Bootstrap are you using?

5.3.1

![2024-01-03 08_12_49-Page Not Found _ React Bootstrap - ms edge](https://github.com/react-bootstrap/react-bootstrap/assets/6758781/222a40bc-4ab7-4c7e-ac0d-1d40df7a68b6)

**Comment by SahilMahey** [comment] 2024-01-05 04:44
Hi,

I found the issue there. The link in href part is not correct.

![image](https://github.com/react-bootstrap/react-bootstrap/assets/90522898/8b74ffa8-0dfa-45a2-8eeb-c84be8a2eafe)

It should be "https://react-bootstrap.netlify.app/docs/components/tabs" instead. In the case of active links, the href link has been set "#home", which results in page not found error as there is no home page. I have seen bootstrap using only "#" in their active links instead of giving "#home", which can be a solution for this. My assumption might be wrong here and "#home" is there for a reason too. So I will correct the tab content issue but will work on active link after getting some information on it.

Thank you

**Comment by Its-Shashank** [comment] 2024-01-05 18:01
I think the issue is when you refresh an open link, a slash ( / ) is added to the URL. I am giving another example of the same issue. You will find such scenarios throughout bootstrap I suppose.

E.g., `https://react-bootstrap.netlify.app/docs/components/cards` will become `https://react-bootstrap.netlify.app/docs/components/cards/` when you refresh.

After refreshing if you are supposed to click on some link in the documentation, e.g., in the **Navigation** section click on **`navs`** button, you will be redirected to **`https://react-bootstrap.netlify.app/docs/components/cards/navs`** instead, the correct redirection would be **`https://react-bootstrap.netlify.app/docs/components/navs`.**

**Comment by kyletsang** [comment] 2024-03-21 15:40
Fixed in #6781

**Closed by kyletsang** 2024-03-21 15:40 UTC
Labels: bug
