### ISSUE TITLE
Invalid prop 'children' of type 'string' supplied to 'ForwardRef', at Accordion

### ISSUE THREAD

**Issue by Larissagilliane** [react-bootstrap/react-bootstrap#4460] opened 2019-09-12 20:21 UTC
## Describe the bug

Warning about invalid prop 'children' of type 'string' supplied to 'ForwardRef' when trying to render Accordion page.

## To Reproduce

1. Go to Components > Accordion
2. Check at the console 
3. See warning

## Screenshots

![Screen Shot 2019-09-12 at 17 14 21](https://user-images.githubusercontent.com/27821672/64818175-cee32180-d581-11e9-8cc8-c8c2a877eeb1.png)

## Environment 
- Operating System: macOS
- Browser, Version:  Chrome, 76
- React-Bootstrap Version : 1.0.0-beta.12

**Comment by Larissagilliane** [comment] 2019-09-13 15:38
> In https://react-bootstrap.github.io/components/accordion/? I don't see any errors.

Did you check on the development environment and that's no warning ?

**Comment by bpas247** [comment] 2019-09-27 17:23
> > In https://react-bootstrap.github.io/components/accordion/? I don't see any errors.
> 
> Did you check on the development environment and that's no warning ?

There are no errors in the console, so I don't see where the issue is here. I'm gonna go ahead and close the issue for now 🙂 
@Larissagilliane if you could create a CodeSandbox example that reproduces this issue, then please feel free to re-open this 👍

**Closed by bpas247** 2019-09-27 17:23 UTC
