### ISSUE TITLE
Dropdown flip property type error

### ISSUE THREAD

**Issue by SerGioPicconti** [react-bootstrap/react-bootstrap#6376] opened 2022-06-12 17:21 UTC
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [x] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hello!

When I set **flip** attribute to true (boolean) it's throws an error "**_Warning: Received `true` for a non-boolean attribute `flip`_**"

When I change prop value to "true" (string) - it's ok in console, but not in VSCode.

### Reproducible Example

https://codesandbox.io/s/patient-sea-416r25

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.1

**Comment by kyletsang** [comment] 2022-06-14 04:54
Duplicate of #3589

Looks like `flip` being documented in the base dropdown is an error.  Apply the `flip` prop to the dropdown menu instead

**Closed by kyletsang** 2022-06-14 04:54 UTC
Labels: bug

**Comment by SerGioPicconti** [comment] 2022-06-14 05:09
Ok, thx)
