### ISSUE TITLE
Documentation hosted on github is not loading

### ISSUE THREAD

**Issue by jainsid12** [react-bootstrap/react-bootstrap#5289] opened 2020-07-12 03:40 UTC
## Bug on this page - **https://react-bootstrap.github.io/**

When you open the above URL it shows the blank screen.
However if you open other link (ex.-https://react-bootstrap.github.io/components/alerts/) 
and then click on **Home** it works properly.

## To Reproduce

1. Go to this link -  https://react-bootstrap.github.io/

2. See the blank screen

## Expected behavior

It should open the home screen of documentation.

## Screenshots

![Screenshot (36)](https://user-images.githubusercontent.com/53045461/87238311-a2589a00-c41e-11ea-926a-1e1cf442ae1d.png)

## Environment (please complete the following information)

- Operating System: Windows, Android
- Browser: Chrome, Firefox

**Comment by bpas247** [comment] 2020-07-12 05:33
duplicate of #5288

**Closed by bpas247** 2020-07-12 05:33 UTC
