### ISSUE TITLE
Don't set component specific props at HTML elements to avoid Unknown Prop Warning

### ISSUE THREAD

**Issue by ungerik** [react-bootstrap/react-bootstrap#2055] opened 2016-07-15 13:44 UTC
React 15 seems to have added a warning for setting props at HTML elements that are not valid for the element type. Using props spread passes all Bootstrap specific props through, like in the shortened Label example below:

```
class Label extends React.Component {
  render() {
    return (
      <span {...this.props}> // passes bsStyle to <span>
        {this.props.children}
      </span>
```

Warning: Unknown props `bsStyle`, `bsClass` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by Label)
    in Label (created by AppContainer)

**Comment by kelchm** [comment] 2016-07-15 13:56
Duplicate of #1994

**Closed** 2016-07-15 14:12 UTC
