### ISSUE TITLE
State is not updated on Radio inputs when using Button Group with data-toggle

### ISSUE THREAD

**Issue by konung** [react-bootstrap/react-bootstrap#1955] opened 2016-06-09 18:15 UTC
I'm trying to implement a radio buttons  like this 
http://getbootstrap.com/javascript/#buttons-checkbox-radio

They work just fine when I use regular radio inputs. When I add btn-group styling - the state of the radio buttons is not updated. The buttons are clickable - "active" class is added to the button clicked, but the actual radio input is not updated. 

I thought this - might be related (because the actual button obfuscated by BS js was to small) - http://jsfiddle.net/32x7p1hk/5/

But that doesn't seem the issue. The click event is simply not being passed to react. 

If anybody has a working small example of this using React & Bootstrap - I would greatly appreciate if you could share it.

**Comment by taion** [comment] 2016-06-09 18:18
Dupe of https://github.com/react-bootstrap/react-bootstrap/issues/1587

**Closed by taion** 2016-06-09 18:18 UTC
