### ISSUE TITLE
Documentation Change on Navs page

### ISSUE THREAD

**Issue by scottgutman** [react-bootstrap/react-bootstrap#4705] opened 2019-10-18 18:17 UTC
On this page https://react-bootstrap.github.io/components/navs/#tabs  there is a prop named "defaultActiveKey" in many of the examples.  But to make it work, I had to change them to "activeKey"

Just thought you should know.

**Comment by bpas247** [comment] 2019-10-18 18:26
@scottgutman What specifically are the other examples that are using `defaultActiveKey` that you think are wrong?

**Comment by scottgutman** [comment] 2019-10-18 18:55
My goal was to set the Active tab on first render that matched the content
displayed.

This is the code that is on the page:
  <Nav variant="tabs" defaultActiveKey="/home">

I had to use this to make it work:
  <Nav variant="tabs" activeKey="/home">

Also, in the API section, "defaultActiveKey" is not listed, but "activeKey"
is.

There are 12 mentions of "defaultActiveKey" but I have not tested them.


Skylar Scotlynn Gutman
Signature Computer Services, Inc.
(954) 579-5515
skylar@signaturecomputer.com <scottie@signaturecomputer.com>

**Comment by bpas247** [comment] 2019-10-18 19:07
FWIW the `defaultActiveKey` prop is used for the [Accordion](https://github.com/react-bootstrap/react-bootstrap/blob/29294228e91a54a6ae91a54fe23d6165724ce36b/src/Accordion.js#L21-L22) component, since we're using [uncontrollable](https://github.com/jquense/uncontrollable), which will return a `defaultActiveKey` as one of its props (along with the `activeKey` prop and its respective handler that is controlling it). I believe that's what the Nav and all of the other components are also doing, So I don't really see where the issue is here.

**Comment by bpas247** [comment] 2019-10-18 19:11
At most, it seems like we're just missing the proptypes for the `default` prefixed props returned from `useUncontrolled`

**Comment by scottgutman** [comment] 2019-10-18 19:16
I understand.  I am just letting you know about my experience and that
setting "defaultActiveKey" prop did not work for me and "activeKey" did.

Thank you for the reply.  I do apreciate it. I wanted to help.


Skylar Scotlynn Gutman
Signature Computer Services, Inc.
(954) 579-5515
skylar@signaturecomputer.com
<scottie@signaturecomputer.com>

**Comment by bpas247** [comment] 2019-10-18 19:55
> I understand.  I am just letting you know about my experience and that
setting "defaultActiveKey" prop did not work for me and "activeKey" did.

Really depends on your use case tbh 🤷‍♀ `defaultActiveKey` prop is typically used for setting the initial value of `activeKey` while keeping everything else uncontrolled (e.g. you don't have to handle passing in `activeKey` prop at all and let the component itself handle it), whereas passing in the `activeKey` props allows you to control the component. For example:
```jsx
const Thingy = () => (
<Nav variant="tabs" defaultActiveKey="link-1">
  <Nav.Item>
    <Nav.Link href="/home">Active</Nav.Link>
  </Nav.Item>
  <Nav.Item>
    <Nav.Link eventKey="link-1">Option 2</Nav.Link>
  </Nav.Item>
  <Nav.Item>
    <Nav.Link eventKey="disabled" disabled>
      Disabled
    </Nav.Link>
  </Nav.Item>
</Nav>
);
```
this will always default the initial `activeKey` value to have `link-1`, which corresponds to the `Option 2` component, but notice this component is still uncontrolled.
```jsx
const Thingy = () => {
  const [activeKey, setActiveKey] = useState("link-1");
  return (
    <Nav variant="tabs" activeKey={activeKey} onSelect={eventKey => setActiveKey(eventKey)}>
      <Nav.Item>
        <Nav.Link href="/home">Active</Nav.Link>
      </Nav.Item>
     <Nav.Item>
      <Nav.Link eventKey="link-1">Option 2</Nav.Link>
    </Nav.Item>
    <Nav.Item>
      <Nav.Link eventKey="disabled" disabled>
        Disabled
      </Nav.Link>
    </Nav.Item>
  </Nav>
  )
};
```
This essentially does the same thing as the first example, but notice how we had to make it a controlled component to do so. If we just passed a hard value into the `activeKey` prop with no `onSelect`, then the `activeKey` will always be the same (and the Nav component will cease to work properly). Whichever approach you decide to do is dependent on your use case, but just note that `activeKey` and `defaultActiveKey` are not really meant to be used for the same use case, since they do different things.

**Comment by scottgutman** [comment] 2019-10-18 20:55
Now I understand.  Thank you for the explanation.  I did not get it until
now.

Skylar Scotlynn Gutman
Signature Computer Services, Inc.
(954) 579-5515
skylar@signaturecomputer.com <scottie@signaturecomputer.com>

**Comment by bpas247** [comment] 2019-10-18 21:02
Anytime 😄 I think I'm gonna go ahead and close this issue for now, if you still want `defaultActiveKey` to be documented as part of the API docs, I would suggest opening a new issue for that 👍

**Closed by bpas247** 2019-10-18 21:02 UTC
