### ISSUE TITLE
Document that ToggleButtonGroup doesn't work when Bootstrap JS is present

### ISSUE THREAD

**Issue by spiroski** [react-bootstrap/react-bootstrap#2774] opened 2017-08-30 13:23 UTC
This is my code:
```
<ToggleButtonGroup
    name="eventType"
    type="radio"
    value={this.state.eventType}
    onChange={(eventType) => this.setState({eventType})}>
    <ToggleButton bsStyle="default-washed"
                  value="business">
        Business
    </ToggleButton>
    <ToggleButton bsStyle="default-washed"
                  value="leisure">Leisure
    </ToggleButton>
</ToggleButtonGroup>
```

The state is not being changed. However the selected value in the component itself changes as the active button changes. I've tested other places as well. This happens after I've updated from 0.31.0 to 0.31.2

**Comment by taion** [comment] 2017-08-30 16:27
Same as https://github.com/react-bootstrap/react-bootstrap/issues/2734. We can't do anything without a runnable repro.

**Comment by jquense** [comment] 2017-08-30 16:28
i'm still fairly sure this is because of a bug in radio/checkboxes in React 15.6.1

**Comment by alexschilpp** [comment] 2017-09-13 11:47
Still having this problem. @taion repro was posted in issue #2734 
https://github.com/react-bootstrap/react-bootstrap/issues/2734#issuecomment-318102096

**Comment by taion** [comment] 2017-09-13 11:56
As you can see from the following 2 posts in that thread, that was not actually repro.

**Comment by alexschilpp** [comment] 2017-09-14 11:57
@taion sorry, it looks like the problem is not in your library.

Reproduced it and everything works fine
https://codepen.io/alexschilpp/pen/PJwdxX

**Comment by kamote** [comment] 2017-10-06 12:03
@alexschilpp It seems the issue occurs when **bootstrap** js lib included
[https://codepen.io/kamote/pen/gGvadB](url)

**Comment by avremel** [comment] 2017-10-17 20:22
@kamote I am having the same issue, my Checkbox is not being toggled while my non bootstrap checkbox works fine. I have regular bootstrap running for non react pages, besides for react-bootstrap. Any workaround?

**Comment by RKushnir** [comment] 2017-10-24 14:17
@kamote Probably, because react-BS adds a `data-toggle="buttons"` attribute, and BS attaches its handler to the elements that have those.

**Comment by taion** [comment] 2017-10-24 14:25
@jquense Should we drop the `data-toggle` prop?

**Comment by taion** [comment] 2017-11-08 20:41
It sounds like the resolution here is that users must not include the Bootstrap JS when using toggle groups here.

This would be a great addition to the docs, if anybody cares to PR.

**Comment by iancullinane** [comment] 2017-11-09 19:09
I am still having this problem with the BootstrapJS removed. Is there another fix?

**Comment by reduxdj** [comment] 2017-12-06 04:14
Same here

**Comment by mreishus** [comment] 2017-12-15 17:19
There's also a workaround of setting an `onClick` handler on each individual `ToggleButton`.  This worked for me (I'm working on an app where removing the bootstrap JS is not an option).  This would be good to document as well.

**Comment by vinodsantharam** [comment] 2018-01-04 10:38
@mreishus this workaround makes my day. As you, I can't remove bootstrap JS. 
If this bug will be still there in the 1.0, it would be nice to document it (official doc, release notes, ...).

**Comment by tomscott1** [comment] 2018-01-08 08:45
@taion I'm happy to create a PR to update this documentation I can't see `ToggleButtonGroup` in the documentation anywhere. Am I missing something?

**Comment by taion** [comment] 2018-01-08 16:24
@jquense did this get dropped from the new docs?

**Comment by jquense** [comment] 2018-01-08 16:31
It's definitely possible

**Comment by mattblackdev** [comment] 2018-01-11 22:06
So I was looking for this component, didn't see it in the docs. I typed ```import { Toggle...``` in vs code and saw it does exist. Then I started to lose my mind wondering why my onChange was not getting called. I read the source code and didn't see any reason. Moral of the story, never forget that ```Github issues >= documentation```.

**Comment by mobilutz** [comment] 2018-01-12 14:23
I looked a little bit into the issue as I also have the need to have `bootstrap.js` and `react-bootstrap` in my application.

These are the problematic lines in (at least) boostrap-3.3.7:
https://github.com/twbs/bootstrap/blob/v3.3.7/js/button.js#L66

Here `checked` is being change and with that, `react-bootstrap` does not see any change.


And in combination, this line is affecting the outcome as well:
https://github.com/twbs/bootstrap/blob/v3.3.7/js/button.js#L115

If the event is  not propagated, `react-bootstrap` does not see it.


Furthermore, I could not make `onChange` work on `ToggleButton` itself. Need to investigate this a bit further.

**Comment by taion** [comment] 2018-03-05 17:45
this was fixed in #2956

**Closed by taion** 2018-03-05 17:45 UTC
Labels: docs, help wanted

**Comment by stevehanson** [comment] 2018-05-08 21:51
In case anyone else stumbles over here, I just wanted to say that I was able to get this to work, though my solution is a bit hacky. I found in [the Bootstrap source](https://github.com/twbs/bootstrap/blob/v3.3.7/js/button.js#L109) that the toggle button code event handling is set up like this:

```javascript
$(document).on('click.bs.button.data-api', '[data-toggle^="button"]', function (e) {
  // handle the click
})
```

I was able to disable this in my React app with the following:

```es6
componentDidMount() {
  $(document).off('click.bs.button.data-api', '[data-toggle^="button"]')
}
```

React Bootstrap is now working for me for toggling button groups. This is not a great solution since it would break any other Bootstrap JS toggle buttons on the page, but I'm sure it could be expanded on easily enough for a more generic solution.

I could put something together for a PR if this is something this library would be interested in.

**Comment by jfouse** [comment] 2020-09-05 20:57
@stevehanson That was exactly what I needed, thanks.  In my case the toggle group is in a modal, so in my code that's about to open the modal I have this:

```
// Disabling a very specific bootstrap event handler while the modal is open
// so our ToggleButtonGroup can actually work the way it's supposed to.
// We save the handler here before removing it, and reinstate it on modal close.
// https://github.com/react-bootstrap/react-bootstrap/issues/2774#issuecomment-387553896
const clickHandlers = $._data( $(document)[0], 'events' ).click;
const icedHandler = clickHandlers.find(({namespace}) => namespace == 'bs.button.data-api').handler;
$(document).off('click.bs.button.data-api', '[data-toggle^="button"]')
```
Then later when the modal gets closed, I simply reinstate it:
```
// reinstate bootstrap toggle click handler
$(document).on('click.bs.button.data-api', '[data-toggle^="button"]', icedHandler)
```
This way if there does happen to be anything else relying on it that bootstrap handler elsewhere in the page it should continue to function as expected.  It's a bit of a special case because it doesn't help folks who want to use the toggle group on the main page, but I wanted to at least point out that it's possible to save and then reinstate it if that helps a given scenario.
