### ISSUE TITLE
Popover renders offscreen

### ISSUE THREAD

**Issue by adrianmc** [react-bootstrap/react-bootstrap#1555] opened 2015-12-10 04:09 UTC
I have a list of items in a scrollable container. Whenever I try to render the popover for the bottom item, the popover ends up showing below the viewport (where you cannot see its contents).

![screen shot 2015-12-10 at 12 01 19 pm](https://cloud.githubusercontent.com/assets/943555/11706774/ef38bbe6-9f36-11e5-91bb-8f50f9484c2e.png)

```jsx
renderOverlay() {
  return (
    <Popover title={this.props.title} {}>
      ...
    </Popover>
  );
}

render() {
  return(
    <OverlayTrigger
      rootClose
      ref="overlayTrigger"
      trigger="click"
      placement="bottom"
      overlay={this.renderOverlay()}
    >
      <a href="#"><i className="fa fa-fw fa-plus-circle" /></a>
    </OverlayTrigger>
  );
}
```

Do I have to make a custom Overlay or does this library support the intelligent positioning of these overlays in a scrollable list?

**Comment by taion** [comment] 2015-12-10 14:31
Dupe of https://github.com/react-bootstrap/react-bootstrap/issues/451.

**Closed by taion** 2015-12-10 14:31 UTC
