### ISSUE TITLE
Bootstrap 4 Roadmap

### ISSUE THREAD

**Issue by chrishoage** [react-bootstrap/react-bootstrap#1187] opened 2015-08-19 18:01 UTC
Bootstrap 4 [was announced today](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/), I am curious where Bootstrap 4 fits in on the [roadmap](https://github.com/react-bootstrap/react-bootstrap/wiki#100-roadmap), if at all?

**Comment by jquense** [comment] 2015-08-19 18:06
we don't know yet! Eventually we will support it, although its too early to say how hat will happen, untill we have a better understanding of the breaking changes it brings.

**Comment by chrishoage** [comment] 2015-08-19 18:16
Good to hear! I obviously don't expect to see support any time soon, I just wanted to start the discussion for everyone to better track it. Looking at what is in the alpha there are certainly some breaking changes but it doesn't look wildly different.  

Thank you for the awesome project!

**Comment by taion** [comment] 2015-08-19 22:04
We should think about the versioning strategy though - ideally you'd want to use a prerelease for this, but that didn't work so well for my `react-pre` thing.

**Comment by jquense** [comment] 2015-08-19 22:29
well it gets easier once we hit a major version we know isn't going to break for a long while. Theoretically if we get stable we can just follow upstream for major versions

**Comment by mtscout6** [comment] 2015-08-20 15:29
_Note: I typed this up and jumped around a lot, more thoughts than any clear direction here. I also haven't dug too deeply into Bootstrap v4 yet so some of this may need more thought._

This has been leading me to wonder if we should just declare 1.0 instead of push 0.25 (Many people are using this library in production anyways). We have been doing a good job of making sure we don't introduce regressions so we are well practiced at this point in following SemVer considerations. Doing this would give us one more number in the version to help convey these changes, though it doesn't entirely solve the problem as you can see later in this comment. _IMHO I don't think this will really help with this problem._

I think that by the nature of the fact that we derive from two major libraries that have churn our versions will likely be bumped frequently. Although if we focus too much on keeping up with betas of our dependencies we introduce another headache, for example how do we produce our betas as @taion points out with the react v0.14 beta changes.

Welcome to dependency hell for OSS project management!

Do we propose maintaining four betas? One for each of the following:

- React Beta `v0.25-react-beta` (If React v0.14 doesn't land before we push v0.25 this was misleading)
- Bootstrap Alpha `v0.25-bootstrap-alpha` (If Bootstrap v4 doesn't land before we push v0.25 this was misleading)
- Both combined `v0.25-react-beta-bootstrap-alpha` (The likelihood that both land before we push v0.25 is well let's face it not going to happen)
- Only our breaking changes against current react and bootstrap versions `v0.25-beta`

Thinking about this is already making my head spin. The git tree for all of this will become a full time job to maintain and coordinate between all interested parties.

Another thought that has just crossed my mind is to just push out a new npm package for these things. Each package can follow it's own versioning for it's scope of interest. I'm thinking something like:

- react-bootstrap-edge - Latest Alpha/Beta Releases from React and Bootstrap
- react-bootstrap-edge-react - Latest Alpha/Beta Releases of React only
- react-bootstrap-edge-bootstrap - Latest Alpha/Beta Releases of Bootstrap only

Although that proposal will still result in a git tree that is very cumbersome.

Another proposal that comes to mind is to maintain both versions of Bootstrap simultaneously, and keep dealing with React the way we are now. This would be a good exercise in making sure our components are more modular, and quite possibly not so tied to Bootstrap. (Modals are making great headway in this arena, thanks to @jquense). 

One way we can do this is to have a static overridable configuration to state which version of Bootstrap is active, and pivot off any class name changes. I'm not too keen on this one and I'll bet it's not just class name changes in Bootstrap v4. 

We can also add a `v4` folder to our library for components that are different. I would want to have our webpack/bower distribution build `react-bootstap-bs4.js` and `react-bootstrap-bs4.min.js` so we aren't bundling both Bootstrap versions for those not rolling their own builds.

**Comment by taion** [comment] 2015-08-20 18:29
The Cartesian product thing is a bit scary. Personally, I think we should support right now e.g.:

* react-bootstrap@0.24.5
* react-bootstrap@0.25.0-alpha.1
* react-bootstrap[react-0.14]@0.24.5
* react-bootstrap[bootstrap-4]@0.24.5 (if necessary)

i.e. for the "edge" dependency variants, only support the current stable release, instead of maintaining alpha releases for everything.

I like the new NPM package idea - pre-releases don't really work for these sorts of "alternate" releases, since they're entirely separate release tracks with no ordering relative to the "standard" releases.

Life would be a lot easier if we can support Bootstrap 3 and Bootstrap 4 in the same package, though, without having to release a separate `react-bootstrap-bs4`.

**Comment by AlexKVal** [comment] 2015-08-21 21:11
`React-0.14` introduces breaking changes. 
(`React-0.15` We all know it - will introduce another breacking changes. ...etc)
`Bootstrap-4` introduces big breaking changes too.

Documentation sites for all four combinations have to be pretty different.
At least `Components` part for sure.

--
What about this ? Let's split up it all into modules.

We already have some good beginnings in this direction:
`react-overlays`, `react-prop-types`.. 
I would also suggest to move into separate pkg `Dropdowns`, because I'm sure many developers will want it standalone. ...etc.

Let's split up it all into modules.
`R-B common`, `Dropdowns`, `react-overlays` etc...

And then have four - `combinations of smaller modules` - projects:
B3 + R0.13
B3 + R0.14
B4 + R0.13
B4 + R0.14
(and with `React-0.15` even more)

Each one will contain its own version of `Components` part of documentation,
all specifics, like `BT4 cards` ...etc.

As time goes by, old versions `B3 + R0.13` will be less and less used and updated..
and the newest like `B4 + R0.14` will have more attention o/c.

In theory it will split concerns and will greatly simplify those projects for new contributors.

- it will simplify versions merging hell
- one who needs particular feature for particular version - will clearly see where them should create Issues and PRs. 
(instead of every time re-submitting their PRs against another particular branches as it happens now)

--
I have no such experience as you have and hence I don't see many `deep water stones` / subtle hindrances with this approach.

But I believe that modularity / spliting up into independent modules - should answer to all those concerns
we have because this project is always the child of other two.
Unix* way and OSS way go exactly in this direction.

**Comment by AlexKVal** [comment] 2015-08-24 20:31
That's what I'm talking about :smile: The future has to be something like that:
<img width="1118" alt="screen shot 2015-08-24 at 11 26 49 pm" src="https://cloud.githubusercontent.com/assets/847572/9451515/ce2275ba-4ab7-11e5-9c3d-c730b484fc74.png">
http://reapp.io/

--
It should help to all those who don't like or don't want to use browserify/webpack machinery.
https://news.ycombinator.com/item?id=10108829
> `andy_ppp`
I am using react-bootstrap but I wish I hadn't - it's quite large (113kb minified, without including anything from bootstrap itself) and doesn't do very much above and beyond using standard bootstrap classes and standard HTML tags.
It also means you'll probably end up having to include jquery for things which adds another very large amount of code...
I'm pretty happy with bootstrap as a quick good looking (with a theme) win, but I think one day I'd like to get rid of it and write some simpler problem specific CSS and use React proper for any Javascript interactions.

**Comment by andrewsuzuki** [comment] 2015-10-31 18:26
Any problems using react-bootstrap components with bootstrap 4 css/html?

**Comment by taion** [comment] 2015-11-01 03:22
The automatically added class names still target Bootstrap 3, so anything that's changed won't work.

**Comment by bioinforx** [comment] 2015-11-26 00:21
Any progress or plan on beta or final Bootstrap 4 version releasing?

**Comment by taion** [comment] 2015-11-26 00:58
How can we possibly release a "final" Bootstrap 4 version when Bootstrap 4 upstream is still in alpha?

**Comment by bioinforx** [comment] 2015-12-08 20:17
Do you have timeline plan for Bootstrap 4 beta?

**Comment by jquense** [comment] 2015-12-08 20:18
@bioinforx nope!

**Comment by Kepro** [comment] 2015-12-31 11:13
rly want this :+1:

**Comment by 9point6** [comment] 2016-01-25 18:24
Any updates on this? Starting a new build soon and would like to use bootstrap 4

**Comment by jquense** [comment] 2016-01-25 18:35
We aren't going to start implementing any of Bootstrap 4 until it is marginally stable, definitely not before "beta". maybe not before the RC's

**Comment by z-ax** [comment] 2016-01-26 16:22
As far as markup was changed for lots of stuff, don't see a reason to spend your time yet. Can be changed again as well before the final release.

**Comment by auvipy** [comment] 2016-02-17 17:20
probably bootstrap4+ react0.15

**Comment by taion** [comment] 2016-02-17 18:11
No – _definitely_ not until TWBS4 leaves alpha.

**Comment by jquense** [comment] 2016-02-17 18:27
I am going to Lock this for now, since I think additional comments obscure our current position.

the __tl, dr.__ here is:

- we __will__ support bootstrap 4
- we __will not__ start that support until bootstrap 4 is stable enough that we can reasonably develop against it without it constantly changing.

We can re-open this thread for comments and discussion once we get to a spot where there is something actionable to be done.

**Comment by taion** [comment] 2016-03-30 14:58
From https://github.com/react-bootstrap/react-bootstrap/issues/1735, @julien-f reports that they've started working on TWBS 4 support in https://github.com/vatesfr/react-bootstrap.

Is TWBS 4 getting closer? Should we consider maintaining a prerelease that supports TWBS 4? Are the implementations even compatible?

**Comment by julien-f** [comment] 2016-03-30 15:13
We just (literally) started working it and it seems it's not too far from Bootstrap 3.

The next Bootstrap release will be the [alpha 3](https://github.com/twbs/bootstrap/milestones/v4.0.0-alpha.3) but I have no idea when :/

**Comment by kandros** [comment] 2016-03-30 15:35
I would like to get involved

**Comment by julien-f** [comment] 2016-03-31 10:35
I just published a react-bootstrap-4 package while waiting for an *official* tag ;)

**Comment by auvipy** [comment] 2016-03-31 10:36
link?

**Comment by julien-f** [comment] 2016-03-31 11:05
@auvipy 
Repository: https://github.com/vatesfr/react-bootstrap
Package: https://www.npmjs.com/package/react-bootstrap-4

**Comment by olalonde** [comment] 2016-06-16 19:45
@julien-f mind building the demo/docs to gh-pages so we can see how it looks?

**Comment by julien-f** [comment] 2016-06-20 12:39
@olalonde I am not sure what you are asking for, we have made no changes in the demos nor in the docs in our fork, we have just fixed a couple of issues which were bothering us in one of our project using Bootstrap 4.

**Comment by olalonde** [comment] 2016-06-20 18:34
@julien-f I understand, would just be useful to quickly see how the v4 components look like and if any of them aren't working

**Comment by julien-f** [comment] 2016-06-21 15:54
We have not changed much things:

- [DropdownMenu template](https://github.com/vatesfr/react-bootstrap/pull/1/files) has been updated
- [Pagination](https://github.com/vatesfr/react-bootstrap/pull/3/files) as well
- Panels are not working because they have been replaced by [cards](http://v4-alpha.getbootstrap.com/components/card/), we have not wrote take care for this ATM

**Comment by joshmanders** [comment] 2016-09-06 02:21
So v4 has now been set as the primary focus, any status on v4 going on? https://github.com/twbs/bootstrap/issues/20631

**Comment by dreyks** [comment] 2016-09-10 00:01
I think it's better to wait for at least the first beta.

**Comment by curran** [comment] 2016-09-18 16:42
Might it be possible to introduce an API to set the Bootstrap version? Something like

```js
require('react-bootstrap').bootstrapVersion(4);
```

Then the changes in the fork by @julien-f could be integrated back into this codebase, but only enabled if `bootstrapVersion(4)` was called before any components are rendered.

**Comment by julien-f** [comment] 2016-09-18 16:55
I think it's a bad idea to complexify the code and have a runtime switch, we should really start to work on BS4 on a different branch.

And my fork really does not have much value, it would make more sense to work here directly :)

**Comment by Tiendq** [comment] 2016-10-06 08:36
Yeah, just intro a new branch for BS4 and start working on this one. It doesn't make sense to have any version configuration since BS3 itself is retired very soon.

BS4 is coming soon, I have used BS4 myself for production sites, and it works very well.

**Comment by geminiyellow** [comment] 2016-12-13 11:49
is there some new news?

**Comment by harsimranb** [comment] 2017-01-24 21:52
Do you guys have any update on this?  v4 Alpha 6 came out and the code base seems to be getting more stable.  Would love to see some development, and potentially contribute!

**Comment by gnanaprakash** [comment] 2017-01-25 00:14
Thank you guys for great work. Any timeline on BS4 support will be appreciable

**Comment by jquense** [comment] 2017-01-25 00:45
we have no time line yet. like I mentioned above, it's not likely we will even start work until it's out of alpha, or even beta. anything sooner is unmanageable for the team what API churn

**Comment by gnanaprakash** [comment] 2017-01-25 03:07
Thank you. Would there be any level of change in react-bootstrap API for BS4? or will it be smooth or transparent migration for an application to switch from BS3 to BS4

**Comment by jquense** [comment] 2017-01-25 03:16
almost certainly breaking changes, it's major bump for bootstrap, but we don't really have a clue until the v4 API settles down

**Comment by jquense** [comment] 2017-01-25 03:17
that said I think RB probably we have a much easier migration path for apps than users of plain bootstrap because of the react component model lets us do better encapsulation

**Comment by gnanaprakash** [comment] 2017-01-25 06:05
That's going to cool and best about the abstraction. Thanks.

**Comment by jochenberger** [comment] 2017-02-08 08:43
You could probably even provide a compatibility layer, to ease the transition wrt. some removed components, e.g.
```jsx
const Well = (props)=> {
  warning('Please use Card instead of Well');
  return <Card {...props} />;
};
```

**Comment by valorize** [comment] 2017-04-11 13:23
Does it makes sense to concentrate v4 work on reactstrap.github.io for Bootstrap 4 instead?

**Comment by NullVoxPopuli** [comment] 2017-04-23 23:57
is reactstrap the goto now? react-bootstrap for 3, and reactstrap for 4?

**Comment by taion** [comment] 2017-04-24 02:17
I believe https://github.com/react-bootstrap/react-bootstrap/issues/1187#issuecomment-132807953 still stands.

It's a bit tricky for everyone involved until Bootstrap 4 hits substantive API stability – probably until things get to the betas.

**Comment by tab00** [comment] 2017-04-29 03:02
I think the demand for Bootstrap 4 support is quite strong already.

I've noticed that all themes at startbootstrap.com are available for Bootstrap 4.

I will start to use react-bootstrap when it also officially adopts Bootstrap 4. I will wait patiently and stick with  plain Bootstrap 4 in the meantime (which I have used it in production for over a year so far).

**Comment by NullVoxPopuli** [comment] 2017-04-29 03:12
reactstrap is actually really solid

**Comment by jharris4** [comment] 2017-08-11 14:13
Bootstrap 4 beta just landed: http://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

So maybe things will be stable enough now to start supporting it?

**Comment by jquense** [comment] 2017-08-11 14:15
#2752 @jharris4

**Comment by kevingzhang** [comment] 2017-08-13 22:28
I tested the bootstrap4 beta, it has a problem with latest Reactstrap. So I revert it back to alpha6 for now.

**Comment by mcquiggd** [comment] 2017-08-22 20:59
Is there any possibility of uniting effort and resources behind Reactstrap, going forward for Bootstrap 4, or are the differences in philosophy / approach too dissimilar?

I'm not making any value judgements on either project, and I do understand that variety can often bring benefits through competition, cross-pollination etc... just throwing it out there...

**Comment by jquense** [comment] 2017-08-22 21:32
We are open to collaborating. It depends on if @eddywashere and other reactstrap contributors are interested as well. Both projects are fairly mature at this point and it can be tough to make sure everyone's needs are met. We are more than happy to talk it through if there is interest

**Comment by eddywashere** [comment] 2017-08-23 18:54
Been a little busy but 100% interested. I was tracking this issue for awhile. Some context, this issue was locked for a period of time, which was totally appropriate, but was a big motivation for creating reactstrap. With reactstrap I wanted to target bs4 releases asap and took it as a chance to explore different component apis.

I'm happy to help unify efforts. I'd take it a step further and suggest asking twbs/bootstrap folks to strongly consider bringing in this collaboration into twbs org. I think there's some really cool possibilities for the evolution of bootstrap and I don't think it's possible strictly from a 3rd party react library perspective.

**Comment by taion** [comment] 2017-08-23 19:17
@eddywashere Awesome to hear that. Out of curiosity, what do you mean w/r/t evolution of TWBS?

**Comment by mcquiggd** [comment] 2017-09-10 16:23
I think this would be a win for everyone. I have my own (far less popular) open source contributions, typically more esoteric, and time is tight, **but** I would be interested in working on a merged project that brings together such talented contributors.

**Comment by mcquiggd** [comment] 2017-09-10 16:25
I think this would be a win for everyone. I have my own (far less popular) open source contributions, typically more esoteric, and time is tight, but I would be interested in working on a merged project that brings together such talented contributors.

Let's build some momentum.

@jquense @eddywashere

**Comment by taion** [comment] 2017-09-13 03:13
@eddywashere Mind if we start by adding the reactstrap folks to this org? Anyone other than you and @TheSharpieOne?

**Comment by sustained** [comment] 2017-09-13 15:45
I'd really like to help.

The issue is that I don't yet have a great deal of React (nor Bootstrap) experience. That said, I've been learning React; Bootstrap and a bunch of other stuff, lately and I'm quite enjoying it all (I burned out many many years ago). Also, I'm aiming to get a web development ASAP, so then I'm dedicated to all of this.

I have, however, been working with HTML/CSS/JS and various programming languages for nearly 15 years, mostly as a hobby. I don't claim to be good at this, though. :stuck_out_tongue:

I don't have a portfolio, yet. I plan to build one at some point, presumably in React once I've grown more accustomed to it. I'll also need to accrue some open-source contributions (hence this message) as well as work on some pet projects, so that I have some recent and more-well-developed things to show (many of my pet projects over the years were eventually abandoned).

I've done a handful of websites for companies freelance though so if you need some kind of proof that I know at least... something, then I can PM links to those. I don't really have much to show on my Github/Gitlab either, as almost all of my freelance web development; my hobby game development and the various other pet projects are in private repos right now.

But I can share images and such, as I said. It's just going to take me a lot of time to get a proper portfolio together. I have more than a decade of projects scattered over several hard drives and websites.

I wouldn't blame you for not being comfortable letting someone like myself touch the codebase - that's fair enough but I enjoy writing, too, thus could perhaps work on documentation to begin with. If there's anyone who would be willing to get me up to speed with how things are done and organised here, though, then I would presumably be fine to get my hands dirty after a short while.

I also have a lot of free time (unemployed). :wink: 

End novel.

**Comment by jquense** [comment] 2017-09-13 16:30
@sustained we are always glad to have contributors, if you are particularlly interested in v4 support i would support working off my branch/pr #2752 and adding test case stories for each component like i've been doing. Best first to identify what doesn't "just work" and what needs to change.

**Comment by TheSharpieOne** [comment] 2017-09-13 16:38
I'm all for teaming up, but I have used react-bootstrap in the past and picked reactstrap not because it was using bootstrap 4, but for other reasons. I don't want to go on a [rant about it](https://github.com/reactstrap/reactstrap/pull/93#r73805279) but I feel that react-bootstrap is a little bloated; the min dist is 4x larger than reactstrap's. I believe this may be because the two projects are fundamentally different even if they attempt to achieve the same goal.

**Comment by jquense** [comment] 2017-09-13 16:42
@TheSharpieOne that may be true ultimately, but I think we are more than open to talking about it. v4 is a great chance for us to revisit all code that's built up over the years. We'd love to make RB much leaner generally. I think we just need to discuss whats important goal-wise and figure out what both projects value in terms of features, defaults, audience, etc.

**Comment by sustained** [comment] 2017-09-13 18:31
Is there a Gitter/Discord/Hipchat/Slack/IRC/whatever?

I'd like to hang around while such discussions go on, if I'm planning to contribute. If these two projects are thinking about merging then that would mean that the codebase will be changing a lot - which means that studying it right now is not the greatest idea. I'd be better off lurking in the chat while people discuss how things are and how things could/should be, for the time being.

**Comment by jquense** [comment] 2017-09-13 18:34
no specific chat other than our discord, which i sere you've already posted in :) It's not always the most active, generally most conversation happens via PR's and overflows there if needed

**Comment by sustained** [comment] 2017-09-13 18:36
Hmm, no dedicated development channel? Okay. :frowning: 

I'll hang out there, then!

**Comment by taion** [comment] 2017-09-13 18:42
It hasn't really come up.

**Comment by RKushnir** [comment] 2018-01-22 15:42
[It's here!](https://blog.getbootstrap.com/2018/01/18/bootstrap-4/)

**Comment by jquense** [comment] 2018-01-22 15:43
if anyone is interesting in contributing there is plenty of things to do on v4 support please feel free to jump in and help with #2752

**Comment by kevcodez** [comment] 2018-09-17 18:38
@jquense I looked at the v4 migration project, but I am very unsure about the state of each issue. What's left to do and is there anything left where no one is actively working on?

Do you have an ETA for a first release?

**Comment by jquense** [comment] 2018-09-17 18:57
the first release was last week! anything that isn't done probably needs to be worked on still in the project. I'll make sure it's up to date tho

**Comment by kevcodez** [comment] 2018-09-17 19:03
Oh shit, I didn't even realize, awesome. Thanks for the heads up!

**Closed** 2018-09-17 20:05 UTC
Labels: question, roadmap
