### ISSUE TITLE
Unrecognized activeKey prop on DOM elements

### ISSUE THREAD

**Issue by robertdown** [react-bootstrap/react-bootstrap#2895] opened 2017-11-27 23:10 UTC
Receiving this error in the console

```
Warning: React does not recognize the `activeKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activekey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in li (created by NavInstance)
    in ul (created by Nav)
    in Nav (created by NavInstance)
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by NavInstance)
    in NavInstance (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App
```

if this is really a bug in react-bootstrap I'll gladly work on it; just wanted to bring it up here first to confirm this is an issue and not just a side effect.

**Comment by taion** [comment] 2017-11-27 23:16
dupe of a bunch of other issues; don't nest DOM nodes directly under `<Nav>`. instead use nav items

**Closed by taion** 2017-11-27 23:16 UTC

**Comment by Domiii** [comment] 2017-12-08 10:19
`NavItem` must be anchor, however Bootstrap support all kinds of HTML elements by default, doesn't it? There must somehow be a way to add anything but `NavItem` and `NavDropdown` into the `Navbar`, no?

**Comment by Domiii** [comment] 2017-12-08 10:20
I suppose the easiest way is to wrap custom elements in something that just gobbles up `activeKey` and `activeHref`, [just like `NavItem` does](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavItem.js#L48)...

**Comment by QuantumInformation** [comment] 2019-03-13 11:22
Just ran into this today with this code:

```jsx
 <Nav pullRight={true}>
          <MenuItem href="foo" target="new" title="Raise Request">
            <Glyphicon glyph="comment"/>
          </MenuItem>
          <MenuItem href="foo" title="Support Email">
            <Glyphicon glyph="envelope"/>
          </MenuItem>
          <LinkContainer to="/help" title="Help">
            <NavItem><Glyphicon glyph="question-sign"/> Help</NavItem>
          </LinkContainer>
        </Nav>
```
 gives this error:

```
1.chunk.js:71388 Warning: React does not recognize the `activeKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activekey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by SafeAnchor)
    in SafeAnchor (created by MenuItem)
    in li (created by MenuItem)
    in MenuItem (at App.tsx:53)
    in ul (created by Nav)
    in Nav (at App.tsx:52)
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (at App.tsx:36)
    in div (at App.tsx:35)
    in Router (created by BrowserRouter)
```

**Comment by QuantumInformation** [comment] 2019-03-13 12:03
Ok menuItem is now `<NavDropdown.Item `

**Comment by QuantumInformation** [comment] 2019-03-13 12:13
Now, we just want to be able to use font-awesome icons in our `NavDropdown.Item`, has anyone got a best practice for this?

**Comment by QuantumInformation** [comment] 2019-03-28 12:56
How do we ignore this error? Would have prefered it to be a warning

 Warning: React does not recognize the `activeKey`
