### ISSUE TITLE
Show Prop For DropdownMenu doesn't work

### ISSUE THREAD

**Issue by rossm6** [react-bootstrap/react-bootstrap#5892] opened 2021-06-26 14:36 UTC
## Describe the bug

Passing 'false' as the value of the 'show' prop to the DropdownMenu component does not work.

E.g.

```
            <Dropdown>
                <Dropdown.Toggle variant="success" id="dropdown-basic">
                    Dropdown Button
                </Dropdown.Toggle>

                <Dropdown.Menu show={false}>
                    <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                    <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                    <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
                </Dropdown.Menu>
            </Dropdown>
```

## To Reproduce

Create the component as described above.  Click on the toggle and the menu still shows.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/angry-keldysh-e84j5).

## Expected behavior

I don't want the dropdown menu to show if show is set to false.

Context - I have created another dropdown component which isn't a react bootstrap component.  I need the RB dropdown to be closed when somebody opens mine.  How can I achieved this as it were outside the RB dropdown?

## Environment (please complete the following information)

Refer to the codebox for details.

NOTE I AM USING THE LATEST BETA VERSION OF REACT BOOTSTRAP 5.

**Comment by golota60** [comment] 2021-06-27 12:22
Hello!

I think you sent the wrong link to codesandbox cause it shows a toast component instead of what you described.

Anyways, I think you might be misunderstanding how `show` works. `show` describes if the modal is visible or not. If you pass `false` to it, it means that *initially* the menu won't be visible. But when you click on it(`Dropdown.Toggle`), `onToggle` is being fired, which changes this property to `true` and it's visible.

When menu is visible, clicking anywhere outside of it will close it, so the issue you described in Expected Behavior shouldn't happen.

When it comes to help on how to achieve the result you want, you might be more successful by posting your problem in reactiflux [Discord Channel](https://discord.gg/AKfs9vpvRW).

**Comment by kyletsang** [comment] 2021-06-27 19:32
You'll have to provide your own `onToggle` function to the `Dropdown` component since you're looking manage the show state of the dropdown.  In your case, by omitting `onToggle`, you're using the dropdown in an uncontrolled manner, so the show prop on the dropdown menu will be overridden.

Use something like:
```
<Dropdown onToggle={yourOnToggleFunc} show={yourShow}>
...
</Dropdown>
```

**Comment by rossm6** [comment] 2021-06-28 10:59
Hi guys,

Can't believe I submitted the wrong sandbox!

Ok, I will look into onToggle.

And thanks for pointing out the discord channel.  Cheers!

**Closed** 2021-08-11 05:32 UTC
