### ISSUE TITLE
I18n. Make the a11y messages customizable via props.

### ISSUE THREAD

**Issue by chrisbianca** [react-bootstrap/react-bootstrap#377] opened 2015-02-12 09:41 UTC
Has there been any thought about whether you'd look at including some basic internationalization into react-bootstrap?

At the moment I'm making use of format.js (http://formatjs.io/react/) which provides a mixin (IntlMixin) and a .getIntlMessage('key') method.  Currently I'm having to do lots of this in the code:

    <Input type="password" name="password" label={this.getIntlMessage("common.user.password")} placeholder={this.getIntlMessage("common.user.password")} />

It would be a nice extension if you could just pass a key through and react-bootstrap looked up the message if available?  It could revert to the string supplied if the message key didn't exist, or internationalisation wasn't available.

**Comment by mtscout6** [comment] 2015-02-12 14:13
I think you could write a thin wrapper around Input here to get what you need. I don't want to impose an i18n solution on everyone that uses this library. It wouldn't be too difficult, you can see an example of a thing library I wrote to do something similar with [react-router](https://github.com/rackt/react-router) in my [react-router-bootstrap](https://github.com/mtscout6/react-router-bootstrap). If you run into any trouble with it, feel free to ask questions here.

**Comment by chrisbianca** [comment] 2015-02-13 15:57
That's fair enough, I can understand why you don't want to impose an i18n solution on everybody. 
Thanks for the pointer/example.  I'll take a look and see what I can come up with.

**Comment by evgenyfadeev** [comment] 2015-06-20 06:31
The issue is that i18n will be needed not only in the Inputs, but throughout.

**Comment by mtscout6** [comment] 2015-06-20 14:15
@evgenyfadeev You would be correct, I wasn't as familiar with the library and all the internationalization needs back when I first read through this issue. Granted most of those situations that I'm aware of are related to screen reader only flags like https://github.com/react-bootstrap/react-bootstrap/blob/14494726df50a9a69690a22a230e3d5341de6117/src/Navbar.js#L128

Now what I'm talking about right now are react-bootstrap's usage of English text that could be internationalized. Most of which is not visible to a normal end user. So if we added i18n support I would see it getting added as a dev dependency so we could build the i18n files with our release. I envision this as being something like: (I don't know at the moment exactly what this would look like in the end result)

- [jQuery UI](https://github.com/jquery/jquery-ui/tree/master/ui/i18n)
- [MomentJs](http://momentjs.com/docs/#/i18n/)

As far as the original request to build i18n it into react-bootstrap I understand that to be building that support in so our users will have an i18n solution for their language needs. Which I still feel is better suited for another library. If you wanted to you could easily build components that wrap the components from this library with the added the internationalization concerns you need, with the internationalization library of your choice. An example wrapper for `Input` could be something like:

```
import CoreInput from 'react-bootstrap/lib/Input';

export default class Input extends React.Component {
  getIntlMessage(key) {
    // You're lookup....
  }

  render() {
    return <CoreInput {...this.props} label={getIntlMessage(this.props.label)} />
  }
}
```

If you decided to build out a library that integrated react-bootstrap with formatjs as I'm recommending then we'd be happy to link to it from our documentation.

I will re-open this and add to our 1.0.0 roadmap, but that will be for react-bootstrap's i18n concerns and not to serve as downstream user's i18n solutions.

**Comment by jquense** [comment] 2015-06-20 14:39
why not just make the a11y messages customizable via props vs trying to localize them ourselves. I took that approach in the new modal Header component

**Comment by jquense** [comment] 2015-06-20 14:41
Oops sorry that is exactly what you are suggesting. ignore me!

**Comment by evgenyfadeev** [comment] 2015-06-21 00:29
If good third party library/libraries can offer a solution then it would be enough. In that case links to documentation would be useful especially for the new users.

i18n should offer support for: 1) pluralization, 2) interpolation of strings with parameters.

**Comment by AlexKVal** [comment] 2015-06-27 18:17
Pull requests are welcome :wink:

**Comment by taion** [comment] 2016-01-11 22:56
What do we actually need to do for this? Isn't everything we have controllable via props?

**Comment by jquense** [comment] 2016-01-12 00:05
I don't think we have anything to do, we can/should expose every message, but I am pretty unexcited about also doing some sort of I18n thing specifically. Definitely vote leaving that to other libraries

**Comment by taion** [comment] 2016-01-12 00:09
Do we have any hard-coded non-internationalized strings?

**Comment by jquense** [comment] 2016-01-12 00:53
not that I know of

**Comment by taion** [comment] 2016-01-12 01:13
Can we close this, then?

**Comment by jquense** [comment] 2016-01-12 02:23
let it be so

**Closed** 2016-01-12 02:22 UTC
Labels: enhancement, help wanted

**Comment by Dattaya** [comment] 2016-08-07 12:30
> Do we have any hard-coded non-internationalized strings?

You have now, for example: 
 - https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavbarToggle.js#L49
 - https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Pagination.js#L127
