### ISSUE TITLE
Buttons in header of collapsible Panel don't respond to clicks

### ISSUE THREAD

**Issue by agmathew** [react-bootstrap/react-bootstrap#1361] opened 2015-09-28 20:06 UTC
I have a collapsible Panel with a PanelHeader and the PanelHeader has buttons. Here's an example:

    var panelHeader = (
      <Row>
        <Col xs={8}><h3>Test</h3></Col>
        <Col xs={4}>
          <ButtonToolbar className="pull-right">
            <Button href="abc.html">New</Button>
            <Button href="xyz.html">Create study block</Button>
          </ButtonToolbar>
        </Col>
      </Row>
    );
    <Panel collapsible={true} defaultExpanded={false} header={panelHeader}>
      ...
    </Panel>

If I click either of the two buttons, the panel will expand and collapse, but the buttons don't receive events. Is this the expected behavior? I'm using v0.25.2.

**Comment by jquense** [comment] 2015-09-29 12:01
They don't respond to clicks because they are wrapped in an `anchor` which is a whole bunch of invalid html. You will probably have to handle the collapsing/expanding manually use props. Also the Panel API is currently under discussion to account better for things like this

**Comment by chung-leong** [comment] 2015-10-10 04:43
Is there a way to disable the creation of the anchor tag? I want to handle the collapsing/expansion manually, but unless collapsible is set, the component doesn't response to the expanded prop. A separate headerToggle prop that controls whether the header get wrapped by an anchor would be  useful in a number of scenarios.

**Comment by chung-leong** [comment] 2015-10-10 10:37
Here's an ugly hack to get around the problem if anyone needs it:
```
Panel.prototype.__reactAutoBindMap._renderAnchor = Panel.prototype.renderAnchor;
Panel.prototype.__reactAutoBindMap.renderAnchor = function(header, headerRole) {
    if (this.props.disableHeaderAnchor) {
        return header;
    } else {
        return this._renderAnchor(header, headerRole);
    }
};
```

**Comment by taion** [comment] 2015-10-10 15:19
It has to be an anchor; what else would it be for a clickable collapsible header?

**Comment by chung-leong** [comment] 2015-10-10 16:01
The automatic insertion of the anchor makes it impossible to put buttons in the header (e.g. for moving items up and down). What I've noticed is that the browser would duplicate the anchor tag, which leads to invariant violations in React because suddenly it sees multiple A nodes with the same reactid.

________________________________

**Comment by taion** [comment] 2015-10-10 16:04
So don't make it collapsible. Your choice.

I'm closing this issue as effectively a dupe of https://github.com/react-bootstrap/react-bootstrap/issues/983, since any concerns here would most likely be covered by work there.

**Closed by taion** 2015-10-10 16:04 UTC

**Comment by donpark** [comment] 2016-01-07 19:13
Why not add  `Panel.DefaultHeader` and `Panel.CollapsibleLabel` components?
Use DefaultHeader, containing CollapsibleLabel, when `header` attribute is a string.
Custom headers can still add anchor with collapsible behavior using CollapsibleLabel.

**Comment by taion** [comment] 2016-01-07 19:14
Take a look at #983...

**Comment by anbhole** [comment] 2016-05-06 02:41
Wrapping header in anchor is not documented either and clearly not needed. There is an expanded prop and people can manage it with the state. Why is the need to put default unconfigurable behavior in the component.
