### ISSUE TITLE
[Docs] Show `import` statements for component examples

### ISSUE THREAD

**Issue by m2mathew** [react-bootstrap/react-bootstrap#2813] opened 2017-09-29 20:56 UTC
As a person jumps in to start using this library, it would be helpful to see the syntax for bringing the "react-boostrap" components into his/her project.

For instance, when I am wanting to use a **`<Panel>`** and **`<ListGroup>`** in my project, I would love to look up exactly how it should be brought into the file.

```JavaScript
import React, { Component } from 'react';
import {
  ListGroup,
  Panel,
} from 'react-bootstrap';
```

As a person who first used this project about a month ago, it threw me for a loop to not see the `import` statements. 🤓 

If this is amenable to our wonderful benefactors, then I would be happy to take up the torch and implement this in the project.

**Comment by taion** [comment] 2017-09-29 21:43
Sort of a dupe of https://github.com/react-bootstrap/react-bootstrap/issues/2573

Part of the problem is that we don't actually recommend importing things like that

**Comment by m2mathew** [comment] 2017-09-29 22:04
@taion I understand that not everyone is using webpack, but it definitely seems like the "Way of the Future". 😀 The project over at [Material-UI](http://www.material-ui.com/#/components/card) uses the `import` in examples.

What is the recommended method of importing components for react-bootstrap?

I see in the linked issue above that we can edit the examples directly in the browser. I have used these docs for about 3 months now...had no idea! Let's tell people!

**Comment by mxschmitt** [comment] 2019-08-03 22:35
Should be enough: https://react-bootstrap.netlify.com/getting-started/introduction/#importing

If not, feel free to file up a PR.

**Closed by mxschmitt** 2019-08-03 22:35 UTC
Labels: enhancement
