### ISSUE TITLE
Navbar dropdown link issue on Microsoft Edge

### ISSUE THREAD

**Issue by cperera-aud** [react-bootstrap/react-bootstrap#2065] opened 2016-07-19 01:24 UTC
Hi,

I've noticed an issue with Microsoft Edge for react-bootstrap navbar dropdowns. The issue is, if you click on a dropdown menu to view the menu then the page is directed to the homepage. This behavior is not present in Chrome or Firefox. I have attached two screenshots from a Microsoft Edge browser and Chrome browser which highlights this issue. 
![react-bootstrap-navbar-edge](https://cloud.githubusercontent.com/assets/16928715/16935422/a48e8f6a-4da2-11e6-99d4-7e0459f79198.png)
![react-bootstrap-navbar-chrome](https://cloud.githubusercontent.com/assets/16928715/16935423/a48efb44-4da2-11e6-8690-124d47aefe65.png)

The screenshot shows a navbar dropdown and I've hovered my mouse over it. On the bottom left corner of the screen the link that being pointed to is shown. 

The non-react bootstrap does not have this issue on Edge. 

So I was wondering is this something that I can fix on my end?

**Comment by MiguelCastillo** [comment] 2016-07-19 21:56
I am also running this issue. It is actually causing us lots of grief in the application I am working on. The problem is how IE is actually processing anchors with hrefs that are empty strings.  Quirky behavior I must say.

The issue can be resolved in react-bootstrap though, so that's very good news.  The flow is that NavDropdowns use `DropdownToggle`, which in turn uses `SafeAnchor` as the toggle component.  NavDropdown does not pass in an href to `SafeAnchor` which means that `SafeAnchor` will just add an href of empty string and that causes IE to misbehave.

1. Proposed solution is to change `SafeAnchor` to instead of am empty string, we use `javascript:void(0)` so that we make sure we address this issue at the root.

The change needs to happen right [here](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/SafeAnchor.js#L32)

2. Alternatively, we can just have `NavDropdown` pass in `javascript:void(0)` as the href for the DropdownToggle, which is less risky I guess...  But this issue might come up in the future again.

I can make a PR for either one.  I personally think that addressing this with `SafeAnchor` is the better choice...  But I will defer to other people with more knowledge.

**Comment by taion** [comment] 2016-07-20 01:27
I'm confused. Is `event.preventDefault` not doing anything here?

**Comment by MiguelCastillo** [comment] 2016-07-20 01:44
Where?

**Comment by jquense** [comment] 2016-07-20 01:44
[here](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/SafeAnchor.js#L56)

**Comment by MiguelCastillo** [comment] 2016-07-20 01:55
Thanks @jakebuhler.  @taion I had the same question...  I really can't explain what is happening there.  I will take a closer look there.  Best case scenario I missed something really simple.

**Comment by MiguelCastillo** [comment] 2016-07-20 01:57
Well autocomplete completely took there... I meant - Thanks @jquense.

**Comment by MiguelCastillo** [comment] 2016-07-21 02:44
I had time to look a bit further into the issue.  As I have described above, the issue stems from the way in which IE handles anchors with empty string hrefs.  When you give IE an anchor with an href that is an empty string, IE removes the document part of the window.location and makes that the anchor's href.

For example, if the current location is 'a/b/c/index.html' and there is an anchor with an empty href, IE will treat it as 'a/b/c/'.  This really ins't a problem when removing index.html... But SPA will generally just fail.

My issue is actually compounded by page.js.  page.js has an onclick handler at the document level, which gets called first when clicking on the toggle anchor.  page.js sees that the current URL is 'a/b/c/index.html' and the anchor that was clicked has href 'a/b/c/', which is technically a different.  page.js then proceeds to trigger a URL change to 'a/b/c/' causing my app to navigate away. page.js also calls `event.preventDefault()` but at that point it does not matter because page.js is already causing a URL change for the app.

Here is a screenshot of me IE showing the URL that correspond to an anchor with an empty href.  Notice that the left bottom show the URL without index.html and the address has index.html.  I am hovering over the `Dropdown` link.

<img width="490" alt="screen shot 2016-07-20 at 10 24 02 pm" src="https://cloud.githubusercontent.com/assets/1457701/17009666/015eb430-4ecb-11e6-8241-27b2403450e0.png">

I realize that we could bounce issues between projects, but I thought the place to start is here since react-bootstrap is the one creating the anchors with empty hrefs.

**Comment by jquense** [comment] 2016-07-21 02:52
my initial thought is that the problem is page.js,  or rather it's interaction with React. RB is doing the right thing here by preventing default on the click.  however,  page.js is either: not respecting the the prevented default which is a bug on its part, or firing before the React event system in which case this isn't really the best spot to address this. 

My initial thought is that you should load page. js after react is fully loaded to give React a chance to attach it's document listeners ahead of page.js apart from that tho the issue seems to an integration one, if I'm understanding you correctly here?

**Comment by taion** [comment] 2016-07-21 02:53
It wouldn't be the worst thing to use `"#"` as the trivial href rather than `""`, though, would it?

**Comment by MiguelCastillo** [comment] 2016-07-21 03:03
@jquense yeah that's a difficult recommendation.  The issue is exposed by page.js.  Not caused by page.js.  Page.js has no way of knowing that the anchor with no href generates a different url than the current location.  So it sees that the URLs are different and therefore trigger a page change. If I had to point my fingers at someone it would certainly be IE.  But that's a harder battle to take on :)

@taion that's a more reasonable suggestion.  However, we should consider that clicking on an anchor with a hash will add an entry in the history, which means that SPAs can be functionality affected.

In general, given that IE has this messy behavior, we should probably not use empty strings.  Understandable if ya'll think differently though.

**Comment by MiguelCastillo** [comment] 2016-07-21 03:13
@jquense correction. page.js does have the empty href as well.  But I think it would be messy to infer that if the href is an empty string, then parse out the anchor pathname to figure out whether or not it should really trigger a change. Seems error prone to me.

**Comment by MiguelCastillo** [comment] 2016-07-21 03:21
This SO has some helpful information about the issue.  http://stackoverflow.com/questions/7966791/empty-html-href-leads-to-directory-listing-in-ie

**Comment by taion** [comment] 2016-07-21 03:23
Fundamentally there's a limit here to what's reasonable on our side to get interop. I specifically use `"#"` as an example because that's what TWBS uses for trivial anchor hrefs. Doing something clunky like `"javascript:;"` would be too much, IMO.

**Comment by MiguelCastillo** [comment] 2016-07-21 03:35
I mean, I already add `javascript:;` wherever I can in other react-bootstrap components.  Why do you think that `javascript:;` is too much?  I would find it really odd behavior for opening a dropdown to insert a hash in the URL which can potentially have unwanted behavior.

We could also expose the href.  Currently, that's all wrapped up in the navdropdown.  If the href for the toggle is exposed as a prop, I would just create a wrapping component on my side that defaults the href to javascript:;

Ultimately, I am just want to resolve the issue.  I am making recommendations that I see would prevent users from having to think about it.

**Comment by MiguelCastillo** [comment] 2016-07-21 03:44
Actually `#` will work just fine.  Simply because event.preventDefault() will stop the browser from propagating the URL change.  That works!  :)

**Comment by jquense** [comment] 2016-07-21 18:25
>  The issue is exposed by page.js. 

I don't think that's right, if page.js (or anything) was going through the react event system then there would be no problem as we preventDefault on the event. The problem here is that page.js is grabbing the event and then _manually_ doing some navigation _before_ React can send those events to the the components.

> page.js does have the empty href as well. But I think it would be messy to infer that if the href is an empty string, then parse out the anchor pathname to figure out whether or not it should really trigger a change.

What do you mean by this? It seems like page.js should just see an empty href and not doing anything.

**Comment by taion** [comment] 2016-08-04 19:49
Let's keep further discussion on #2080. This is a Page.js interop thing, not a browser support thing per se.

**Closed by taion** 2016-08-04 19:49 UTC
