### ISSUE TITLE
Modal closing on mouseup

### ISSUE THREAD

**Issue by powermikee** [react-bootstrap/react-bootstrap#3373] opened 2018-11-15 06:19 UTC
When you select text dragging outside the modal, the modal will close.

This does not happen with react-overlays.

Seems that the modal treats mouseup as a click event.

**Comment by powermikee** [comment] 2018-12-20 05:59
This can be replicated on the example page:

https://react-bootstrap.github.io/components/modal/

Open any modal that doesn't have a static backdrop.

Drag select some text with the mouse pointer ending outside modal.

Modal will close.

**Comment by powermikee** [comment] 2018-12-20 06:03
You can view an example here:
https://youtu.be/ZlcfIMgwpFc

**Comment by patrickomeara** [comment] 2019-01-08 00:58
This is an issue in chrome and safari. Firefox is fine. 

I'm also having an issue where clicking an element within the modal that overflows is closing the modal

I have tried to stop propagation on click, mousedown and mouseup but the modal still closes.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/571773/50802959-acd33880-133c-11e9-9587-1c683ec87d08.png">

**Comment by teloo** [comment] 2019-01-13 05:40
I try to reproduce it.

# Steps

## bootstrap demo

1. I opened [the page](https://getbootstrap.com/docs/4.2/components/modal/#live-demo).
2. I clicked [Launch demo modal].
3. I selected text in the modal dragging outside the modal.

## react-bootstrap demo

1. I opened [the page](https://react-bootstrap.github.io/components/modal/#modals-live).
2. I clicked [Launch demo modal].
3. I selected text in the modal dragging outside the modal.

# Results

| Site | Edge | Firefox | Chrome |
------ | ---- | ------- | ------ |
| bootstrap demo | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| react-bootstrap demo | :x: | :heavy_check_mark: | :x: |

:heavy_check_mark: The modal didn't close.
:x: The modal closed.

# Versions

## Browsers

Edge: 42
Firefox: 64
Chrome: 71

## Sites

bootstrap: v4.2.1
react-bootstrap: v0.32.4

**Comment by teloo** [comment] 2019-01-13 18:10
I try to reproduce it.

# Steps

## bootstrap demo

1. I opened [the page](https://getbootstrap.com/docs/4.2/components/modal/#live-demo).
2. I clicked [Launch demo modal].
3. I selected text in the modal dragging outside the modal.

## react-bootstrap 3 demo

1. I opened [the page](https://react-bootstrap.github.io/components/modal/#modals-live).
2. I clicked [Launch demo modal].
3. I selected text in the modal dragging outside the modal.

## react-bootstrap 4 demo

1. I opened [the page](https://react-bootstrap.netlify.com/components/modal/#modals-live).
2. I clicked [Launch demo modal].
3. I selected text in the modal dragging outside the modal.

# Results

| Site | Edge | Firefox | Chrome |
------ | ---- | ------- | ------ |
| bootstrap demo | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| react-bootstrap 3 demo | :x: | :heavy_check_mark: | :x: |
| react-bootstrap 4 demo | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

:heavy_check_mark: The modal didn't close.
:x: The modal closed.

# Versions

## Browsers

Edge: 42
Firefox: 64
Chrome: 71

## Sites

bootstrap: v4.2.1
react-bootstrap 3: v0.32.4
react-bootstrap 4: v1.0.0-beta.3

**Comment by barrystaes** [comment] 2019-04-11 13:49
@teloo Great overview!
Though OS also matters: Firefox on Windows (10) does not close, but Firefox on Linux (Ubuntu16.04) does close.

**Comment by Batistleman** [comment] 2019-04-12 13:38
Anyone found a workaround/solution for this ?

**Comment by mxschmitt** [comment] 2019-04-14 10:46
In the new `react-bootstrap` version it was fixed by @jquense in PR #3187. But it's not applied to the old version yet.

**Comment by JasonKleban** [comment] 2019-05-22 14:44
@jquense - do you know - can this fix be applied to 0.32?

**Comment by jquense** [comment] 2019-07-09 12:40
We aren't likely to backport this fix since it's a bit tricky with the older styles. Happy to take a PR is someone wants to attempt it tho 👍

**Closed by jquense** 2019-07-09 12:40 UTC
Labels: Bootstrap 3
