### ISSUE TITLE
OverlayTrigger not working at React18

### ISSUE THREAD

**Issue by yuhs0** [react-bootstrap/react-bootstrap#6291] opened 2022-04-01 01:50 UTC
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

All values ​​of OverlayTriggerProps are recognized as required values.
So IDE ocurr error below.

```
Element OverlayTrigger doesn't have required attribute defaultShow 
Element OverlayTrigger doesn't have required attribute flip 
Element OverlayTrigger doesn't have required attribute onHide 
Element OverlayTrigger doesn't have required attribute onToggle 
Element OverlayTrigger doesn't have required attribute popperConfig 
Element OverlayTrigger doesn't have required attribute show 
Element OverlayTrigger doesn't have required attribute target
```

![image](https://user-images.githubusercontent.com/91457381/161177634-37bfd06a-262d-4cd2-98df-373bbaac5df1.png)
![image](https://user-images.githubusercontent.com/91457381/161177675-2e307ca5-07e6-4fb3-83f3-37fee8a4e729.png)

### Expected behavior

Only required value children and overlay.

### To Reproduce

1. Using React18
2. Create OverlayTrigger component with only prop children and overlay.
3. Test the behavior of OverlayTrigger.

### Reproducible Example

<OverlayTrigger
      trigger={['hover', 'focus']}
      placement="auto"
      delay={{ show: 150, hide: 150 }}
      overlay={
        <Popover id="popover-basic">
          <Popover.Header>Tooltip Header</Popover.Header>
          <Popover.Body>Tooltip Body</Popover.Body>
        </Popover>
      }>
      Tooltip Trigger
</OverlayTrigger>

### Screenshots

with React 17
![image](https://user-images.githubusercontent.com/91457381/161178896-4cc1b1ed-14fd-43ec-9a04-2009091c971a.png)

with React 18
![image](https://user-images.githubusercontent.com/91457381/161178718-52fcdf80-4bf6-44ff-aad0-d7a66fe68868.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.2.2

### What version of Bootstrap are you using?

5.1.3

### Additional context
My React 17 dependencies below
```
"dependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.16.7",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/pro-duotone-svg-icons": "^6.1.1",
    "@fortawesome/pro-light-svg-icons": "^6.1.1",
    "@fortawesome/pro-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@loadable/component": "^5.15.2",
    "@reduxjs/toolkit": "^1.8.0",
    "@sentry/react": "^6.19.2",
    "@sentry/tracing": "^6.19.2",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "@tiptap/core": "^2.0.0-beta.174",
    "@tiptap/extension-bubble-menu": "^2.0.0-beta.55",
    "@tiptap/extension-code-block-lowlight": "^2.0.0-beta.68",
    "@tiptap/extension-color": "^2.0.0-beta.9",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.25",
    "@tiptap/extension-font-family": "^2.0.0-beta.21",
    "@tiptap/extension-highlight": "^2.0.0-beta.33",
    "@tiptap/extension-image": "^2.0.0-beta.27",
    "@tiptap/extension-link": "^2.0.0-beta.36",
    "@tiptap/extension-table": "^2.0.0-beta.48",
    "@tiptap/extension-table-cell": "^2.0.0-beta.20",
    "@tiptap/extension-table-header": "^2.0.0-beta.22",
    "@tiptap/extension-table-row": "^2.0.0-beta.19",
    "@tiptap/extension-task-item": "^2.0.0-beta.31",
    "@tiptap/extension-task-list": "^2.0.0-beta.26",
    "@tiptap/extension-text-align": "^2.0.0-beta.29",
    "@tiptap/extension-text-style": "^2.0.0-beta.23",
    "@tiptap/extension-underline": "^2.0.0-beta.23",
    "@tiptap/react": "^2.0.0-beta.108",
    "@tiptap/starter-kit": "^2.0.0-beta.183",
    "@types/jest": "^27.4.1",
    "@types/lowlight": "^0.0.3",
    "@types/node": "^17.0.23",
    "@types/qs": "^6.9.7",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "@types/react-redux": "^7.1.23",
    "@types/react-table": "^7.7.10",
    "@wojtekmaj/react-daterange-picker": "^3.4.0",
    "adblock-detector": "^2.0.1",
    "add": "^2.0.6",
    "axios": "^0.26.1",
    "babel-loader": "^8.2.4",
    "bootstrap": "^5.1.3",
    "classnames": "^2.3.1",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.11.0",
    "echarts": "^5.3.1",
    "echarts-for-react": "^3.0.2",
    "history": "^5.3.0",
    "impression-tracker-react-hook": "^7.0.1",
    "lowlight": "^2.6.1",
    "qs": "^6.10.3",
    "react": "^17.0.2",
    "react-app-rewired": "^2.2.1",
    "react-bootstrap": "^2.2.2",
    "react-cookie": "^4.1.1",
    "react-dom": "^17.0.2",
    "react-gtm-module": "^2.0.11",
    "react-hook-form": "^7.28.1",
    "react-hook-inview": "^4.4.1",
    "react-image-crop": "10.0.0",
    "react-is": "^17.0.2",
    "react-number-format": "^4.9.1",
    "react-redux": "^7.2.6",
    "react-router": "^6.2.2",
    "react-router-dom": "^6.2.2",
    "react-scripts": "5.0.0",
    "react-svg": "^14.1.16",
    "react-table": "^7.7.0",
    "react-use": "^17.3.2",
    "react-viewer": "^3.2.2",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "sass": "^1.49.9",
    "styled-components": "^5.3.5",
    "styled-reset": "^4.3.4",
    "tslib": "^2.3.1",
    "typescript": "~4.6.3"
  },
```

And this is My React 18 dependencies
```
"dependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.16.7",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/pro-duotone-svg-icons": "^6.1.1",
    "@fortawesome/pro-light-svg-icons": "^6.1.1",
    "@fortawesome/pro-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@loadable/component": "^5.15.2",
    "@reduxjs/toolkit": "^1.8.1",
    "@sentry/react": "^6.19.3",
    "@sentry/tracing": "^6.19.3",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^14.0.3",
    "@tiptap/core": "^2.0.0-beta.174",
    "@tiptap/extension-bubble-menu": "^2.0.0-beta.55",
    "@tiptap/extension-code-block-lowlight": "^2.0.0-beta.68",
    "@tiptap/extension-color": "^2.0.0-beta.9",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.25",
    "@tiptap/extension-font-family": "^2.0.0-beta.21",
    "@tiptap/extension-highlight": "^2.0.0-beta.33",
    "@tiptap/extension-image": "^2.0.0-beta.27",
    "@tiptap/extension-link": "^2.0.0-beta.36",
    "@tiptap/extension-table": "^2.0.0-beta.48",
    "@tiptap/extension-table-cell": "^2.0.0-beta.20",
    "@tiptap/extension-table-header": "^2.0.0-beta.22",
    "@tiptap/extension-table-row": "^2.0.0-beta.19",
    "@tiptap/extension-task-item": "^2.0.0-beta.31",
    "@tiptap/extension-task-list": "^2.0.0-beta.26",
    "@tiptap/extension-text-align": "^2.0.0-beta.29",
    "@tiptap/extension-text-style": "^2.0.0-beta.23",
    "@tiptap/extension-underline": "^2.0.0-beta.23",
    "@tiptap/react": "^2.0.0-beta.108",
    "@tiptap/starter-kit": "^2.0.0-beta.183",
    "@types/jest": "^27.4.1",
    "@types/lowlight": "^0.0.3",
    "@types/node": "^17.0.23",
    "@types/qs": "^6.9.7",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "@types/react-redux": "^7.1.23",
    "@types/react-table": "^7.7.10",
    "@wojtekmaj/react-daterange-picker": "^3.4.0",
    "adblock-detector": "^2.0.1",
    "add": "^2.0.6",
    "axios": "^0.26.1",
    "babel-loader": "^8.2.4",
    "bootstrap": "^5.1.3",
    "classnames": "^2.3.1",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.11.0",
    "echarts": "^5.3.1",
    "echarts-for-react": "^3.0.2",
    "history": "^5.3.0",
    "impression-tracker-react-hook": "^7.0.1",
    "lowlight": "^2.6.1",
    "qs": "^6.10.3",
    "react": "^18.0.0",
    "react-app-rewired": "^2.2.1",
    "react-bootstrap": "^2.2.2",
    "react-cookie": "^4.1.1",
    "react-dom": "^18.0.0",
    "react-gtm-module": "^2.0.11",
    "react-hook-form": "^7.29.0",
    "react-hook-inview": "^4.4.1",
    "react-image-crop": "10.0.0",
    "react-is": "^18.0.0",
    "react-number-format": "^4.9.1",
    "react-redux": "8.0.0-beta.3",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.0",
    "react-svg": "^14.1.16",
    "react-table": "^7.7.0",
    "react-use": "^17.3.2",
    "react-viewer": "^3.2.2",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "sass": "^1.49.10",
    "styled-components": "^5.3.5",
    "styled-reset": "^4.3.4",
    "tslib": "^2.3.1",
    "typescript": "~4.6.3"
  },
```

_No response_

**Comment by kyletsang** [comment] 2022-04-01 16:33
Dupe of #6130 

This appears to be an ongoing problem with JetBrains IDEs.  Could you post a bug on their tracker?

**Closed** 2022-04-01 16:34 UTC
Labels: invalid

**Comment by kyletsang** [comment] 2022-04-04 16:17
> WebStorm warnings aside (I don't use WebStorm), OverlayTrigger doesn't seem to work in React 18. Can we reopen this issue @kyletsang? Or would you prefer a new one? Thanks.

It's better to create a new one because this one references a different issue.  Please create a new one and follow the issue template.  Thanks!

**Comment by snstanton** [comment] 2022-07-08 17:09
This doesn't seem like a JetBrains IDE issue.  The propTypes as declared doesn't indicate that the arguments are optional.  If they are supposed to be optional, the props should be declared with `?:`

**Comment by LouisRomeas** [comment] 2023-10-15 16:49
Upping this because it would need to be re-open.

**Comment by kyletsang** [comment] 2023-10-21 00:22
Try the latest release 2.9.1
