### ISSUE TITLE
Modal not closing when backdrop is tapped.

### ISSUE THREAD

**Issue by jorge-marques** [react-bootstrap/react-bootstrap#150] opened 2014-07-11 10:25 UTC
I'm using the ModalTrigger and Modal components in a project. On a desktop, when the backdrop is clicked, the modal closes, as it should. However, trying the same on an iOS 7 device does not seem to work. Nothing happens. It works fine on mobile IE though.
Has anyone experienced similar problems?

**Comment by mtscout6** [comment] 2015-03-31 01:36
I only have the Chrome dev tools emulation for iOS, is this still a problem?

**Comment by taion** [comment] 2015-05-19 17:41
Looks like this was resolved by #204.

**Closed by taion** 2015-05-19 17:41 UTC
Labels: 1 - Awaiting Response, bug, help wanted

**Comment by AlexKVal** [comment] 2015-05-19 20:28
Confirmed. It was resolved by #204 and that hack awaits removing when React-0.14 will be released.
https://github.com/react-bootstrap/react-bootstrap/issues/613

**Comment by SiyabongaNzulwana** [comment] 2017-05-24 13:46
I am experiencing this issue of a Modal not disappearing when tapped outside it only on iOS. anyone managed to solve it?
