### ISSUE TITLE
Hovering over Tooltip after upgrade crashes UI

### ISSUE THREAD

**Issue by F-Adam-B** [react-bootstrap/react-bootstrap#3587] opened 2019-04-02 22:14 UTC
After upgrading to the latest versions of React, Redux, Bootstrap 4, and React-Bootstrap, when I hover over my Tooltip component wrapped in a React-Boostrap Overlay component it throws the error `triggerBrowserReflow.js:5 Uncaught TypeError: Cannot read property 'offsetHeight' of null at triggerBrowserReflow (triggerBrowserReflow.js:5)`

Here's the component, 

```

function Tooltip({ icon, message, placement = 'top', trigger, ...props }) {
  return (
    <OverlayTrigger
      id='overlayComponent'
      overlay={<BSTooltip id="tooltip">{message}</BSTooltip>}
      placement={placement}
      trigger={trigger}
      {...props}
    >
      <div>
        {props.children}
        {icon && <span>&nbsp;<i className={icon} aria-hidden="true" tabIndex="0"></i></span>}
      </div>
    </OverlayTrigger>
  );
}

```

and the relevant package.json, 
``` "bootstrap": "^4.3.1",
    "bootstrap-css-only": "^4.3.1",
    "react": "^16.6.0",
    "react-bootstrap": "^1.0.0-beta.6",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "^16.8.6",
    "react-hot-loader": "^4.3.11",
    "react-redux": "^6.0.1",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "redux": "^4.0.1",
    "redux-form": "^8.0.1",

```

I did not have this issue prior to updating the aforementioned packages. Any help would be huge.

**Comment by bpas247** [comment] 2019-04-10 19:30
Do you have a link to a repo? Or a CodeSandbox perhaps?

**Comment by Floriferous** [comment] 2019-04-18 21:00
Having the same issue, unable to reproduce it so far.

Here's my stack trace:

```sh
'Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a
 class/function (for composite components) but got: object. You likely forgot to export your
 component from the file it\'s defined in, or you might have mixed up default and named 
imports.\n\nCheck the render method of `InnerPopper`.'
```

**Comment by jwd2a** [comment] 2019-05-03 02:16
Having a similar issue myself, but with the `Modal` component.

Component looks like this: 

```
import React, {Component} from 'react';                                                                                 
import {Modal} from 'react-bootstrap';                                                                                   
                                                                                                                        
class ModalComponent extends Component {                                                                                
  render() {                                                                                                                                                                            
    return(                                                                                                             
      <Modal show={this.props.show}>                                                                                    
        <Modal.Body>{this.props.children}</Modal.Body>                                                                  
      </Modal>                                                                                                          
    );                                                                                                                  
  }                                                                                                                     
}                                                                                                                       
                                                                                                                        
export default ModalComponent;  
```

Even when removing `{this.props.children}`, same issue. Any pointers toward what this is about would be awesome.

**Comment by kosmiq** [comment] 2020-03-11 10:53
Is anyone still having issues here? Please produce a test case on codepen or similar.

Will close this in 7 days if no new feedback appears.

**Comment by alberthdev** [comment] 2020-04-29 19:10
I have a similar issue where nesting a FormControl under an OverlayTrigger causes the site to crash. Short and sweet reproducible snippet here: https://codesandbox.io/s/react-bootstrap-broken-hover-example-yobib

**Comment by kosmiq** [comment] 2020-04-30 09:38
> I have a similar issue where nesting a FormControl under an OverlayTrigger causes the site to crash. Short and sweet reproducible snippet here: https://codesandbox.io/s/react-bootstrap-broken-hover-example-yobib

You are using the wrong prop, your code looks like this:
```
      <OverlayTrigger tooltip={<Tooltip>Hey, it's a tooltip!</Tooltip>}>
        <FormControl type="text" placeholder="Hover over me!" />
      </OverlayTrigger>
```

It should be:
```
      <OverlayTrigger overlay={<Tooltip>Hey, it's a tooltip!</Tooltip>}>
        <FormControl type="text" placeholder="Hover over me!" />
      </OverlayTrigger>
```

If you use the correct prop it works just fine: https://codesandbox.io/s/react-bootstrap-broken-hover-example-gpql3?file=/src/App.js

**Closed** 2020-04-30 09:38 UTC

**Comment by alberthdev** [comment] 2020-04-30 14:14
Ah, completely missed that - my bad. Thanks for your help!
