### ISSUE TITLE
ListGroupItem with onClick causes React warning to appear

### ISSUE THREAD

**Issue by hgezim** [react-bootstrap/react-bootstrap#1477] opened 2015-11-06 00:36 UTC
React displays this warning:

    Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>. See button > ... > button.

given a component like this:

```jsx
React.createClass({
  onClickOla: function ()
  {},

  render: function() {
    return( 
        <ListGroup className="list-group">
          <ListGroupItem onClick={this.onClickOla}>
            Trigger an alert
          </ListGroupItem>
        </ListGroup>
    );
  }
});
```

**Comment by taion** [comment] 2015-11-06 00:43
That's actually happening because you have a `<button>` somewhere else in your component hierarchy. Try e.g. dropping

```js
const listgroupInstance = (
  <ListGroup>
    <ListGroupItem onClick={() => {}}>
      Trigger an alert
    </ListGroupItem>
  </ListGroup>
);

ReactDOM.render(listgroupInstance, mountNode);
```

into the R-B playground - no error shows up until you add other `<button>` elements.

Otherwise this is a dupe of #1445 anyway.

**Closed by taion** 2015-11-06 00:43 UTC

**Comment by hgezim** [comment] 2015-11-06 03:54
This gives a warning just the same:

```jsx
<ListGroup>
    <ListGroupItem onClick={() => {}}>
      Trigger an alert
    </ListGroupItem>
</ListGroup>
```

Keep in mind that when ListGroupItem is rendered, `button` is rendered if there's an `onClick` handler.

**Comment by taion** [comment] 2015-11-06 03:58
Try it on our components page - it doesn't.

**Comment by hgezim** [comment] 2015-11-06 04:09
@taion, I apologize. You're absolutely right. I was looking at a component that was wrapped by another component. Essentially a `ListGroup` within a `ListGroup`.

**Comment by taion** [comment] 2015-11-06 04:16
No worries - anyway, keep an eye on #1445. We don't want to always force the use of a `<button>` there, but it's a good default for accessibility.
