### ISSUE TITLE
Show Popover cause Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by ifranseda** [react-bootstrap/react-bootstrap#792] opened 2015-06-05 11:50 UTC
Add this to render component in react-rails app:

      <ReactBootstrap.OverlayTrigger trigger="focus" placement="bottom"
        overlay={<ReactBootstrap.Popover title="Popover bottom">
          <strong>Holy guacamole!</strong> Check this info.
          </ReactBootstrap.Popover>}>
        <ReactBootstrap.Button bsStyle="default">Holy guacamole!</ReactBootstrap.Button>
      </ReactBootstrap.OverlayTrigger>

caused this:
Uncaught TypeError: Cannot read property 'firstChild' of undefined
	ReactMount.findComponentRoot
	ReactMount.findReactNodeByID
	getNodeFromInstance
	findDOMNode
	getPosition
	calcOverlayPosition
	updateOverlayPosition
	(anonymous function)

**Comment by mtscout6** [comment] 2015-06-05 14:23
I entered your example into one of the live editable code regions on our docs sight and it worked just fine.

I had to clean it up a little bit to work there, but those were merely cosmetic issues:

```
const overlay = (
  <OverlayTrigger trigger="focus" placement="bottom"
    overlay={<Popover title="Popover bottom">
      <strong>Holy guacamole!</strong> Check this info.
      </Popover>}>
    <Button bsStyle="default">Holy guacamole!</Button>
  </OverlayTrigger>
);

React.render(overlay, mountNode);
```

What versions of React and React-Bootstrap are you using?

**Comment by ifranseda** [comment] 2015-06-07 14:32
I'm using react-rails 1.0 with react-bootstrap version 0.23.1.
I'm not quite sure the version number of React.

it works fine if I use other component such as Button, Badge, ButtonContainer, etc. but not for Popover, OverlayTrigger.

**Comment by AlexKVal** [comment] 2015-06-27 16:04
We need a reproducible code for this error to work with to find out where is the problem lays.
Could you provide such ?

Or you can just close this issue if it is not relevant already. :sparkle:

**Closed** 2015-07-11 08:55 UTC
Labels: 1 - Awaiting Response

**Comment by lenart** [comment] 2015-07-21 09:18
I've just encountered this problem also. I'm new to react and also come from rails world like @ifranseda. It looks like the problem is in the way `react_rails` helper initializes component. I just copied your example for modal and called it from within the javascript file with

```javascript
let mountNode = document.getElementById("tmp");
React.render(<Example/>, mountNode);
```
This works. However `react-rails` uses [helper method](https://github.com/reactjs/react-rails#rendering--mounting) and some javascript [magic](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L31) to do the mounting. I think you should be able to figure out the cause of this problem and at least point us to the right direction. At the moment it's too much for me to figure out the solution.
