### ISSUE TITLE
React 16: Modal.Body input refs no longer usable from componentDidUpdate() in parent

### ISSUE THREAD

**Issue by lvpro** [react-bootstrap/react-bootstrap#2841] opened 2017-10-16 19:59 UTC
We render input controls within the modal body which sometimes need initialization such as a setSelectionRange() applied once shown.  Prior to React 16, we did this by acquiring a ref to the input control rendered within the modal body, then applied the setSelectionRange via the ref within componentDidUpdate() on the modal's containing component.  Worked fine.

Starting with React 16, we find componentDidUpdate() in the parent component executes before the ref functions on the input controls, thus the refs are undefined.  componentDidUpdate() doesn't run again, so we don't have an opportunity to do much else other than utilize a setTimeOut() to wait for the ref to be ready.

Is this expected behavior?  Psuedocode below:

```
class Container extends Component {
    inputRef = null;

    componentDidUpdate() {
         // this.inputRef is null here in v16
         // this.inputRef.setSelectionRange() works in v15, works in v16 only with setTimeout()
    }

    render() {
        <Modal show={true}>
              <Modal.Body>
                   <input ref={(ref) => { this.inputRef = ref; }}>
              </Modal.Body>
        </Modal>
    }
}
```

**Comment by gigobyte** [comment] 2017-10-19 11:20
I can confirm this problem. To be more specific here is the stack trace:

1. `Modal.componentDidUpdate`
2. `Modal.onShow`
3. `Modal.focus`
4. `modalContent` is undefined because `this.modalNode` is undefined and `this.getDialogElement` cannot get `modalNode.lastChild`

**Comment by taion** [comment] 2017-10-19 22:40
I believe this is the same root cause as https://github.com/react-bootstrap/react-bootstrap/issues/2842. Can you try using a bound method rather than an inline function for assigning the ref?

**Comment by lvpro** [comment] 2017-10-20 14:03
@taion that did not work.  setTimeout() still required within componentDidUpdate() to get valid references.

Changed code to:

setInputRef = (ref) => { this.inputRef = ref; };  // property initializer on Container class
...
<Modal.Body>
   <input ref={this.setInputRef}>
</Modal.Body>

**Comment by taion** [comment] 2017-10-20 20:15
Can you log the order of what the `ref` gets called with, plus the order of invocation of the lifecycle methods?

Is this only when the modal initially mounts, or is it for even "normal" rerender updates to the modal?

**Comment by ninja-** [comment] 2017-10-21 19:08
I've got the same issue, is there a good solution?

**Comment by ninja-** [comment] 2017-10-23 00:02
looks like it's fixed properly on master, at least the part that @gigobyte taked about. (internal crash from react-bootstrap)
as for what @lvpro tries to do where you use "your own" refs, it looks like a proper fix - using a function with bind - as mentioned here https://github.com/facebook/react/issues/11258#issuecomment-337379350 

I think we can close this?

@lvpro could you clarify whether you are able to call .setSelectionRange inside componentDidUpdate/componentDidMount now or only with a setTimeout/inside setInputRef? thanks

**Comment by lvpro** [comment] 2017-10-23 17:31
@ninja my sincere apologies for my ignorance on this, but how can I use master via package.json in my project to test?  I tried `"react-bootstrap": "git+https://git@github.com/react-bootstrap/react-bootstrap.git" `as well as` "react-bootstrap": "github:react-bootstrap/react-bootstrap#master"`, but get a Webpack error of: `Module not found: Can't resolve 'react-bootstrap'` after deleting node_modules / yarn.lock and re-running yarn install.

**Comment by ninja-** [comment] 2017-10-23 17:36
@lvpro 
easiest way would be like

```
cd ..
git clone https://github.com/react-bootstrap/react-bootstrap.git; cd react-bootstrap
npm install
npm run build;

cd ..
cd yourproject
npm link ../react-bootstrap
```

before you run ``` npm install``` please use this patch as there are deps missing on master that will break babel compile

```patch
From 1c24cdfb7737d4b5867c0123e9360decd9f54c4d Mon Sep 17 00:00:00 2001
From: ninja
Date: Sat, 21 Oct 2017 21:30:57 +0200
Subject: [PATCH] Add missing dev deps to compile properly

---
 package.json | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/package.json b/package.json
index 25011f8..f25e241 100644
--- a/package.json
+++ b/package.json
@@ -42,6 +42,10 @@
     "react-dom": "^0.14.9 || >=15.3.0"
   },
   "devDependencies": {
+    "babel-plugin-transform-es3-member-expression-literals": "^6.22.0",
+    "babel-plugin-transform-es3-property-literals": "^6.22.0",
+    "babel-preset-es2015": "^6.24.1",
+    "babel-preset-stage-1": "^6.24.1",
     "babel-cli": "^6.11.4",
     "babel-core": "^6.13.2",
     "babel-eslint": "^8.0.1",
--
libgit2 0.26.0
```

**Comment by lvpro** [comment] 2017-10-23 18:41
Okay, I followed your instructions.  I then used bound functions to set the ref:

```
constructor(props) {
   super(props);
   this.setInputRef = this.setInputRef.bind(this);
}
...
setInputRef(ref) { this.inputRef = ref; }
...
<input ref={this.setInputRef}>
```

componentDidUpdate sadly still bombs with an undefined reference to this.setInputRef unless I use a timeout.

**Comment by ninja-** [comment] 2017-10-23 18:42
@lvpro try with {this.setInputRef.bind(this)} ?

**Comment by ninja-** [comment] 2017-10-23 18:42
sorry didn't notice you used the bind already

**Comment by ninja-** [comment] 2017-10-23 18:45
you can try

```
setInputRef(ref) {
this.inputRef = ref;
if (ref != null) {
ref.setSelectionRange()
}
```

I would assume this api change is to prepare you for async rendering in react which means that refs will become ready at random time

**Comment by lvpro** [comment] 2017-10-23 18:48
I think the problem is that, although setInputRef may be called multiple times per Dan's explanation, componentDidUpdate is only called once, and during that single call, the ref is still null.  For various reasons, I need to do more logic within componentDidUpdate which utilizes the refs.

**Comment by ninja-** [comment] 2017-10-23 19:35
> Perhaps the pattern of safely using a ref within componentDidUpdate is simply no longer a thing in React 16+. That's unfortunate. :(

Yes, I've had similiar things in my codebase i.e. this.refs.textbox.focus(), I commented it out until there is more info on the official way to do this on react 16+. As I said you might be able to move all of your ref logic(like focus() on componentDidUpdate) to setInputRef. The refs won't be null inside i.e. button click handlers by the way so that part of the logic can stay intact.

**Comment by gaearon** [comment] 2017-10-23 19:48
If you have issues with React 16 please file them in React repo. We do support using refs in componentDidUpdate. I don't know where the information that it's unsupported is coming from, but now people will see this thread and quote it further spreading this.

It is hard to guess what went wrong and why without a minimal reproducing case. Please file it in React repo and we can discuss there.

**Comment by gaearon** [comment] 2017-10-23 19:52
In other words: if something wasn't mention in "breaking changes" in 16 blog post, then it being broken is probably a bug. Please report such bugs to us, don't just try to work around them or assume it's meant to be broken.

**Comment by lvpro** [comment] 2017-10-23 20:08
At this point, I'm not sure if the issue is within react-bootstrap itself, or an issue with React 16.  I personally use refs in the above manner all over the place and they work fine. This erroneous case seems specific to react-bootstrap's modal implementation, thus I filed the issue here.  Whether or not this is indeed a React specific issue is outside of my purview, so I'll leave moving this discussion over to the React team to the discretion of the maintainers of react-bootstrap.  Thanks Dan!

**Comment by taion** [comment] 2017-10-23 20:12
We just moved offices and have a few major deadlines coming up, so we're a bit limited on time right now.

Per https://github.com/react-bootstrap/react-bootstrap/issues/2841#issuecomment-338311644, can you log what you're seeing for the ref, including with or without an instance-bound method rather than an inline function?

**Comment by dlangerm** [comment] 2017-10-24 03:37
I can confirm that I also started getting this bug as soon as I moved from React 15.6.2 to 16. Anywhere that I used a modal began to throw this error.

**Comment by geminiyellow** [comment] 2017-10-24 06:41
same error, please fix it.

**Comment by taion** [comment] 2017-10-24 17:44
We just pushed through v0.31.4 with some fixes. Please take a look; if it's still broken, please log out the order of the ref values and the lifecycle callbacks.

**Comment by lvpro** [comment] 2017-10-24 18:34
@taion, v0.31.4 bombs webpack, had to revert back to v.0.31.3

```
:3000/static/js/bundle.js:235582 Uncaught ReferenceError: exports is not defined
    at Object.<anonymous> (:3000/static/js/bundle.js:235582)
    at Object../node_modules/react-bootstrap/es/utils/createChainedFunction.js (:3000/static/js/bundle.js:235583)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object.<anonymous> (:3000/static/js/bundle.js:231712)
    at Object../node_modules/react-bootstrap/es/PanelGroup.js (:3000/static/js/bundle.js:231827)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object.<anonymous> (:3000/static/js/bundle.js:222285)
    at Object../node_modules/react-bootstrap/es/Accordion.js (:3000/static/js/bundle.js:222316)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object../node_modules/react-bootstrap/es/index.js (:3000/static/js/bundle.js:234559)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object../app/client/src/components/App.js (:3000/static/js/bundle.js:2013)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object../app/client/src/routes.js (:3000/static/js/bundle.js:64533)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object../app/client/src/index.js (:3000/static/js/bundle.js:63686)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at fn (:3000/static/js/bundle.js:112)
    at Object.0 (:3000/static/js/bundle.js:300997)
    at __webpack_require__ (:3000/static/js/bundle.js:699)
    at ./app/client/src/actions/AppActions.js.__webpack_exports__.n (:3000/static/js/bundle.js:797)
    at :3000/static/js/bundle.js:800
```

**Comment by taion** [comment] 2017-10-25 00:06
fixed the v0.31.4 issue

**Comment by sadovnychyi** [comment] 2017-10-25 10:28
Didn't use any refs, but modals were broken. The latest release (0.31.4) fixed the issue.

**Comment by lvpro** [comment] 2017-10-25 13:00
@taion, upgraded to v0.31.5 and added logging as you requested and used bound functions for setting the refs.

componentDidUpdate() fires 1 time when the modal shows.  At this time, the refs are undefined.  The ref setting functions then run AFTER that (on the initial modal show).  componentDidUpdate() is not called again after the refs are set on the initial modal show, thus simply checking for undefined refs in componentDidUpdate is not a solution as it is only called once.   So the order is: render->componentDidUpdate->ref setting methods.

Subsequent updates on the shown modal work when componentDidUpdate() is called since the refs exist, but I note the ref setting functions are never called again - only on the initial modal show.

**Comment by taion** [comment] 2017-11-08 20:35
Moving this to https://github.com/react-bootstrap/react-overlays/issues/224.

**Closed by taion** 2017-11-08 20:35 UTC

**Comment by dperetti** [comment] 2018-04-02 19:22
The issue is still there in 0.32.1.
