### ISSUE TITLE
onChange event not fired for checkboxes

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#648] opened 2015-05-12 00:06 UTC
Just found that out with your latest version on npm.

For now I ll add a hack with an onClick event handler ...

**Comment by jportela** [comment] 2015-05-17 18:16
AFAIK, I don't think react-bootstrap does anything on the onChange property, this is done by React ( https://facebook.github.io/react/docs/forms.html ).

Does this happen to you on < IE9, or does it happen on other browsers as well?

**Comment by mtscout6** [comment] 2015-05-17 19:13
I put this into one the live editable show code tab on the [components page](http://react-bootstrap.github.io/components.html#input) and the alert shows when I change the checkbox. Can you provide more details? 

```
const inputTypeInstance = (
  <form>
    <Input type='checkbox' label='Checkbox' onChange={() => alert('changed checkbox')} />
  </form>
);

React.render(inputTypeInstance, mountNode);
```

**Comment by dozoisch** [comment] 2015-05-18 17:30
Will close this for now as there are now answers. Feel free to reopen. 

I do think though that the 2 current comments answer the problem.

**Closed by dozoisch** 2015-05-18 17:30 UTC
Labels: 1 - Awaiting Response

**Comment by jkmcrg** [comment] 2017-07-20 23:21
To this day - this fix still works - but the cause is unknown .... can anyone shed some light?

**Comment by jquense** [comment] 2017-07-20 23:40
We use checkboxes and radios with onChange all the time it works fine :)

**Comment by jkmcrg** [comment] 2017-07-20 23:55
@jquense I have one component where it does work fine - and another where it doesn't... I will look into the differences between the two and report back!

**Comment by jkmcrg** [comment] 2017-07-31 04:25
@jquense Figured it out!!! We weren't calling event.preventDefault() on one of the handlers 🤦‍♂️

**Comment by mayacode** [comment] 2018-01-29 13:31
Hi any update?

      checkboxFormatter(cell, row) {
        return (<Checkbox
          name="weekDisplay"
          value={row.week}
          defaultChecked
          onChange={this.handleChange}
          style={{ marginLeft: '20px' }}
        />);
      }

      handleChange(event) {
        console.log('event.target.name', event.target.name);
        console.log('event.target.value', event.target.value);
        console.log('event.target.checked', event.target.checked);
      }

Unfortunately, event is not fired. Also when I check in React tools in Chrome, I see all props except onChange. I would really appreciate any help

**Comment by avispeng** [comment] 2020-01-08 18:40
Sorry to comment on such an old post, but I hope my finding would help others. I have three stacked checkboxes that wouldn't fire onChange event. But they start to work properly after I assigned an id to each of them.

**Comment by texonidas** [comment] 2020-01-15 01:28
@avispeng this fix also worked for me, absolute lifesaver.

**Comment by paulsmithkc** [comment] 2020-02-01 17:40
Same for me, when id is not set, onChange is not called.

**Comment by ghostwriternr** [comment] 2020-06-21 13:52
@avispeng I have been breaking my head for the last 4 hours and this was it. Works after adding `id`. Can't thank you enough!

**Comment by mbret** [comment] 2020-08-07 01:34
Same, setting an id is the way to go. This issue should be opened again and the doc updated with this information

**Comment by bryandandan** [comment] 2021-03-01 13:44
The id has to be unique
