### ISSUE TITLE
Ability to not remove markup from DOM?

### ISSUE THREAD

**Issue by pertrai1** [react-bootstrap/react-bootstrap#2918] opened 2017-12-29 17:43 UTC
Is there a way that if a modal is closed it does not remove the markup from the DOM and rather just hides it? We are using a library that will only load once so when we close the modal and then open again, the library will not load. So I want to have the markup still in the DOM and just display none or block depending on if I open or close the modal. Any ideas on how to do this?

**Comment by dozoisch** [comment] 2017-12-29 18:00
@pertrai1 the best way in my opinion would be to use react lifecycle functions like (componentDidMount) to call the function that needs to run on that library. componentDidMount also lets you access references so it makes it easy to pass the dom node to the library too. 

It seems brittle to rely on the fact that dom is not unmounted.

**Comment by pertrai1** [comment] 2017-12-29 18:13
@dozoisch thank you for the quick reply. What is happening is that the library has one method exposed that calls a private function to only load the library once. So when the modal is closed, the library removes from the DOM and will not open again. If you don't mind having a look that would be very helpful as I am still in progress of getting up to speed with React. If you don't have time, I appreciate you sharing your feedback that you have already given. Here is some information:

**Line of Code:**  https://github.com/votinginfoproject/vip-embeddable-tool/blob/master/src/javascript/app.js#L60

---

**Example:**
* https://wevote.us/ballot 
* Click on Polling Location in submenu
* Close the modal and then open again to see the embed not opening

---

**Files from Our Repository**
* Modal: https://github.com/wevote/WebApp/blob/develop/src/js/routes/Ballot/PollingPlaceLocatorModal.jsx
* https://github.com/wevote/WebApp/blob/develop/src/js/components/Ballot/PollingPlaceLocator.jsx

**Comment by taion** [comment] 2017-12-29 18:19
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/2655

**Closed by taion** 2017-12-29 18:19 UTC

**Comment by pertrai1** [comment] 2017-12-29 18:22
Thank you for the help @taion. I am guessing this is getting closed with very little help because it is not a react-bootstrap issue.

**Comment by taion** [comment] 2017-12-29 19:14
It's a missing feature in React Overlays. We'd welcome a PR to add it.

**Comment by pertrai1** [comment] 2017-12-29 19:15
@taion  - awesome. will work on that and put in a PR. thank you

**Comment by artygrand** [comment] 2022-07-19 10:05
I dont want to open new issue, so ask here.

Hello, @taion , @pertrai1 Any news about this topic? Keep children mounted as option is very helpful.
I made my personal manager, that can open modal from other modal, and pass data between them in both way, but now I should keep all modals opened for working callbacks.
