### ISSUE TITLE
GitLab CI build fails - due to missing modules

### ISSUE THREAD

**Issue by dj-neza** [react-bootstrap/react-bootstrap#3714] opened 2019-04-28 19:43 UTC
When I try to build the code in my CI Pipeline on Gitlab I keep getting an error "./node_modules/react-bootstrap/es/index.js
Cannot find module: './Accordion'. Make sure this package is installed."
followed by the build fail. I honestly tried everything already to figure out what might be but I cannot seem to figure it out. Could you help me? (below is the screenshot of the problem)

<img width="744" alt="Screenshot 2019-04-28 at 21 39 13" src="https://user-images.githubusercontent.com/15552533/56869256-9b529100-69fe-11e9-9e11-165c69a34e63.png">

**Comment by mxschmitt** [comment] 2019-04-28 20:10
Please provide us your version of `react-bootstrap` which you are using.

**Comment by dj-neza** [comment] 2019-04-28 20:40
1.0.0-beta.6

**Comment by mxschmitt** [comment] 2019-04-28 20:55
I think it's a duplicate of #3712, please read through that, thanks.

**Comment by mxschmitt** [comment] 2019-05-08 06:42
Closed due no further response

**Closed by mxschmitt** 2019-05-08 06:42 UTC
