### ISSUE TITLE
[Modal] Uncaught TypeError: (0 , _scrollbarSize.default) is not a function

### ISSUE THREAD

**Issue by erycson** [react-bootstrap/react-bootstrap#5924] opened 2021-07-14 13:53 UTC
## Describe the bug

I can't use Modal

## To Reproduce

```jsx
  render() {
    return (
      <Modal show={true}>
        <Modal.Header closeButton>
          <Modal.Title>Modal title</Modal.Title>
        </Modal.Header>

        <Modal.Body>
          <p>Modal body text goes here.</p>
        </Modal.Body>
      </Modal>
    );
  }
```

## Screenshots
https://prnt.sc/1b2q5rd

## Environment (please complete the following information)

- Operating System: Windows 10 Pro 20H2
- Browser: Chrome 91.0.4472.124
- React-Bootstrap Version: 2.0.0-beta.2
- Snowpack Version: 3.0.1

**Comment by golota60** [comment] 2021-07-14 17:41
Possible duplicate of: https://github.com/react-bootstrap/react-bootstrap/issues/5834

**Comment by kyletsang** [comment] 2021-07-15 00:00
@erycson can you try on the latest version of snowpack?  If it still occurs, please file an issue in the snowpack repo

**Comment by erycson** [comment] 2021-07-15 12:02
> @erycson can you try on the latest version of snowpack? If it still occurs, please file an issue in the snowpack repo

I updated the snowpack to version 3.8.2, but the error continues

**Comment by kyletsang** [comment] 2021-07-15 16:16
Going to consolidate this issue with #5834 since it's the same cause.

**Closed** 2021-07-15 16:16 UTC
Labels: duplicate, upstream
