### ISSUE TITLE
navbar without navbar-nav class?

### ISSUE THREAD

**Issue by bryanlarsen** [react-bootstrap/react-bootstrap#305] opened 2014-12-10 17:14 UTC
I'd like to generate the following HTML:

```
<nav role="navigation" class="navbar navbar-default">
  <div class="container">
    <ul class="nav nav-justified">
```

This almost works, but it adds an extra `navbar-nav` class to the ul.

```
<Navbar>
  <Nav justified>
```

I tried adding `navbar={false}`, but that gets overridden by the cloneWithProps of the Navbar.

**Comment by mtscout6** [comment] 2015-02-27 18:56
Is this a duplicate of #422?

**Comment by taion** [comment] 2015-05-10 16:24
This is not a duplicate of #422. The issue is that https://github.com/react-bootstrap/react-bootstrap/blob/1181c55fad636e431e2a8c49d0868cc530619d72/src/Navbar.js#L87 will set the `navbar` prop on the `Nav` child to `true` even if it was explicitly set to `false`.

**Comment by AlexKVal** [comment] 2015-07-18 12:07
`Bootstrap` states that:
> Justified navbar nav links are currently not supported.

http://getbootstrap.com/components/#navbar
<img width="911" alt="screen shot 2015-07-18 at 2 35 53 pm" src="https://cloud.githubusercontent.com/assets/847572/8761437/64920e28-2d5a-11e5-9931-005780455463.png">

and
http://getbootstrap.com/components/#nav-justified
<img width="887" alt="screen shot 2015-07-18 at 2 40 03 pm" src="https://cloud.githubusercontent.com/assets/847572/8761459/fbff4e38-2d5a-11e5-836e-09a1bf554351.png">

--
If remove `navbar-nav` and add `nav-justified` as author proposes, it will be looking like that:
<img width="883" alt="screen shot 2015-07-18 at 3 01 07 pm" src="https://cloud.githubusercontent.com/assets/847572/8761523/1813bbce-2d5e-11e5-9c6c-6b05e07e7aee.png">

--
Hence this issue is not a bug. :sparkle: 
It is a more like a feature request. 

But the question is:
Because we seek parity with `Bootstrap` should we implement that unsupported by `BS3` feature ?

--
I'm closing it. 
If there are enough voices (from collaborators and users) to implement this feature, 
then we will reopen it as a feature request.
:cherries:

**Closed by AlexKVal** 2015-07-18 12:07 UTC
