### ISSUE TITLE
Reason for (overflow:hidden) change on Modal 

### ISSUE THREAD

**Issue by kRITZCREEK** [react-bootstrap/react-bootstrap#448] opened 2015-03-11 11:15 UTC
When updating react-bootstrap in my Application this change broke my UI.

[Modal.jsx, line-61](https://github.com/react-bootstrap/react-bootstrap/commit/13f395d2304727d65ee22242423150c22b73addb#diff-3f8ea8f4138955e64a0c26a6e9f8ac24R61)

What's the particular reason for this change (also the commit message doesn't reflect it)?

![modal-overflow](https://cloud.githubusercontent.com/assets/6189397/6595154/e204f2a4-c7e7-11e4-99cb-a4a34dac2291.png)

This was the behaviour before the change.

![modal-overflow-hidden](https://cloud.githubusercontent.com/assets/6189397/6595157/f49e4db6-c7e7-11e4-9ccc-ab5a008270fa.png)

Afterwards the Timepicker Component gets chopped. It's mainly a Question since i don't really mind using an older version.

**Comment by mtscout6** [comment] 2015-03-11 19:05
Looks like an oversight, that should be removed.

**Comment by stefanfisk** [comment] 2015-03-11 19:19
@mtscout6 that was a major oversight form my part. my PR set overflow: hidden for the whole modal. a solution would be to set it only if bsStyle is passed, and document accordingly. Will get a PR for it when I have the time, hopefully this weekend. if you don't feel like waiting you can revert my code in the meantime, likely not too many people have even noticed it.

**Comment by kRITZCREEK** [comment] 2015-03-18 15:59
@stefanfisk any updates on the matter?

**Comment by stefanfisk** [comment] 2015-03-26 07:03
I’m afraid not, as I’m currently tied up in a bunch of work.

But as I said, just reverting the commit would at least remove the regression it introduced.

**Comment by taion** [comment] 2015-05-19 17:48
This was resolved by #605.

**Closed by taion** 2015-05-19 17:48 UTC
Labels: 4 - Done, bug, help wanted
