### ISSUE TITLE
react-overlays dependency issue

### ISSUE THREAD

**Issue by nick** [react-bootstrap/react-bootstrap#3407] opened 2019-01-04 00:47 UTC
I'm using react-bootstrap 1.0.0-beta.3 in my app and today got the following error when using webpack:

app: ERROR in ../node_modules/react-bootstrap/lib/Modal.js
app: Module not found: Error: Can't resolve 'react-overlays/Modal' in 'PATH/node_modules/react-bootstrap/lib'
app:  @ ../node_modules/react-bootstrap/lib/Modal.js 26:36-67

It seems that react-bootstrap 1.0.0-beta.3 requires [react-overlays 1.0.0-beta.17](https://github.com/react-bootstrap/react-bootstrap/blob/aa00fe26c573e74b8da55114c026f7104393d7c6/package.json#L132) but when I check node_modules/react-bootstrap/node_modules/react-overlays/package.json I see that 1.1.0 is being installed, perhaps due to the `^` in the react-bootstrap package.json?

The solution was to `cd node_modules/react-bootstrap` then `npm install react-overlays@1.0.0-beta.17` manually. 

It seems the latest package.json refers to react-overlays 1.0.0... so perhaps pushing a new release would fix this issue?

**Comment by bpas247** [comment] 2019-07-25 08:31
Is this issue still relevant with the latest release (`v1.0.0-beta.10`)?

**Comment by bpas247** [comment] 2019-10-08 23:55
Closing this due to staleness (and since we're now on `v1.2.0` for React Overlays).

@nick please feel free to re-open this issue if you're able to reproduce it with the latest release of React Bootstrap 😃

**Closed by bpas247** 2019-10-08 23:55 UTC
