### ISSUE TITLE
include typescript definitions

### ISSUE THREAD

**Issue by christhomas** [react-bootstrap/react-bootstrap#1921] opened 2016-05-22 11:37 UTC
Hi guys,

I think it would be a good idea to include a typescript definition file which would let people out of the box using react bootstrap with typescript.

Even if it included the one available online now, it would be a great benefit over the latter, installing the typings yourself.

Then over time, if they are outdated, I could clone the repo, update them and offer a pull request with the fixes, right now I have to add a custom typings file and it's a bit cumbersome.

Everybody using typescript has to do this and right now it's not perfect, but adding it to the repo would at least give everybody an easy way to use typescript and report bugs that perhaps somebody like me could swoop in and fix, but whatever changes I make right now, are effectively private since I can't share them with anybody officially, other than creating my own fork of the repository.

What does everybody think?

**Comment by jquense** [comment] 2016-05-22 13:00
We've talked about this in the past, and my concern here is that b/c none of the maintainers use TS regularly the definitions would get out of date quickly and we wouldn't be able to update them, Generally thats ok, except that including them by default suggests that we are offering a level of support there that we are not.

Doesn't TS have a type def file registry? Would it make more sense to update and publish there vs here?

**Comment by christhomas** [comment] 2016-05-22 13:08
Hi there, yeah I understand you.

The problem is the typings available are also out of date, so what you need to do is install the typings that are offered through DT and then add a custom typing overlaying on top of it, which is kind of awkward.

So any and all typescript support, is by definition, always out of date, since the ones available are not really that great.

So this means contributing to those d.ts files is hard, because you can't just make a pull request on your repo, I have to go through DT and this is pretty much the blocker, meaning nobody updates the d.ts files, even if they could.

So in my case, I want to use typescript, I could clone your repo, update them give a pull request, then use the default ones when you merge them, but right now I don't have that easy path, which means I manually keep them to myself, meaning I cannot easily share my work.

So even if you had the d.ts file in your repo, you could offer it with a warning that it might be out of date and pull requests are welcome, other projects do this and whilst it's not perfect, it's certainly easily and better than the current system of kludgy overlaps...

So would it be possible to add the file _anyway_ and then add a warning that it might not cover everything and it might be out of date? This would at least make it easier for people to work with and perhaps contribute too, I personally think the current way of doing it, stops people from contributing because it's so convoluted...

**Comment by jquense** [comment] 2016-05-22 14:32
I don't terribly mind the warning with the included TS files, however, in practice that still results in some maintainance burden of triaging issues of ppl complaing they are out of date. Idueally I'd really like to handle this out of band via the TS sponsered solution...

I don't really understand DT but is the issue that the owner of them doesn't update them? Would it make more sense to try and grab ownership there? I'd be happy to point folks who use TS to the DT defs, and suggest they contribute there...if thats a thing that makes sense. The seperation also helps keep issues like "YO TS DEFS NOT WORK" off our issue tracker :P

**Comment by christhomas** [comment] 2016-05-22 14:40
the problem is that they are trying to get module owners to stop pushing defs into DT because it's obviously a band aid around the problem instead of taking care of the issue.

the warning would avoid most problems if it's a typescript issue, but I realise that maybe it won't stop everybody.

so if we can't put these directly into the repository, we're left with the worst possible solution because nothing will ever updated and everybody has to keep using their own private versions of react-bootstrap definitions. like I'm doing currently.

**Comment by mtscout6** [comment] 2016-05-22 15:24
@jquense I haven't seen any new Maintainers added to the Org in a while. How about creating a TypeScript team and recruit a few people to be a part of that team. You can make initial members of the team only have read access to the repo. When issues come in that are TypeScript related, just @ mention the TypeScript team and wash your hands of it. When you see that they have the technical chops you think are adequate then give them push access to the repo.

Regardless of how much you try this project has gained enough popularity that you can't keep TypeScript issues from coming into the issue board. We may as well capitalize on this and capture the talents of these developers to continue to enhance this project.

Also to be clear I'm not suggesting that this project should change to TypeScript, only that it can do a better job at including that portion of the community with open arms.

**Comment by jquense** [comment] 2016-05-22 16:10
that sounds fine to me, I just want to avoid a situation where folks can't get help with their TS issues because most of us don't know anything about it, or a situation where there is one person who handles this, then we need to be recruiting TS folks to keep that stuff up to date. IF that's the best solution then great, I do wnat to try and understand why handling this in DT isn't worthwhile, since that seems to be the TS blessed appraoch to providing type defs for libraries, and insofar as we don't need to handle this in a bespoke way i'd like not too, as its less fragile overall.

That being said, if thats not possible we should provide high quality TS support for folks if its not too hard. @christhomas if you'd like manage that as part of the RB org I'm 👍  on that. other @react-bootstrap/collaborators, thoughts?

**Comment by christhomas** [comment] 2016-05-22 20:09
I've created a test repository with react-bootstrap definitions, it's here: https://github.com/christhomas/react-bootstrap

I was just testing it before I attempted to submit a pull request, but it appears to work just fine and is the combination of the available react-bootstrap d.ts merged with the one that I updated in order to access missing functionality.

The problem is, it's like a chicken and the egg, right now, nobody maybe things to use typescript because it's support lacks, but once we have any support, no matter how basic, it can be worked on and improved and whilst I'm the first to bring this up to the stage of actually having a repo to pull from, who knows, maybe there are others who also have their own versions and can contribute, but before it was not possible.

the first step to solving this, is to at least have support there, in whatever form it has, then you can pull updates, but without that, we're left in limbo.  

I'm perfectly happy to take requests to enhance the TS support for RB whilst I'm able and capable and hopefully this pulls in more people to contribute.

**Comment by mtscout6** [comment] 2016-05-22 22:38
Does it make more sense to be in the same repo or another repo within the
organization?

**Comment by mathieumg** [comment] 2016-05-22 22:45
> another repo within the organization

To me, that would be the most fitting scenario. The versions could even be aligned with RBS' so you know that when you get react-bootstrap-typedefs @ 0.29.4, for example, they work with react-bootstrap @ 0.29.4. The upside is that it keeps these concerns separated and "TypeScript people" can handle the maintenance/issues in its own repo; the downside is that if signatures don't change between versions, publishing the same code with a different version could be cumbersome, or even confusing. Perhaps this "version syncing" thing is not even necessary if peer dependencies are leveraged properly, but definitely +1 at the separate repo idea.

**Comment by christhomas** [comment] 2016-05-23 07:26
The separate repo doesn't make that much sense to me, because it's a single small file and if you split it off, then you could have different branches for version 3 or 4 of bootstrap for example, then you could have a discrepancy between the version you install of both projects, because they are now disconnected from each other.

Putting the d.ts files into the mainline repository is the best idea, because the definitions you have, match the code in whatever branch you are working on, right now the master branch is bootstrap 3 and the definitions will line up with those and each new iteration, will have the correct definitions as time passes, but if a 4.x branch appears, then we can modify them accordingly to match version 4 and all the code remains in sync.

If we split it, then it's an unnecessary overhead with no benefits that I can see, apart from segregation of repository access.

I would push a little bit to include it in the main repository, until we reach any impasse that would mean the typescript people should move into their own repo cause of some unforeseen reason that may happen. 

what do you think?

**Comment by taion** [comment] 2016-05-23 12:55
The issue with having the same release cycle for TypeScript defs is that, given the size the API here, that we don't use TypeScript means we've have to cut new releases to update the TypeScript defs – and if we use a separate package, then that package would need to release on a different schedule.

To follow up on

>the problem is that they are trying to get module owners to stop pushing defs into DT because it's obviously a band aid around the problem instead of taking care of the issue.

It wouldn't be the owners pushing the typings there... it would be third-party in this case.

**Comment by jquense** [comment] 2016-05-23 13:05
I am most concerned about this situation: I push a PR that changes the API, now the TS defs need to be updated (which i can't do not using TS), what do we do? Hold a release until they have been updated? Release changes, and push another release when the type defs are updated? Are we ok with blocking releases for this? If not are we ok with some releases of RB not having matching type defs?

It may make sense to hold off on this until v1, where we are certain the API is going to move more slowly (not that it's particularly fast now)

**Comment by mtscout6** [comment] 2016-05-23 13:11
@christhomas I've been reading up on TypeScript this morning, and I'm leaning more and more to a separate repo for this. I don't want to see the project releases held up as @jquense has addressed. Likewise with the majority of the contributors not using it that would be detrimental. I agree that DefinitelyTyped has all the markings of a Band-Aid solution, but I blame TypeScript for that more as it's requiring a leaky abstraction to application dependencies based on the choice of language transpilers downstream.

It does look like DefinitelyTyped does support mechanics to represent definition files for numerous versions of a dependency, which seems ideal to address issues with updating mappings after a release has happened. Which will be the cause for this project on a recurring basis. I still stand by the idea of putting this in a separate repo within the organization which you and the team you recruit can maintain out of cycle with the core project's cadence.

**Comment by christhomas** [comment] 2016-05-23 13:15
Understood, thanks for your feedback on the issue.

**Comment by taion** [comment] 2016-05-23 13:15
To me it's not a matter of pushing out releases – it's having to cut point releases to release e.g. fixes purely to the TypeScript defs, which seems like it'd be a disservice to other users.

What's the benefit of putting the TSDs in the react-bootstrap org v in DefinitelyTyped? Is it just that we can recruit people to maintain them here? Sounds reasonable.

**Comment by mtscout6** [comment] 2016-05-23 13:38
@christhomas Have you looked at [typings](https://github.com/typings/typings)? It seems to me that their approach is more in line with allowing something outside the DefinitelyTyped repo, and a much better thought out product.

**Comment by christhomas** [comment] 2016-05-24 08:56
Hey, yeah I know typings, it's the new version of tsd and most of the same guys are on it, but it still has the same problems, the typings team are the ones saying that npm modules should carry their own typescript definitions and not use typings at all.  Thats where I got the idea to ask whether you'd like to carry the file in your repo or not.

But it's ok, I'm going to find a way to do this one way or another, thanks again for your feedback

**Comment by taion** [comment] 2016-05-24 13:22
What is the recommendation right now? Every package maintaining type definitions even when said packages do not use TypeScript is not viable.

**Comment by christhomas** [comment] 2016-05-24 13:25
It's my understanding that if people want to support typescript, they ship it alongside their code and eventually there will not be any need for tsd or typings at all since projects which care about typescript, will work out of the box and those which don't, if there is enough support for it, will gain those definitions as and when they need/want them.

**Comment by jquense** [comment] 2016-05-24 13:28
@christhomas we do want to try and figure out a solution here, do you have any thoughts on how to handle the concerns we have with keeping them in the same repo? From what I gather of your issues with the seperate repo is that its easy for them to get mismatched and hard to understand which version of RB they belong too? That makes sense but it seems likely to be the issue even if they are in the repo here, because folks PR code to the library won't/can't also update the ts defs. To me it seems like a worse situation to ship type defs that are wrong with a library

**Comment by christhomas** [comment] 2016-05-24 13:33
well, from my pov, the code and the defs are locked together, you can't really have different code than you have defs, cause if they don't match, it's a bug and should be fixed.

if they are in the same repo, the issue comes to the surface quicker cause tests could maybe get written and run against it, also, it centralises everybody around the same repository which has typescript or not

however, I understand that if nobody is going to step up, just me, I would get behind and things might not work out, so of course I understand your point that then the defs could naturally fall out of lock step and problems occur and people would complain.

separating the repositories seems like a way to make this easier because typescript people only have to deal with a separate typescript repository

I don't think there are any easy answers here, cause they all sound a bit like a sh*t sandwich no matter how you look at it.  For now though, I've created a repository (https://github.com/christhomas/react-bootstrap-typescript) for just the defs and I've published a npm module (react-bootstrap-typescript) and I'm working down this path instead until something better comes along.

**Comment by mtscout6** [comment] 2016-05-24 13:41
Let's take the agile approach and run with the separate Repo for a while. Then after some time evaluate how that's going. @christhomas I'm going to send you an invite to join the Org in a new Team "Typescript Gurus" (This can be renamed...) Feel free to transfer your repo to the Organization for better public visibility of it's existence. It may be worth adding docs to the Getting Started page explaining the setup and the reasoning behind it.

**Comment by mtscout6** [comment] 2016-05-24 13:46
@christhomas The team has been created and an invitation has been sent. Let me know if you run into permissions issues with the [Repo Transfer](https://help.github.com/articles/transferring-a-repository/).

**Comment by christhomas** [comment] 2016-05-24 13:56
I've never used this repo transfer before, it's asking what team access I want to choose, should I tick off all the boxes? or just certain ones? I have:
- Owners
- Collaborators
- Publishers
- Typescript Gurus (not sure I would count myself as a guru, just yet ;))

**Comment by christhomas** [comment] 2016-05-24 14:47
ok, so I've transferred the repo and i've also done a little bit of rearranging for the code and I've got what I expect to be working with the new repo against the typescript "extension repo" 

and my sample code works and everything appears to be working.

now here is where I get a deluge of issues regarding typescript support :) hopefully.....

thanks guys, I think this might be very interesting for me.

**Comment by taion** [comment] 2016-06-15 18:41
Closing this out for now.

Per https://github.com/Microsoft/TypeScript/issues/9184, looks like `@types/react-bootstrap` still points at the DT definitions, so... well, I don't know. But seems okay for now.

**Closed by taion** 2016-06-15 18:41 UTC
