### ISSUE TITLE
TabbedArea onSelect called suring an action dispatch

### ISSUE THREAD

**Issue by mikecargal** [react-bootstrap/react-bootstrap#472] opened 2015-04-02 19:13 UTC
I have an onSelect function assigned to a TabbedArea control.  Using Flux, I need to fire an action, but I get an invariant message about not being able to dispatch in the middle of a dispatch.  Should onSelect be called during a dispatch?  (I've checked the stack, and it's not one of my dispathes).  If that's normal behavior, how should I be able to fire an action as a result on someone selecting a tab?

**Comment by AlexKVal** [comment] 2015-06-27 18:20
I'm closing it because of age of question.
If issue is still relevant, please provide reproducible code snippet to work with. :sparkle:

**Closed by AlexKVal** 2015-06-27 18:20 UTC
