### ISSUE TITLE
React 16 Modal

### ISSUE THREAD

**Issue by jaynakus** [react-bootstrap/react-bootstrap#2803] opened 2017-09-22 13:17 UTC
There is an error when switching to react 16.0.0

```
Uncaught TypeError: Cannot read property 'contains' of undefined
    at eval (contains.js:17)
    at Modal.focus (Modal.js:557)
    at Modal.onShow (Modal.js:486)
    at Modal.componentDidUpdate (Modal.js:243)
    at commitLifeCycles (react-dom.development.js:11563)
    at commitAllLifeCycles (react-dom.development.js:12342)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1319)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1358)
    at invokeGuardedCallback (react-dom.development.js:1215)
    at commitAllWork (react-dom.development.js:12463)
```

**Comment by taion** [comment] 2017-09-22 14:17
dupe of a bunch of older issues; see earlier issues here and on react-overlays

**Closed by taion** 2017-09-22 14:17 UTC
