### ISSUE TITLE
CollapseOnSelect in Responsive Navbars prevents external links from working

### ISSUE THREAD

**Issue by Marjanus** [react-bootstrap/react-bootstrap#2365] opened 2016-12-01 11:41 UTC
Encountered locally and have recreated a problem in Navbar Mobile Friendly example code.

While collapseOnSelect is set in the Responsive Navbar, hrefs that should be redirecting to external websites are not working.  This behaviour applies both to Nav and  Nav pullRight.

**Comment by chrisbianca** [comment] 2016-12-01 13:40
Funnily enough, I've just come across the exact same problem.
I've worked around it in the short term with by getting rid of the NavItem for the external item and doing this instead:
```
<li role="presentation"><a href='{externalLink}'>Link</a></li>
```

**Comment by Marjanus** [comment] 2016-12-02 09:45
External links are working with this approach, but console gives this warning: 

> Warning: Unknown props `active`, `activeKey`, `activeHref` on <li> tag. Remove these props from the element.

**Comment by rmemoria** [comment] 2017-01-24 15:46
Same problem with me. In my case is not an external link but a hash to navigate inside the system (ex. #/mypage). If I replace by the li tag, it works but navbar doesn't collapse

`<li role="presentation"><a href='{hash}'>Link</a></li>`

If I use NavItem, the navbar collapse, but the link is not called.

**Comment by yhzgirl** [comment] 2017-03-08 09:49
Same problem for me on my Nav external links as well.

**Comment by dmison** [comment] 2017-03-30 07:06
I've just encountered this and it looks like the problem is in `NavItem.prototype.handleClick`

Disclaimer: today was my first foray into the code of this project so I could be missing something.

```javascript
NavItem.prototype.handleClick = function handleClick(e) {
  if (this.props.onSelect) {
    e.preventDefault();

   if (!this.props.disabled) {
      this.props.onSelect(this.props.eventKey, e);
    }
  }
};
```

`this.props.onSelect` points to `Navbar.prototype.handleCollapse` if `collapseOnSelect` is set on `Navbar`

```javascript
Navbar.prototype.handleCollapse = function handleCollapse() {
  var _props2 = this.props,
      onToggle = _props2.onToggle,
      expanded = _props2.expanded;


  if (expanded) {
    onToggle(false);
  }
};
```

So two scenarios:

1. `collapseOnSelect` is set: because `onSelect` is set in `NavItem` the browser navigation behaviour is overridden (via `e.preventDefault()`), `handleCollapse` is called, which calls `onToggle` to hide the menu.  So the menu is hidden and no navigation occurs.

2. `collapseOnSelect` is not set: `this.props.onSelect` is undefined in `NavItem` and therefore regular browser navigation behaviour occurs for the link clicked on and nothing else.  Navigation happens, menu stays visible.

I don't understand why `e.preventDefault()` is being invoked here.  The link is actually a `<SafeAnchor> `anyway so I think that if you wanted to avoid the browser navigation in favour of your own logic in an `onClick` or something on `NavItem` you can just set `NavItem's` `href` to `"#"` and it will ignore it.  

I think the simple fix is to remove the call to  `e.preventDefault()` in `NavItem.prototype.handleClick`.  It does seem unnecessary.

**Comment by dmison** [comment] 2017-03-30 07:12
My workaround was to copy `NavItem.js` (also `utils/createChainedFunction.js` and `SafeAnchor.js`) from `node_modules/react-bootstrap/lib/` to `src/NavItem/` directory in my own project and remove the `e.preventDefault` call as described above.

Then I include it with

`import NavItem from './NavItem/NavItem.js';`

instead of 

`import NavItem from 'react-bootstrap/lib/NavItem';`

Seems to be working ok thus far.

**Comment by dmison** [comment] 2017-03-30 07:26
Hmmmm, actually a better solution might be:

```javascript
handleClick(e) {
  if (this.props.disabled) {
    e.preventDefault();
  } else {
    if (!this.props.onSelect) {
      this.props.onSelect(this.props.eventKey, e);
    }      
  }
}
```
That way if disabled is set then nothing happens.

**Comment by emilyemorehouse** [comment] 2017-06-26 03:29
It appears that the current implementation of `collapseOnSelect` for the Navbar component is flawed as it overrides any `onSelect` passed to Nav or NavItem, causing a collision when using both `collapseOnSelect` and `onSelect`.

Current implementation aside, the most straightforward quick fix I can think of for the original issue is to add a check to `NavItem.prototype.handleClick` to check if the current onSelect prop is the bound handleCollapse function. This would allow the default behavior to continue when using `collapseOnSelect` and would properly stop propagation when using `onSelect`.

**Comment by emilyemorehouse** [comment] 2017-06-26 03:59
It appears that the current implementation of `collapseOnSelect` for the Navbar component is flawed as it creates a chained method with `onSelect` and `handleCollapse` when `collapseOnSelect` is defined, which causes `NavItem.prototype.handleClick` to stop propagation since `onSelect` is defined.

Current implementation aside, the most straightforward quick fix I can think of for the original issue is to add a check to `NavItem.prototype.handleClick` to see if the current onSelect prop is the bound handleCollapse function. This would allow the default behavior to continue when using `collapseOnSelect` and would properly stop propagation when using `onSelect`.

This does break a test though, I haven't had time to look into it yet.

**Comment by taion** [comment] 2017-06-26 04:40
If you'd care to submit a failing test case pending a full fix (which I think will require moving around a few things in this code), that would be helpful too.

**Comment by emilyemorehouse** [comment] 2017-06-26 04:45
Just re-opened my PR with the failing test case. The spy used to check `onToggle` is expected to fire, but does not.

**Comment by sevgibson** [comment] 2017-07-15 16:46
Submitted a [fix](https://github.com/react-bootstrap/react-bootstrap/issues/2711) for this issue along with tests.

**Comment by PsiXdev** [comment] 2017-09-01 17:57
Hello, is there any progress on this task? The problem is very urgent.

What prevents you from removing of using preventDefault when the user pass `onSelect` function? I think that the user will not pass the `href` and `onSelect` simultaneously. What is the point in this deventDefault?

**Comment by taion** [comment] 2017-09-01 17:57
If it's urgent to you, then send a PR that actually fixes it correctly. You can see the discussion on the current PR and where it stands.

**Comment by PsiXdev** [comment] 2017-09-01 18:11
Ok, I'll try to suggest a simple solution.
I just deleted `e.preventDefault ()` from `NavItem.prototype.handleClick`. Then I wrote the following code:
```
	<NavItem
		href="https://google.com"
		target="_blank"
		onSelect={this.onSelect}
	>
		Google
	</NavItem>
```
and
```
	onSelect(eventKey, e) {
		e.preventDefault();
		console.log('onSelect');
	}
```
When I clicked on the link app wrote to the console "onSelect", the link has been prevented.
I really think that in such cases, "preventDefault" should be called by programmers, not the library. In general, I do not fully understand what is the point of sending in `NavItem`` href` and `onSeeect` simultaneously.

Why do you think otherwise? I missed some other cases?

**Comment by taion** [comment] 2017-09-01 18:16
This is discussed at length in the linked PR. I recommend reading through it before commenting further.

**Comment by PsiXdev** [comment] 2017-09-01 18:21
I already read the discussion in the pr before, if you want, I will continue the discussion in it.

**Comment by zhanwenchen** [comment] 2017-10-22 17:50
For future reference, [here's the ongoing PR](https://github.com/react-bootstrap/react-bootstrap/pull/2711)

**Comment by taion** [comment] 2017-11-08 20:37
Fixed in `next` with https://github.com/react-bootstrap/react-bootstrap/pull/2790

**Closed by taion** 2017-11-08 20:37 UTC
