### ISSUE TITLE
Button `variant` typing too strict

### ISSUE THREAD

**Issue by akx** [react-bootstrap/react-bootstrap#3693] opened 2019-04-23 15:31 UTC
I think it might be sensible to also allow `string` for the variant over at https://github.com/react-bootstrap/react-bootstrap/blob/787a19ed22f5292e493d494816ae1cb9cc9b28d6/types/components/Button.d.ts#L8-L25 – the list of known variants is a good guide, but there are many cases where you have set up your own variants and using the escape hatch seems like overkill.

At the very least, the list of variant types should be exported as its own type.

**Comment by taion** [comment] 2019-04-23 18:44
Duplicate of https://github.com/react-bootstrap/react-bootstrap/issues/3574.

**Closed by taion** 2019-04-23 18:44 UTC

**Comment by akx** [comment] 2019-04-24 03:56
Sorry for the dupe!

I still think the variant list should be exported – I have a component that allows one to set `buttonVariant`; right now its type is `string`, which isn't directly assignable to `<Button>`'s `variant`. Would be nicer to just give it the correct `Variant` type, but since it's not exported, I'd need to copy-paste the above enumeration in.

**Comment by yinghaochan** [comment] 2019-07-22 17:48
@akx  did you find a good workaround?

Did you manage to get @taion 's suggestion of overriding interfaces to work?
> It's the default to work well with stock Bootstrap out of the box. The props are implemented as interfaces exactly so that you can override them as appropriate.
