### ISSUE TITLE
react bootstrap Model box doesn't work in react 16

### ISSUE THREAD

**Issue by mglrahul** [react-bootstrap/react-bootstrap#2827] opened 2017-10-10 11:30 UTC
hi there,

i am tried to integrate the react-bootstrap-modal popup box, but couldn't enable to integrate it, i have read the react-bootstrap repo closed issue. below is the link of my issue. 

https://stackoverflow.com/questions/46665490/react-bootstrap-model-box-doesnt-work-in-react-16

i have already checked this [issue](https://github.com/react-bootstrap/react-overlays/issues/188), but couldn't able to solve it.

thanks

**Comment by taion** [comment] 2017-10-10 15:13
dupe of a few existing issues

**Closed by taion** 2017-10-10 15:13 UTC

**Comment by mglrahul** [comment] 2017-10-10 15:51
hey taion, thanks for replying. I am in urgent need to fix this issue. 

how can we fix it. 

thanks in advance.
