### ISSUE TITLE
Modal animation does not work if modal is closed by clicking the modal footer buttons

### ISSUE THREAD

**Issue by anindya-dhruba** [react-bootstrap/react-bootstrap#5348] opened 2020-07-31 15:28 UTC
## Describe the bug
According to the official doc https://react-bootstrap.github.io/components/modal/#modals-live, react modal does not animate if the modal is closed by clicking the modal footer buttons.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to https://react-bootstrap.github.io/components/modal/#modals-live
2. Click the **Launch demo modal** primary button
3. Close the modal by clicking the **X** button of the modal.
4. The animation should work.
5. Open the modal again.
6. Close the modal by clicking the **Close** button of the modal.
7. The animation **should not** work. 

## Reproducible Example
The example can be found here:
https://react-bootstrap.github.io/components/modal/#modals-live

## Expected behaviour
Animation should work on closing modal event. Right now it works if the **X** button or anywhere outside the modal is clicked, but does not work if the buttons placed in modal footer are clicked.

## Environment
- Operating System: macOS Catalina 10.15.3
- Browser, Version 84.0.4147.105
- React-Bootstrap Version 1.3.0

**Comment by taion** [comment] 2020-07-31 15:38
Dupe of https://github.com/react-bootstrap/react-bootstrap/issues/5230

**Closed by taion** 2020-07-31 15:38 UTC

**Comment by anindya-dhruba** [comment] 2020-07-31 16:32
Oops, I couldn't find it before, thank you for pointing out.

In case it helps someone, I am disabling the `.btn` CSS transition for `.modal-footer` for now. I will enable the transition once the issue is resolved.
```
.modal-footer .btn {
  transition: none;
}
```
