### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-bootstrap#5174] opened 2020-05-12 21:01 UTC
Issue which keeps track of issues which are persistent / blocking before we can publish a version with Bootstrap 5 compatibility.

I can go ahead with creating the branch, bumping Bootstrap to v5 and connecting it with Netlify as soon as #5150 is merged. Then we have to go over the upstream changes etc.

Regarding Netlify and GitHub Pages, maybe use https://react-bootstrap-v5.netlify.app as soon its in alpha and once its stable move it over to the main name and v4 to https://react-bootstrap-v4.netlify.app.

cc @jquense @taion @bpas247

**Comment by jquense** [comment] 2020-05-12 21:07
sounds great. i'd like to be more on pace releasing for this version than with v4 :P

**Comment by kosmiq** [comment] 2020-05-13 05:30
I started goding through twbs5 a while back and wrote things down here: https://github.com/react-bootstrap/react-bootstrap/projects/2

Have we decided on using v4/v5? I remember there being some discussion about versioning and (possible) future breaking changes. Think it was @taion that brought it up.

**Comment by kyletsang** [comment] 2020-06-16 20:53
v5 alpha 1 just dropped:  https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/

**Comment by mxschmitt** [comment] 2020-06-16 20:55
> v5 alpha 1 just dropped:  https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/

I'm not totally sure how we should proceed with TypeScript. Definitely we should find a solution in the next couple of days to have a working version soon. What do you think?

**Comment by jquense** [comment] 2020-06-16 20:57
I'm happy to just merge in the typescript stuff now. I know very few people probably tried it but we did push a release with it for testing. I'd say lets do it and be ready to fix stuff quiickly

**Comment by kyletsang** [comment] 2020-06-16 20:58
> 
> 
> I'm happy to just merge in the typescript stuff now. I know very few people probably tried it but we did push a release with it for testing. I'd say lets do it and be ready to fix stuff quiickly

Can we do 1 more release of v4 prior to merging TS branch?  There are a number of features/fixes that should probably go out.

**Comment by jquense** [comment] 2020-06-16 21:01
to clarify i don't consider the TS release a breaking one, type only changes aren't semver breaking (by convention generally). This would just be a point release and we will continue to support v4 for a while, likely past v5's final release, like we are still supporting v3 for bug releases etc

**Comment by caub** [comment] 2020-07-01 17:24
There could be a sort of `import {Button} from 'react-bootrap/v5';` maybe, instead of separating bootstrap v4/v5 with versioning in react-boostrap

**Comment by jquense** [comment] 2020-07-10 00:52
Ok the TS stuff is merged in so no remaining large branches, does anyone want to own the v5 project? @kosmiq you've done a lot of work already to figure out the v5 changes here https://github.com/react-bootstrap/react-bootstrap/projects/2 do you want to continue to own that? Anyone else want to jump in as well?

**Comment by kyletsang** [comment] 2020-07-13 05:20
I can help out here.  Should have some time this week to start on v5 stuff.

**Comment by kosmiq** [comment] 2020-07-13 08:38
@jquense I can't promise the amount of time that I will have the next 2 months or so. But I will happily put in whatever time I can, whenever I can. If I try to limit myself to figuring out the differences regarding existing features and possibly new features, and keep myself away from the code I can probably get a bit more done.

@kyletsang et al are more than welcome of course to contribute with whatever they feel like :)

**Comment by kyletsang** [comment] 2020-07-16 03:03
@mxschmitt I should have some time tomorrow to start, so should I go ahead with the branch?  Name it `bs5-dev`?

**Comment by mxschmitt** [comment] 2020-07-16 03:19
> @mxschmitt I should have some time tomorrow to start, so should I go ahead with the branch?  Name it `bs5-dev`?

Yes feel free to do so. Thanks for your effort!

**Comment by kyletsang** [comment] 2020-07-29 21:44
@react-bootstrap/collaborators 

Looking at the v5 form file API... Bootstrap no longer has the native file picker and only supports the custom one.  Does it make sense to merge `FormFileLabel` and `FormFileInput` into `FormFile`, seeing as how there is only one way to write the form file html now?  This would also remove the ability for users to form their own markup, which I don't think will be needed anymore anyway.

Thanks!

**Comment by kyletsang** [comment] 2020-07-30 00:28
> 
> 
> @react-bootstrap/collaborators
> 
> Looking at the v5 form file API... Bootstrap no longer has the native file picker and only supports the custom one. Does it make sense to merge `FormFileLabel` and `FormFileInput` into `FormFile`, seeing as how there is only one way to write the form file html now? This would also remove the ability for users to form their own markup, which I don't think will be needed anymore anyway.
> 
> Thanks!

Actually ignore. I thought about it some more and there are some cases where I could see users overriding this.

**Comment by thakkaryash94** [comment] 2020-07-30 01:52
@kyletsang You are doing awesome, thank you so much. I am new to this, I want to participate in the process with you. I have forked the repo, switched to bs5-dev branch and I started working on [https://github.com/react-bootstrap/react-bootstrap/projects/2#card-42008293](https://github.com/react-bootstrap/react-bootstrap/projects/2#card-42008293) because I felt it is a good and easy task to start with. I have just pushed it to my branch, can you please confirm check and confirm so that I can send a PR.

Link: https://github.com/thakkaryash94/react-bootstrap/commit/467fe0263f80b89c3710bb5dc653a46696bef210

Bootstrap Link: https://v5.getbootstrap.com/docs/5.0/components/badge/#pill-badges

Thanks

**Comment by kyletsang** [comment] 2020-07-30 03:00
@thakkaryash94 Thanks for helping!  

You can go ahead and create the PR.  It'll be easier for us to leave feedback there.

**Comment by thakkaryash94** [comment] 2020-07-30 03:04
Sure. I have created a PR. Please check. https://github.com/react-bootstrap/react-bootstrap/pull/5345

**Comment by kosmiq** [comment] 2020-07-31 07:21
@kyletsang @jquense @bpas247 @taion 

Lets talk version numbering. I think we should go for v5 since it's based in bs v5 and try to keep in sync. This should make it easier for most users as well. 

Drawbacks are of course whenever a breaking change needs to be introduced and how we manage that if we are trying to follow upstream versions.

And how do we, in that case, manage minor updates etc? Both on our end and when upstream pushes minor updates that might affect us?

**Comment by jquense** [comment] 2020-07-31 13:27
I love the idea of keeping in sync in theory, we considered it for the current v1 as well. The problem is as you say how do we handle breaking changes on our end. There are outside forces in what bootstrap implements as well as what React does that limit our ability to control or avoid breaking changes. Those aside tho it's a bit limiting to be bound by the major version number of effectively another project. For minor/patch versions we really need the freedom to bump as needed so we can't keep those in sync. Question then is whether the version signpost is worth the extra limitations?

**Comment by cordosvictor** [comment] 2020-08-26 11:19
Hi guys, did you made any releases for this branch? Or can you tell me a way I can npm install it? I tried installing branch `bs5-dev`, but only got the source code for it so the import doesn't work.. and to make it work I had to manually run the build script under node_modules/react-bootstrap

**Comment by kyletsang** [comment] 2020-08-27 06:00
There's no release yet. You'll have to manually build it if you want to play around with it.

**Comment by cordosvictor** [comment] 2020-08-27 10:09
Thanks @kyletsang, resolved it by adding a postinstall script in my package.json file. I'll leave it here for whoever might want to install this branch.

`"postinstall": "cd ./node_modules/react-bootstrap && npm i && npm run build && rm -rf node_modules/"`

**Comment by laoshaw** [comment] 2020-10-02 03:48
can't wait to try bt5 without jquery on react

**Comment by kyletsang** [comment] 2020-10-02 18:13
@laoshaw Bootstrap contains javascript components as well like dropdowns and modals.  React-Bootstrap re-implements all that using the react paradigm.  RB also encapsulates the html, classes, some accessibility handling, etc into components so you don't really need to wire up the low level bootstrap stuff yourself.

**Comment by laoshaw** [comment] 2020-10-02 19:00
BT5 will not have jQuery, but still needs popper.js(which seems OK as it does not change DOM) and its own small native js library(for dropdowns etc probably), BT javascript libraries(jQuery or native) will modify DOM directly, which might conflict with React's VDOM approach, and RB can convert those JS code to work with VDOM like the rest of React code, is this one of the major reason for react-bootstrap (other than the encapsulation you mentioned above)?

Other js libraries also have their react-version, e.g. chartist has react-chartist, i18next has react-i18next, and so on, are these react-version-wrapper "good to have"(i.e. with the wrappers they're more consistent with react coding style to make code easy to understand), or are they "mandatory"(i.e. some of them will modify DOM directly which might cause real issues with React's VDOM approach). I am new to React and ask them along with RB because I saw many JS libraries including Bootstrap all have their react-version, and not sure what is the real reason. Converting other js/css projects to react-style seems a lot of work too.

**Comment by kyletsang** [comment] 2020-10-02 20:18
> 
> 
> BT5 will not have jQuery, but still needs popper.js(which seems OK as it does not change DOM) and its own small native js library(for dropdowns etc probably), BT javascript libraries(jQuery or native) will modify DOM directly, which might conflict with React's VDOM approach, and RB can convert those JS code to work with VDOM like the rest of React code, is this one of the major reason for react-bootstrap (other than the encapsulation you mentioned above)?
> 

Correct

> Other js libraries also have their react-version, e.g. chartist has react-chartist, i18next has react-i18next, and so on, are these react-version-wrapper "good to have"(i.e. with the wrappers they're more consistent with react coding style to make code easy to understand), or are they "mandatory"(i.e. some of them will modify DOM directly which might cause real issues with React's VDOM approach). I am new to React and ask them along with RB because I saw many JS libraries including Bootstrap all have their react-version, and not sure what is the real reason. Converting other js/css projects to react-style seems a lot of work too.

Same reasons as above - stick with the react variants of the libraries

**Comment by laoshaw** [comment] 2020-12-13 00:52
BT5-beta was out, hope react-bootstrap will support it sometime

**Comment by ridhwaans** [comment] 2021-02-02 21:36
Please add Position utilities from Bootstrap 5 https://blog.getbootstrap.com/2020/09/29/bootstrap-5-alpha-2/

**Comment by AndreiBehel** [comment] 2021-02-12 13:19
@jquense As bootstrap 5 beta 2 has been released, so i think it's good idea to pin this issue to avoid questions related to react-bs-5 dev progress

**Comment by bduff9** [comment] 2021-03-14 22:11
@jquense Any chance we can get this published as an alpha/beta version in npm?  Using the GitHub link as the version in package.json has caused me many headaches, but up to this point I was able to get it to work.  However, due to this issue, this no longer works for me since we are using Husky: https://github.com/typicode/husky/issues/851#issuecomment-777179899

I completely understand this is not ready for prod, but that's what people typically use the alpha or beta semver tags for.

**Comment by jquense** [comment] 2021-03-14 22:21
I believe there is an alpha published now

**Comment by kyletsang** [comment] 2021-03-15 05:25
v2.0.0-alpha.0 is available on npm

See release notes here:
https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.0

**Comment by cyonder** [comment] 2021-06-05 20:54
Is it possible to give ETA?

**Comment by kyletsang** [comment] 2021-06-06 05:43
> 
> 
> Is it possible to give ETA?

v2 beta is currently out and supports a majority of the Bootstrap 5 features.  You can install that via npm.

Going to close this issue - the remaining tasks can be tracked in https://github.com/react-bootstrap/react-bootstrap/projects/2.  Feel free to send and PRs for missing features and bug fixes.

**Closed by kyletsang** 2021-06-06 05:43 UTC
