### ISSUE TITLE
Someone messed up the documentation

### ISSUE THREAD

**Issue by sunshineo** [react-bootstrap/react-bootstrap#3676] opened 2019-04-18 06:52 UTC
https://react-bootstrap.github.io/getting-started/introduction/

All the code samples are messed up

![image](https://user-images.githubusercontent.com/1072766/56342222-41370d80-616c-11e9-9924-b94596fd8ddd.png)

**Comment by mxschmitt** [comment] 2019-04-18 07:12
Duplicate of #3540

**Closed by mxschmitt** 2019-04-18 07:12 UTC
