### ISSUE TITLE
input action popover is covered up

### ISSUE THREAD

**Issue by imjared** [react-bootstrap/react-bootstrap#1283] opened 2015-09-03 18:38 UTC
https://react-bootstrap.github.io/components.html#input-addons
![image](https://cloud.githubusercontent.com/assets/525011/9667283/eb252598-5248-11e5-9fab-52b50861d810.png)

Looks like if you bump the z-index from 2 to 3 on the rule `.input-group-btn:last-child>.btn, .input-group-btn:last-child>.btn-group` it will be resolved.

screencast: http://cl.ly/192j0B0R181F

**Comment by taion** [comment] 2015-09-11 05:33
The issue here is actually a bit more subtle than that. This breaks because we nest the menu inside of the `button` element; upstream TWBS doesn't do that, and actually puts the menu next to the `button`.

/cc @mtscout6 @jquense

**Comment by jquense** [comment] 2015-09-11 10:21
I can't think of a good way to fix this without changing the API to explicitly handle dropdowns like: `dropdownAfter` or something. The issue is that the `input-group-btn` div should be the dropdown parent and not have a nested `btn-group`...

**Comment by taion** [comment] 2015-09-11 14:04
Oops, miswrote above. @jquense has it right.

**Comment by taion** [comment] 2016-04-08 20:52
This is fixed with the revamped form control API. See https://github.com/react-bootstrap/react-bootstrap/pull/1797.

**Closed by taion** 2016-04-08 20:52 UTC
Labels: bug, help wanted
