### ISSUE TITLE
Question: is there any idea on using Bootstrap w ReactJS Native

### ISSUE THREAD

**Issue by mschipperheyn** [react-bootstrap/react-bootstrap#500] opened 2015-04-09 14:38 UTC
Bootstrap and ReactJS Native don't seem to mesh well because ReactJS Native assumes the use of straight stylesheets in stead of css classes. I've been wondering if there's any kind of conversion that can be done going from perhaps Less to javascript objects or any other way that doesn't require manually copying Bootstrap to javascript objects. Then there is the challenge of selectors you can't express in Javascript objects.

**Comment by mtscout6** [comment] 2015-04-09 15:09
I personally have not entered the React Native space yet, nor do I have a need to in the immediate future. There has been some discussion about inline styles in #362 but no clear path has been found that would work for everyone. If you'd like to champion the cause and present a path that we could follow that would get us there I'm all ears.

**Comment by mschipperheyn** [comment] 2015-04-09 15:11
Yeah, my problem is that I don't have any clear ideas on this. We seem to be in limbo a bit here. It doesn't seem to make sense to maintain Bootstrap separately as a javascript object unless there is some kind of conversion script. I vaguely thought in the direction of less, since that already does some javascript based parsing. Fb through us a curve ball here

**Comment by AlexKVal** [comment] 2015-05-04 11:49
I think we can close the issue.

**Closed by AlexKVal** 2015-05-04 11:49 UTC
Labels: question

**Comment by sanketsahusoft** [comment] 2016-01-19 03:50
Disclaimer: I own StrapMobile.com

My team developed a starter kit for React Native, we call it "The Bootstrap of React Native". Here is the link
http://strapmobile.com/native-starter-pro/

Though it's not open source, it may save some good amount of weeks with the app development. Don't mean to advertise, just adding so it may help someone.

**Comment by mschipperheyn** [comment] 2016-01-19 10:20
I recommend just using one of the Material Design kits and forget about Bootstrap. It took me a while to get over Bootstrap, but once you go with Material Design, you'll be the happier for it

**Comment by taion** [comment] 2016-01-19 16:01
If you are using uncustomized Bootstrap for a production site, you are doing it wrong.
