### ISSUE TITLE
Accordian auto close

### ISSUE THREAD

**Issue by vivek-gapps** [react-bootstrap/react-bootstrap#5333] opened 2020-07-27 12:30 UTC
I have used React bootstrap dropdown button components in my react project. 

I have one parent component in react which uses Accordion and I have given it static eventKey="0"

when I select a dropdown item from the child component then my parent component Accordion get closed automatically.

Please let me know the solution, how can I handle it ?

Thanks in Advance.

**Comment by kyletsang** [comment] 2020-07-27 17:35
Dupe of #4176

A workaround is to wrap your dropdown with `<SelectableContext.Provider value={null}>`. See #4176 comments for more info.

**Closed by kyletsang** 2020-07-27 17:35 UTC

**Comment by vivek-gapps** [comment] 2020-07-28 03:41
Awesome you save me to revamp a piece of code. :+1:
