### ISSUE TITLE
Minified version of react-bootstrap isn't minified

### ISSUE THREAD

**Issue by sanchitanand** [react-bootstrap/react-bootstrap#3133] opened 2018-04-27 06:14 UTC
Am I misinterpreting something here? I thought the minified version was supposed to be smaller than the uncompressed version, but they are both the same size.

**Comment by thatnini** [comment] 2018-04-27 06:43
Duplicate of [#3126](https://github.com/react-bootstrap/react-bootstrap/issues/3126)

**Closed** 2018-04-27 07:11 UTC
