### ISSUE TITLE
In StrictMode, Carousel does not scroll inifinitely, final transition goes backwards

### ISSUE THREAD

**Issue by roblframpton** [react-bootstrap/react-bootstrap#5365] opened 2020-08-05 17:14 UTC
## Describe the bug

When StrictMode is enabled, the Carousel will exhibit unexpected behaviour.  The items scroll towards the left, but after the final item is displayed, it will transition back to the first item by scrolling right.

This is not the expected behaviour, as [demonstrated on the documentation](https://react-bootstrap.github.io/components/carousel/), in which the Carousel scrolls infinitely towards the left in a repeating pattern.

The issue does not happen in production or when StrictMode is off, so is almost certainly due to #5075, because StrictMode causes the double-rendering of components which leads to strange behaviour.  Nonetheless I am reporting this issue for tracability in case resolving #5075 does not fix it, and to help any Googlers who are stuck with this like me and could not find a workaround.

## To Reproduce

1. Use Create React App to initialise a new project.
2. Install react-bootstrap and copy the Carousel example from https://react-bootstrap.github.io/components/carousel/
3. Launch the website and continually click the left scroll carousel button.  The final transition will go backwards, towards the right.
4. Remove StrictMode from `index.js` and reload the website.  Continually clicking the left scroll button will now always scroll towards the left.

## Environment (please complete the following information)

- React-Bootstrap Version 1.3.0

**Comment by taion** [comment] 2020-08-05 17:19
This is a duplicate of https://github.com/react-bootstrap/react-bootstrap/issues/5319. I believe https://github.com/react-bootstrap/react-bootstrap/pull/5322 will fix this.

**Closed by taion** 2020-08-05 17:19 UTC

**Comment by roblframpton** [comment] 2020-08-05 17:55
Is it a duplicate?  That ticket describes starting from the first slide and moving backwards, and the animation is described as "off", not that it goes in the wrong direction.  The issue I have reported happens when starting from the final slide and moving forwards, and it specifically results in a backwards transition.  I'm not sure it's the same thing, although it may or may not have the same root cause.

**Comment by taion** [comment] 2020-08-05 18:01
Yup, the issue there was "wrong direction". It's the same thing.

**Comment by roblframpton** [comment] 2020-08-05 18:06
Ok fair enough, thanks!
