### ISSUE TITLE
Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by Yuripetusko** [react-bootstrap/react-bootstrap#1747] opened 2016-03-31 09:31 UTC
Quite often our Sentry catches this error, however I haven't been able to reproduce it myself. 

We use `"react-bootstrap": "^0.28.2"` Error happened on different browsers, but mostly in Chrome on Windows.

It is coming from this line in Modal: 
```
var modalContent = this.getDialogElement();
var current = _domHelpersActiveElement2['default'](_utilsOwnerDocument2['default'](this));
var focusInModal = current && _domHelpersQueryContains2['default'](modalContent, current);
```

Looks like `modalContent` sometimes is `undefined`. Just as a refresher, your `getDialogElement` function looks like this:

```
getDialogElement: function getDialogElement() {
	    var node = this.refs.modal;
	    return node && node.lastChild;
	  },
```

![screenshot 2016-03-31 10 33 11](https://cloud.githubusercontent.com/assets/666169/14171673/0d3d8354-f72c-11e5-9223-c7863324d4bf.png)

**Comment by taion** [comment] 2016-03-31 13:30
Please try to provide a repro or a failing test case.

**Comment by Yuripetusko** [comment] 2016-03-31 13:41
@taion If I find a way to reproduce it I will! :). I just thought that maybe developers of react-overlays, by looking at this error, might have a clue of what is going on and give me some pointers. Maybe I should have posted it https://github.com/react-bootstrap/react-overlays ?

**Comment by jquense** [comment] 2016-03-31 14:09
if its fairly sporadic my guess its probably just a race condition with Refs being unbound. Perhaps a Modal quickly mounting and unmounting?

**Comment by wphampton** [comment] 2016-04-01 17:38
I am experiencing this same issue where a change in state (Redux) triggers the display of a Modal.  In my case I'm getting this error when the code that triggers the state change is placed in componentWillMount().  If I move the code to componentDidMount() then I no longer see this error and the Modal triggers appropriately, as many times as necessary.  The code triggering this Redux state change lives in a child component of a parent, where the Modal is actually defined.  Essentially my Modal is a "Loading, please wait..." message whenever async things are happening, that comes and goes as needed.

**Comment by Yuripetusko** [comment] 2016-04-01 18:20
Thanks a lot @wphampton I will try that and report back here

**Comment by taion** [comment] 2016-07-06 17:27
Closing pending a repro.

**Closed by taion** 2016-07-06 17:27 UTC

**Comment by brendensoares** [comment] 2016-08-09 08:26
I have this issue when simply trying to use a `DropdownButton` with `v0.30.2`.

Here's the simplest render method the reproduces the issue:
```
		return (
			<div>
				<DropdownButton title="x" id="x">
					<MenuItem>x</MenuItem>
				</DropdownButton>
			</div>
		);
```

Here are my npm modules:
```
  "dependencies": {
    "axios": "^0.9.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-html-attrs": "^2.0.0",
    "babel-plugin-transform-class-properties": "^6.3.13",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "blueimp-load-image": "^2.6.1",
    "history": "^2.0.1",
    "moment": "^2.13.0",
    "pouchdb": "^5.3.1",
    "quagga": "^0.10.2",
    "react": "^0.14.6",
    "react-autosuggest": "^3.9.0",
    "react-bootstrap": "^0.30.2",
    "react-dom": "^0.14.6",
    "react-redux": "^4.4.5",
    "react-router": "^2.0.1",
    "react-router-redux": "^4.0.5",
    "react-select": "^1.0.0-beta14",
    "redux": "^3.4.0",
    "redux-thunk": "^2.0.1",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1"
  },
```

The steps to reproduce are to simply open the dropdown and then click outside of it. In Chrome, it triggers a breakpoint before it fails with:
```
contains.js:8
 Uncaught TypeError: Cannot read property 'contains' of null(anonymous function) @ contains.js:8
componentWillUpdate @ Dropdown.js:195
_performComponentUpdate @ ReactCompositeComponent.js:535
updateComponent @ ReactCompositeComponent.js:473
ReactCompositeComponent_updateComponent @ ReactPerf.js:66
receiveComponent @ ReactCompositeComponent.js:405
receiveComponent @ ReactReconciler.js:87
_updateRenderedComponent @ ReactCompositeComponent.js:562
_performComponentUpdate @ ReactCompositeComponent.js:544
updateComponent @ ReactCompositeComponent.js:473
ReactCompositeComponent_updateComponent @ ReactPerf.js:66
performUpdateIfNecessary @ ReactCompositeComponent.js:421
performUpdateIfNecessary @ ReactReconciler.js:102
runBatchedUpdates @ ReactUpdates.js:129
perform @ Transaction.js:136
perform @ Transaction.js:136
perform @ ReactUpdates.js:86
flushBatchedUpdates @ ReactUpdates.js:147
ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66
closeAll @ Transaction.js:202
perform @ Transaction.js:149
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:176
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueForceUpdate @ ReactUpdateQueue.js:143
ReactComponent.forceUpdate @ ReactComponent.js:85
set @ index.js:27
setAndNotify @ createUncontrollable.js:142
toggleOpen @ Dropdown.js:256
handleClose @ Dropdown.js:265
handleDocumentMouse @ RootCloseWrapper.js:109
```

I'm eager to use this component, as in ASAP. I'm available for further debugging, but that's all I can offer since I am so new to this component library.

**Comment by jquense** [comment] 2016-08-09 12:32
it looks like you have more than one copy of React being pulled in to you bundle

**Comment by brendensoares** [comment] 2016-08-09 17:10
@jquense not sure how that would be possible. My app has had no such errors until I tried using this dropdown component. Any idea how I could confirm that?

**Comment by jquense** [comment] 2016-08-09 17:32
> You are trying to add a ref to an element that is being created outside of a component's render() function

this is usually the error thrown when there is mroe than one React/ReactDom instance

> Notice I am using webpack.

Which may be pulling in multiple copies of React without you realizing it.

**Comment by brendensoares** [comment] 2016-08-09 17:33
I now have 4 test cases each containing the exact same `render()` code. The only difference between the passing and failing versions is the import path:
```
import Test1 from "./test"; // Works
import Test2 from "./tickets/components/Test"; // Fails
import Test3 from "./tickets/test3"; // Works
import Test4 from "./tickets/components/test4"; // Fails
ReactDOM.render(
	<Provider store={store}>
		<Router history={history}>
			<Route path="/" component={Test4} />
		</Router>
	</Provider>
	, document.getElementById('app'));
```

The failing versions always trigger these console logs:
```
Warning: You are manually calling a React.PropTypes validation function for the `active` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `disabled` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `divider` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `eventKey` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `header` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `href` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onClick` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onSelect` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsClass` prop on `MenuItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `defaultOpen` prop on `DropdownButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsStyle` prop on `DropdownButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsSize` prop on `DropdownButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `title` prop on `DropdownButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `noCaret` prop on `DropdownButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `children` prop on `DropdownButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `defaultOpen` prop on `Uncontrolled(Dropdown)`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `dropup` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `id` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `disabled` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `pullRight` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `open` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onClose` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onToggle` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onSelect` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `role` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsClass` prop on `Dropdown`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `vertical` prop on `ButtonGroup`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `justified` prop on `ButtonGroup`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `block` prop on `ButtonGroup`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsClass` prop on `ButtonGroup`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `noCaret` prop on `DropdownToggle`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `open` prop on `DropdownToggle`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `title` prop on `DropdownToggle`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `useAnchor` prop on `DropdownToggle`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsClass` prop on `DropdownToggle`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `active` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `disabled` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `block` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onClick` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `href` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `type` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsStyle` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsSize` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsClass` prop on `Button`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `open` prop on `DropdownMenu`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `pullRight` prop on `DropdownMenu`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onClose` prop on `DropdownMenu`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `labelledBy` prop on `DropdownMenu`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onSelect` prop on `DropdownMenu`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `bsClass` prop on `DropdownMenu`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `href` prop on `SafeAnchor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `onClick` prop on `SafeAnchor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `disabled` prop on `SafeAnchor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `role` prop on `SafeAnchor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `tabIndex` prop on `SafeAnchor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

Not sure why the import path matters. I'm digging further now.

**Comment by brendensoares** [comment] 2016-08-09 17:35
@jquense I'll look more into the possibility of multiple React instances, but can you explain the test case outcome above?

**Comment by brendensoares** [comment] 2016-08-09 17:45
# Solution

@jquense is correct, there were multiple **versions** of react being loaded by webpack, because other dependent modules also required react, but were not using the same version.

I solved this with help from [this article](http://www.justincarmony.com/blog/2015/04/02/webpack-react-multiple-versions-issues/) by adding a module resolution alias to my `webpack.config.js`:
```
	resolve: {
		alias: {
			"react": __dirname + "/node_modules/react"
		}
	},
```

this forces webpack to always use the version of react that my app's `package.json` has specified.


Thank you @jquense for sharing your knowledge and helping me resolve this. I learned something valuable from you.

**Comment by taion** [comment] 2016-08-09 18:12
What? No library should _ever_ declare `react` or `react-dom` as a runtime dependency. At most they should be peer dependencies. If you're seeing this issue, you should contact the maintainers of the offending packages to not do that.

**Comment by jasonsturges** [comment] 2017-02-25 06:41
Since my searches kept routing me here, I might just note I was receiving this error when referencing `data-target` as a class instead of ID.

Likewise using ReactJS, my navbar collapse data toggle defined the data-target by class:

```
<div className="navbar-header">
  <button data-target=".navbar-collapse">
    <span className="sr-only">Toggle navigation</span>
    <span className="icon-bar"></span>
    <span className="icon-bar"></span>
    <span className="icon-bar"></span>
  </button>
</div>
<div className="navbar-collapse collapse">
```

Referencing the `data-target=".navbar-collapse" by class gave me error:

> Uncaught TypeError: Cannot read property 'contains' of undefined
    at hasClass (bootstrap-native.js:159)
    at HTMLButtonElement.Collapse.toggle (bootstrap-native.js:885)

Instead, I have to define data-target by ID:

```
<button data-target="#navbar-collapse">
...
<div id="navbar-collapse" className="navbar-collapse collapse">
```

**Comment by dmitrika** [comment] 2017-09-28 08:16
Seems like related with https://github.com/react-bootstrap/react-bootstrap/issues/2812

**Comment by fabioespinosa** [comment] 2017-10-10 00:09
Seems like the modals are not working with React 16, as @dmitrika said, check #2812
