### ISSUE TITLE
Error using components

### ISSUE THREAD

**Issue by Emmaotiki5** [react-bootstrap/react-bootstrap#6758] opened 2024-01-21 16:18 UTC
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

 of 1 unhandled error
Next.js is up to date
Unhandled Runtime Error

Error: Unsupported Server Component type: undefined
Call Stack
ej
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:264886)
<unknown>
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:276953)
Array.toJSON
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:281723)
stringify
<anonymous>
<unknown>
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:268079)
ez
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:268158)
eH
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:268559)
Timeout._onTimeout
/home/emmanuel_gbodo-otiki/projects/real_react/react_second/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:265057)
listOnTimeout
node:internal/timers (573:17)
process.processTimers
node:internal/timers (514:7)

### Expected behavior

The page is supposed to load the navbar component

### To Reproduce

npm i react-bootstrap
created a new page then added bootstrap navbar component
yarn dev

### Reproducible Example

ccyyccyy.com

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What version of React-Bootstrap are you using?

2

### What version of Bootstrap are you using?

5

### Additional context

No more context

**Comment by kyletsang** [comment] 2024-01-29 05:36
Duplicate of #6669

**Closed by kyletsang** 2024-01-29 05:36 UTC
Labels: bug
