### ISSUE TITLE
Dropdown.Item eventKey always recieved as String

### ISSUE THREAD

**Issue by scrust** [react-bootstrap/react-bootstrap#3957] opened 2019-06-26 16:14 UTC
## Describe the bug

The type of `DropdownItem`'s `eventKey` is always received by its `onSelect` handler as a `String`, even if some other type is used such as `Number`.

This breaks e.g. `===` checking when testing the received value.

## To Reproduce

1. Create a `DropdownItem` whose `eventKey` is not a `String` type (e.x. `Number`)
2. Create & set up an `onSelect` handler, and attach it to the `Dropdown.Item`
3. In the handler, log the `typeof` the received `eventKey`. Note the `typeof` is `String` rather than the type of the original value passed to the `eventKey` prop.

## Reproducable Example

[Here](https://codesandbox.io/embed/code-sandbox-examples-hcidl) (make sure to expand the Console to see log messages).

## Expected behavior

The `typeof` the `eventKey` received by the `onSelect` handler should be the same as the `typeof` the value passed to the `eventKey` prop.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Firefox Developer 68.0b1 
- React-Bootstrap Version: 1.0.0-beta.9

## Additional context

In `DropdownItem`, the `onSelect` handler is not passed the original `eventKey` value, but rather a new variable called `key`:

https://github.com/react-bootstrap/react-bootstrap/blob/3a3818f684bef99dcea0701f92790b864917b60c/src/DropdownItem.js#L91-L92

This `key` is created here:

https://github.com/react-bootstrap/react-bootstrap/blob/3a3818f684bef99dcea0701f92790b864917b60c/src/DropdownItem.js#L79

using the `makeEventKey` function from here:

https://github.com/react-bootstrap/react-bootstrap/blob/3a3818f684bef99dcea0701f92790b864917b60c/src/SelectableContext.js#L5-L8

⚠️ note the `return String(eventKey)`.

**Comment by taion** [comment] 2019-06-26 17:17
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/3536; this is a docs bug and we should update the docs to show this

**Closed by taion** 2019-06-26 17:17 UTC

**Comment by scrust** [comment] 2019-06-26 19:32
Hey @taion thanks for the quick reply.

Sorry I missed that issue before opening this one, it didn't turn up in a cursory search.

The [type definitions for `eventKey`](https://github.com/react-bootstrap/react-bootstrap/search?l=TypeScript&q=eventKey) will also need to be updated in addition to the docs; it seems like most are already typed as `string`, `unknown`, or `any`, but the types for `DropdownItem` are _particularly_ misleading:

https://github.com/react-bootstrap/react-bootstrap/blob/d9429a93e989c69e019bffac37b8b0eb75ff3a7c/types/components/DropdownItem.d.ts#L7-L14

**Comment by taion** [comment] 2019-06-26 19:33
please follow up on the open issue
