### ISSUE TITLE
Sometimes React Bootstrap doesn't style components without CDN even though React Bootstrap is installed locally. 

### ISSUE THREAD

**Issue by nnabicse** [react-bootstrap/react-bootstrap#6327] opened 2022-05-08 16:11 UTC
sometimes react bootstrap behaves crazy, it's install locally but still not styling items, after putting the CDN in app.js then it started working.

**Comment by golota60** [comment] 2022-05-08 16:50
Duplicate of #6326

**Closed by golota60** 2022-05-08 16:50 UTC
