### ISSUE TITLE
Bug broken responsive navbar in docs

### ISSUE THREAD

**Issue by PatrikTrefil** [react-bootstrap/react-bootstrap#6671] opened 2023-07-28 13:01 UTC
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The documentation examples in the [Navbar section](https://react-bootstrap.github.io/docs/components/navbar/#overview) are broken. When a user triggers a collapse into a hamburger menu and then tries to expand the menu by clicking the hamburger icon, the UI breaks.

### Expected behavior

There should not be multiple layers of text.

### To Reproduce

1. Go to [this link](https://react-bootstrap.github.io/docs/components/navbar/#overview)
2. Go to the first example
3. Make the navbar collapse by zooming in or making the browser behave like a phone/tablet.
4. Click on the hamburger menu

### Reproducible Example

https://react-bootstrap.github.io/docs/components/navbar/#overview

### Screenshots

<img width="967" alt="Screenshot 2023-07-28 145408" src="https://github.com/react-bootstrap/react-bootstrap/assets/36563492/24519a9d-a7b7-4ae6-a07b-03a129e95abe">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

-

### What version of Bootstrap are you using?

-

**Comment by PatrikTrefil** [comment] 2023-08-02 08:19
Good work @asamad35!

**Comment by CodeMode365** [comment] 2023-08-04 15:05
If this is fixed why the issue is still open?

**Comment by PatrikTrefil** [comment] 2023-08-04 15:23
> If this is fixed why the issue is still open?

PR is not merged yet.

**Comment by asamad35** [comment] 2023-08-10 14:40
> Good work @asamad35!

Thank you.
I have updated the code to maintain consistency. What can I do to make this PR get merged ?

**Closed** 2023-08-11 05:11 UTC
Labels: bug
