### ISSUE TITLE
Rendering TabPane content when Tab is active

### ISSUE THREAD

**Issue by katyo** [react-bootstrap/react-bootstrap#1149] opened 2015-08-13 06:05 UTC
In various projects I need render content in tabs. And every time I have an issue with too long rendering when then number of tabs is about five or more or content is too big. I offer some optional feature to render tabbed content only when tab is activated. What do you think about it?

**Comment by taion** [comment] 2015-08-13 06:49
Duplicate of #129. Note that the tabs were recently refactored a bit, though this is only in v0.25-rc right now.

**Closed by taion** 2015-08-13 06:49 UTC
