### ISSUE TITLE
Accordion closes on component update

### ISSUE THREAD

**Issue by TrySpace** [react-bootstrap/react-bootstrap#315] opened 2014-12-22 16:00 UTC
I have a couple of accordions, returning them from an iteration like:

        return  <Panel header={user} eventKey={uid}>
                         <UserBlock userID={user} messages={messages} />
                    </Panel>

Which in return goes into the `Accordion`:

           <Accordion> {users}  </Accordion> 

But everytime the props of `<Panel/>` change, it collapses the accordion.

I can't find a way in the "docs" other than one example, but no real customizability, maybe there is, but it's not documented.

I've tried forcefeeding it the expanded prop: 

    <Panel expanded={true} />

But its not taking that into its own state as far as I can tell.

Or am I supposed to manage their states from outside the `<Accordion/>`, with `defaultActiveKey`? Which would be a bit "counter-reactive".

At least it would be handy to have some persistant state within the components

**Comment by mtscout6** [comment] 2015-02-27 18:44
@joemcbride Can you look at this since you are looking at the Panel today?

**Comment by joemcbride** [comment] 2015-03-04 16:27
The way the `Accordion` works today is that you do control what panel is active outside of the `Accordion`.  Only one `Panel` can be active at a time.  If there is no `activeKey` provided to the `Accordion`, then the panels can be collapsed/expanded.  Otherwise if there is always an `activeKey` then there will always be one panel expanded.

Use the `onSelect` function to know what Panel has been selected so you can set the `activeKey` on the `Accordion`.

**Comment by TrySpace** [comment] 2015-03-05 22:18
It would be nice to have an option to leave expanded items manage their own open/collapsed state, so they could operate seperately. Or maybe pass an array in as the `activeKey` instead of a number, to indicate which ones are open, if you want to force the state from above. Or alternatively have the an option `keepState` to have the opening closing manually. 

But, the real problem was that I had multiple instances of the accordion, and once the parent updates, or you open another accordion, it collapses the last open instance in that same parent container. They are each instantiated in their own react component and have keys but it seems to not have been tested with multiple instances (not just accordion children, also the container) generated through `.map`.

**Comment by joemcbride** [comment] 2015-03-06 09:15
I agree that having the option to allow multiple open at once would be nice.  I think the way the `PanelGroup` is currently designed passing in an array of active keys would definitely work (and shouldn't be very hard to add).  I'm not sure about the `keepState` option.

Can you reproduce your problem with a sample?  We have multiple `Accordion`'s on the same page on the docs site without issue.

**Comment by AlexKVal** [comment] 2015-06-27 18:09
I'm closing it. 
> Multiple Accordion's on the same page on the docs site without issue.

http://react-bootstrap.github.io/components.html

**Closed by AlexKVal** 2015-06-27 18:09 UTC
