### ISSUE TITLE
ListGroup fails if list contains a single entry

### ISSUE THREAD

**Issue by leth** [react-bootstrap/react-bootstrap#548] opened 2015-04-22 08:12 UTC
It looks like this bug was introduced by f52380584f842b9db5efae4a96d77369234d5828. I suspect that

    let child = this.props.children;

should be 

    let child = this.props.children[0];

**Comment by AlexKVal** [comment] 2015-04-22 09:18
Thank you. May be @apkiernan could take a look at it.

**Comment by apkiernan** [comment] 2015-04-22 12:33
I took a quick look at this earlier, and didn't notice any immediate issue. Will look at it more tonight.

Could you provide a snippet of the failing example?

**Comment by leth** [comment] 2015-04-22 13:58
Sorry, I couldn't reproduce this with a minimal test case, I'll dig into our failure some more

**Comment by leth** [comment] 2015-04-22 14:06
Okay I found it:

      items = [
        <ListGroupItem>Item 1</ListGroupItem>
      ]
      <ListGroup>
        {items}
      </ListGroup>

**Comment by AlexKVal** [comment] 2015-04-22 16:18
The code:
```js
render: function() {
  var items = [
    <ListGroupItem>Item 1</ListGroupItem>
  ];
  return (
    <div>
      <ListGroup>
        {items}
      </ListGroup>
    </div>
  );
}
```
Generates:
```html
<div data-reactid=".0">
  <div class="list-group" data-reactid=".0.0">
    <span class="list-group-item" data-reactid=".0.0.$=10:$0">Item 1</span>
  </div>
</div>
```

Your snippet doesn't cause any problem.

You need to provide another one that causes in bug.
Or you can do even better. You write a test case for it :wink:

**Comment by mtscout6** [comment] 2015-04-22 17:12
Are you seeing this on a particular browser?

**Comment by apkiernan** [comment] 2015-04-22 23:13
So I checked it out, and the issue is with storing the `ListGroupItem`s in the `items` array and passing that in as `this.props.children`. This causes `React.Children.count(this.props.children)` to evaluate to 1, but it is an array so it can't be assigned to `child` directly. 

The fix would be adding a check to the children count === 1 condition to see if children is an array and assign child accordingly.

**Comment by Philmod** [comment] 2015-04-23 07:27
Having the same issue with v0.21.0

**Comment by mtscout6** [comment] 2015-04-23 14:36
Thanks for clarifying the cause of this bug @apkiernan. @Philmod PRs are welcome for bug fixes if you can get to it before we do :wink:

**Comment by leth** [comment] 2015-04-24 15:31
I think I've found another problem:

```
items = [
	<ListGroupItem>Item 1</ListGroupItem>
	<ListGroupItem>Item 2</ListGroupItem>
]
<ListGroup>
{items}
	<ListGroupItem>Item 3</ListGroupItem> 
	<ListGroupItem>Item 4</ListGroupItem>
</ListGroup>
```

**Closed** 2015-04-26 13:02 UTC
Labels: 1 - Awaiting Response, bug, help wanted
