### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by freemaths** [react-bootstrap/react-bootstrap#5075] opened 2020-03-27 09:25 UTC
Error generated when using <OverlayTrigger >
Warning: findDOMNode is deprecated in StrictMode.

Tested with latest 1.0.0 release of recat-bootstrap 

From what I can see this is a known issue with react-bootstrap but I am not clear on when it will be fixed or any workarounds in the meantime. Console errors are not helpful when developing. Turning off strict mode compromises other development.

see: https://reactjs.org/docs/strict-mode.html

**Comment by mxschmitt** [comment] 2020-03-27 11:27
https://github.com/react-bootstrap/react-bootstrap/blob/d983ec8897ff4b1dd52886f09dcae3417bed331d/src/Overlay.js#L114-L121


https://github.com/react-bootstrap/react-bootstrap/blob/d983ec8897ff4b1dd52886f09dcae3417bed331d/src/OverlayTrigger.js#L121-L124

seems like at these two places, hmmm. We already had this issue come up a few month ago if I remember correctly.

**Comment by freemaths** [comment] 2020-03-27 11:31
Yes, many thanks. I found some references earlier but all were closed and I couldn't see any clear instructions on work-arounds or when it might be fixed.

**Comment by jquense** [comment] 2020-03-27 14:16
arg, we should have removed this probably, like we did for dropdowns. 

What we can do tho is only call findDOMNode if required. that way users can avoid it themselves by not using class component refs

**Comment by freemaths** [comment] 2020-03-27 19:56
Thanks. Happy to test any updated version.

**Comment by webcoderkz** [comment] 2020-03-30 10:56
Just faced the same issue on a clean CRA app with react-bootstrap@1.0.0

**Comment by jquense** [comment] 2020-03-30 14:13
PR's welcome if folks wanna get it fixed quicker, we will get to it but it's lower on the priority list since it's an opt in warning

**Comment by Korywon** [comment] 2020-04-01 12:17
I encountered this warning as well when using the navbar collapse. Here's the stacktrace:

```
    in div (created by Context.Consumer)
    in Transition (created by Collapse)
    in Collapse (created by Context.Consumer)
    in NavbarCollapse (at navbar-menu.component.js:18)
    in nav (created by Navbar)
    in Navbar (at navbar-menu.component.js:13)
    in NavbarMenu (at App.js:18)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:17)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

Haven't found the reference in code just yet.

**Comment by ratchapol-an** [comment] 2020-04-02 14:50
Modal also has this issue too.

> index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Modal which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Modal)
    in Transition (created by Fade)
    in Fade (created by BackdropTransition)
    in BackdropTransition (created by Modal)
    in Modal (created by ForwardRef)
    in ForwardRef (created by Modal)
    in Modal (created by Bootstrap(Modal))
    in Bootstrap(Modal) (at NewCustomerModal.tsx:13)
    in NewCustomerModal (at Customers.tsx:27)
    in div (at Customers.tsx:18)
    in Customers (at withMainLayout.tsx:26)
    in div (created by Container)
    in Container (at withMainLayout.tsx:25)
    in main (at withMainLayout.tsx:23)
    in div (at withMainLayout.tsx:21)
    in withMainLayout(Component) (created by Context.Consumer)
    in Route (at Routes.tsx:11)
    in Switch (at Routes.tsx:9)
    in Router (created by BrowserRouter)
    in BrowserRouter (at Routes.tsx:8)
    in Routes (at App.tsx:7)
    in App (at src/index.tsx:11)
    in StrictMode (at src/index.tsx:10)

**Comment by HunteRoi** [comment] 2020-04-04 18:13
Just got the issue with `Accordion.Collapse` : 
```
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by AccordionCollapse)
    in Transition (created by Collapse)
    in Collapse (created by AccordionCollapse)
    in AccordionCollapse (at Contributor/index.tsx:30)
    in div (created by ForwardRef)
    in ForwardRef (at Contributor/index.tsx:26)
    in div (at Contributor/index.tsx:25)
    in Contributor (at App/index.tsx:33)
    in div (at PageLayout/index.tsx:18)
    in main (at PageLayout/index.tsx:17)
    in div (at PageLayout/index.tsx:12)
    in PageLayout (at App/index.tsx:32)
    in Route (at App/index.tsx:31)
    in Switch (at App/index.tsx:14)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App/index.tsx:13)
    in App (at src/index.tsx:10)
    in StrictMode (at src/index.tsx:9)
```

**Comment by kheide** [comment] 2020-04-07 10:11
Tab.Pane also has the same issue

**Comment by HunteRoi** [comment] 2020-04-07 22:45
I have quickly checked the repository to find all `findDOMNode` references and here are the places where it is currently used and/or referenced as documentation :
- [www/src/pages/components/forms.js](https://github.com/react-bootstrap/react-bootstrap/blob/724ea6f7cbc9fa34c60ff74d72f14bc42feab9f7/www/src/pages/components/forms.js)
- []()

**Comment by jquense** [comment] 2020-04-08 13:20
I'm in the process of fixing this upstream with: https://github.com/react-bootstrap/react-overlays/pull/794/files#diff-97a43659c6311e819ce665f4a3291f58 which we can use here as well once it's merged and upgraded

**Comment by ajayala** [comment] 2020-04-19 02:36
The issue is came from a dependency, react-transition-group. It has to fixed from this side. Here's the offending code:  

https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js

**Comment by HunteRoi** [comment] 2020-04-19 11:41
It looks like they already know about the issue in this particular library as well : [#429](https://github.com/reactjs/react-transition-group/issues/429)

**Comment by martinKindall** [comment] 2020-04-19 20:01
Had this issue using <Modal ../>
`index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Modal)
    in Transition (created by Fade)
    in Fade (created by BackdropTransition)
    in BackdropTransition (created by Modal)
    in Modal (created by ForwardRef)
    in ForwardRef (created by Modal)
    in Modal (created by Bootstrap(Modal))
    in Bootstrap(Modal) (at FilterForm.tsx:13)
    in FilterForm (at Searcher.tsx:29)
    in Searcher (at BottomBar.tsx:80)
    in Route (at BottomBar.tsx:79)
    in Switch (at BottomBar.tsx:68)
    in div (at BottomBar.tsx:26)
    in BottomBar (at App.tsx:9)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:8)
    in App (at src/index.tsx:9)
    in StrictMode (at src/index.tsx:8)`

**Comment by devcrp** [comment] 2020-04-23 13:49
Thanks @jquense ! Upgrading to the fresh 1.0.1 version fixed it.

**Comment by jquense** [comment] 2020-04-23 15:27
Yes we are waiting for react transition group to update as well

**Comment by mabsystems** [comment] 2020-04-24 14:07
v.1.0.1: "Warning: findDOMNode is deprecated" still actual

**Comment by envious** [comment] 2020-04-24 15:54
Also facing this issue.

**Comment by sylwiasuwalska** [comment] 2020-04-24 17:59
Modal with animation set to false.
Updated to v 1.0.1.

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Modal which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Modal)
    in Modal (created by ForwardRef)
    in ForwardRef (created by Modal)
    in Modal (created by Bootstrap(Modal))
    in Bootstrap(Modal) (at Options.js:25)
    in Options (at Grid.js:152)
    in div (created by Col)
    in Col (at Grid.js:151)
    in div (created by Row)
    in Row (at Grid.js:146)
    in Grid (at App.js:24)
    in div (created by Container)
    in Container (at App.js:8)
    in App (at src/index.js:10)
    in StrictMode (at src/index.js:9)

**Comment by onomzzzy** [comment] 2020-05-02 10:36
``

**Comment by carliey** [comment] 2020-05-02 17:07
Having the same issue with material-ui dialog

**Comment by devcrp** [comment] 2020-05-04 10:45
I must be doing something different, beacause creating the modal with animation={false} doesn't raise the warning for me, and I got it if I set it to true.

> <Modal
          show={showMultiple}
          onHide={() => setShowMultiple(false)}
          animation={false}
        >
          <Modal.Header closeButton>
            <Modal.Title>Modal heading</Modal.Title>
          </Modal.Header>
          <Modal.Body>Woohoo, you're reading this text in a modal!</Modal.Body>
          <Modal.Footer>
            <Button variant="success">Select</Button>
          </Modal.Footer>
        </Modal>

**Comment by garycyyeung** [comment] 2020-05-05 05:50
I had the same messages before when I used <Modal> or <Alert>

The following is the solution for fixing the issue:
1) For <Modal>, add animation={false} within the tag
2) For <Alert> add transition={null} within the tag

**Comment by wolfgang-reutz** [comment] 2020-05-13 13:36
I have the error with Accordion when I toggle a Accordion.Collapse element.
Tried both animation and transition parameter with false and null but no luck.

Any hints on how to fix this problem for Accordion until react-transition fixes it?

using react-bootstrap@1.0.1

**Comment by kunuit** [comment] 2020-05-15 08:28
So sad, my eyes don't like it

### ```

> index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
>     in div (created by ForwardRef(Paper))
>     in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
>     in WithStyles(ForwardRef(Paper)) (created by Transition)
>     in Transition (created by ForwardRef(Grow))
>     in ForwardRef(Grow) (created by TrapFocus)
>     in TrapFocus (created by ForwardRef(Modal))
>     in div (created by ForwardRef(Modal))
>     in ForwardRef(Portal) (created by ForwardRef(Modal))
>     in ForwardRef(Modal) (created by ForwardRef(Popover))
>     in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
>     in WithStyles(ForwardRef(Popover)) (created by ForwardRef(Menu))
>     in ForwardRef(Menu) (created by WithStyles(ForwardRef(Menu)))
>     in WithStyles(ForwardRef(Menu)) (at Header/index.js:42)
>     in div (at Header/index.js:59)
>     in Header (created by WithStyles(Header))
>     in WithStyles(Header) (at Dashboard/index.js:13)
>     in div (at Dashboard/index.js:12)
>     in Dashboard (created by WithStyles(Dashboard))
>     in WithStyles(Dashboard) (at AdminLayoutRoute/index.js:18)
>     in Route (at AdminLayoutRoute/index.js:14)
>     in AdminLayoutRote (created by WithStyles(AdminLayoutRote))
>     in WithStyles(AdminLayoutRote) (at App/index.js:27)
>     in Switch (at App/index.js:49)
>     in ThemeProvider (at App/index.js:44)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (at App/index.js:43)
>     in Provider (at App/index.js:42)
>     in App (created by WithStyles(App))
>     in WithStyles(App) (at src/index.js:9)
>     in StrictMode (at src/index.js:8)
> console.<computed> @ index.js:1
> r @ react_devtools_backend.js:6
> printWarning @ react-dom.development.js:88
> error @ react-dom.development.js:60
> findHostInstanceWithWarning @ react-dom.development.js:24306
> findDOMNode @ react-dom.development.js:24804
> performEnter @ Transition.js:245
> updateStatus @ Transition.js:228
> componentDidUpdate @ Transition.js:192
> commitLifeCycles @ react-dom.development.js:19835
> commitLayoutEffects @ react-dom.development.js:22803
> callCallback @ react-dom.development.js:188
> invokeGuardedCallbackDev @ react-dom.development.js:237
> invokeGuardedCallback @ react-dom.development.js:292
> commitRootImpl @ react-dom.development.js:22541
> unstable_runWithPriority @ scheduler.development.js:653
> runWithPriority$1 @ react-dom.development.js:11039
> commitRoot @ react-dom.development.js:22381
> finishSyncRender @ react-dom.development.js:21807
> performSyncWorkOnRoot @ react-dom.development.js:21793
> (anonymous) @ react-dom.development.js:11089
> unstable_runWithPriority @ scheduler.development.js:653
> runWithPriority$1 @ react-dom.development.js:11039
> flushSyncCallbackQueueImpl @ react-dom.development.js:11084
> flushSyncCallbackQueue @ react-dom.development.js:11072
> discreteUpdates$1 @ react-dom.development.js:21893
> discreteUpdates @ react-dom.development.js:806
> dispatchDiscreteEvent @ react-dom.development.js:4168

```

**Comment by jquense** [comment] 2020-05-15 13:17
Folks please stop posting the same example of react-transition-group causing an error, its not helpful to the discussion. We know why these occur, If someone wants to upgrade RTG to the latest and migrate to the `nodeRef` API that will speed this along, otherwise don't run in StrictMode if you don't want to see the errors thanks!

**Comment by kyletsang** [comment] 2021-05-28 04:47
Fixed in v2 alpha

**Closed by kyletsang** 2021-05-28 04:47 UTC
