### ISSUE TITLE
Can't give a custom class to a modal element (to change its width)

### ISSUE THREAD

**Issue by DelvarWorld** [react-bootstrap/react-bootstrap#560] opened 2015-04-23 22:19 UTC
See this line: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L58

The className of a modal is hard coded to `"modal-dialog"`. I need to change this specific modal's width, so I'd like to give it a custom class. Passing in className puts the className on the element *inside* the modal, which is frustrating. 

I could give the parent element a custom class and then use a nested selector to match it, but that's not ideal.

**Comment by DelvarWorld** [comment] 2015-04-23 22:20
Possible dupe of https://github.com/react-bootstrap/react-bootstrap/issues/404

**Comment by mtscout6** [comment] 2015-04-27 16:53
I don't see this as a dupe of #404. Though we should provide the means to supply custom classes to the Modal's `className` prop. This is actually a larger issue that we need to discuss and either determine a proper fix for across the project. There is a similar issue currently being mentioned in #517. This will need to be figured out as part of our 1.0.0 roadmap.

**Comment by mtscout6** [comment] 2015-04-27 16:57
I have updated the 1.0.0 roadmap with this issue.

**Comment by DelvarWorld** [comment] 2015-04-27 17:03
Thank you! :smiley:

**Comment by mtscout6** [comment] 2015-05-19 18:14
Resolved by #696

**Closed by mtscout6** 2015-05-19 18:14 UTC

**Comment by topgun743** [comment] 2015-09-22 13:44
How can I set custom width and height (without using external CSS class) on a react-bootstrap modal?
I have tried setting like so 
<Modal style={{width:'300px'}} />
But it applies on the outer div and not on the modal dialog div. If I apply to width height to modal body then its behavior becomes weird. Whats the proper way doing that?

**Comment by jordync3** [comment] 2019-08-30 15:38
If anybody is still looking for the answer, this is how i fixed it:

 <Modal dialogClassName={"CSRModal"} centered show={props.modal} onHide={props.toggleModal} >


With the CSS class of:

.CSRModal{
    width: 90%;
    max-width: none!important;
}


**The important part is ** to make sure you add **max-width: none!important;**
