### ISSUE TITLE
Unrelevant code samples in Introduction started page

### ISSUE THREAD

**Issue by NtsDK** [react-bootstrap/react-bootstrap#3506] opened 2019-02-27 17:12 UTC
Browser globals and style sheets show unrelevant code samples.
https://react-bootstrap.github.io/getting-started/introduction/

![image](https://user-images.githubusercontent.com/669689/53508972-2379f000-3abb-11e9-902f-348e250810a2.png)

**Comment by mxschmitt** [comment] 2019-03-20 14:07
Duplicate of #3540

**Closed by mxschmitt** 2019-03-20 14:07 UTC
