### ISSUE TITLE
Panel-collapse wrong height when body is changed

### ISSUE THREAD

**Issue by iam4x** [react-bootstrap/react-bootstrap#410] opened 2015-02-25 11:49 UTC
When you add content in the body of the panel, the heigh isn't re-calculated. 

This breaks the layout (a gif is better than explanation):

![gif](http://zippy.gfycat.com/JointThatGreathornedowl.gif)

I have an easy fix, but it adds a little glitch to the animation:

```(css)
.panel-collapse.collapse.in {
  height: 100% !important;
}
```

**Comment by joemcbride** [comment] 2015-03-04 07:31
This should be fixed when https://github.com/react-bootstrap/react-bootstrap/pull/427 is merged.

**Comment by joemcbride** [comment] 2015-03-04 07:32
Duplicate of https://github.com/react-bootstrap/react-bootstrap/issues/399

**Closed** 2015-03-04 07:33 UTC
Labels: bug, duplicate, help wanted
