### ISSUE TITLE
Update for 15.5 deprecations

### ISSUE THREAD

**Issue by Kepro** [react-bootstrap/react-bootstrap#2550] opened 2017-04-09 18:12 UTC
Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by jquense** [comment] 2017-04-09 21:16
PR s welcome

**Comment by daveyx** [comment] 2017-04-10 00:02
Warning: Uncontrolled(Dropdown) comes from uncontrollable/createUncontrollable.js and uncontrollable@4.0.3 is a dep of react-bootstrap 0.30.8

I have same issue and furthermore another one which i post here as it belongs to the issue title: 

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

react-bootstrap/es/PanelGroup.js

Both issues with react-bootstrap 0.30.8 together with react 15.5.3

**Comment by tmobaird** [comment] 2017-04-10 04:24
I can help knock out the PropTypes warnings if it's still up for grabs

**Comment by sorahn** [comment] 2017-04-10 18:56
@tmobaird Got em over here: https://github.com/react-bootstrap/react-bootstrap/pull/2552

(There was a different bug filed specifically for PropTypes)

**Comment by tmobaird** [comment] 2017-04-10 19:54
Sweet! Thanks @sorahn!

**Comment by fredjiles** [comment] 2017-04-12 23:58
Looks like once this PR gets merged in the deps can be updated and the warning should go away.  https://github.com/jquense/uncontrollable/pull/22

**Comment by bigkrp** [comment] 2017-04-18 12:50
Have same trouble. Update to latest react-bootstrap(0.30.8), but have warning about bootstrap-components
```
warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning	@	warning.js:36
warning	@	warning.js:60
get	@	React.js:95
(anonymous)	@	PropTypes.js:3
__webpack_require__	@	bootstrap 85711cc…:691
fn	@	bootstrap 85711cc…:110
(anonymous)	@	main.js?85711cc…:114366
(anonymous)	@	main.js?85711cc…:114436
__webpack_require__	@	bootstrap 85711cc…:691
fn	@	bootstrap 85711cc…:110
(anonymous)	@	index.js:90
__webpack_require__	@	bootstrap 85711cc…:691
fn	@	bootstrap 85711cc…:110
(anonymous)	@	emitter.js:2
(anonymous)	@	main.js?85711cc…:55746
__webpack_require__	@	bootstrap 85711cc…:691
fn	@	bootstrap 85711cc…:110
(anonymous)	@	main.js?85711cc…:131487
__webpack_require__	@	bootstrap 85711cc…:691
webpackJsonpCallback	@	bootstrap 85711cc…:23
(anonymous)	@	main.js?85711cc…:1
```

**Comment by ProtectedVoid** [comment] 2017-04-18 13:27
I'm also having the same issue.  I pulled master locally and have inspected the source code, and indeed it looks like all instances of React.PropTypes have been migrated to PropTypes, however, when the code is transpiled, the output is still referencing PropTypes from the main React object.

![image](https://cloud.githubusercontent.com/assets/464291/25132894/0d74e2d4-2419-11e7-9326-cd68bf086ea0.png)

This is a screenshot debugging that actual output to the browser, and in this case, it's PanelGroup that appears to be the culprit.

**Comment by ProtectedVoid** [comment] 2017-04-18 13:30
From the /dist directory, lines 2036 - 2042
`	var propTypes = {
	  accordion: _react2['default'].PropTypes.bool,
	  activeKey: _react2['default'].PropTypes.any,
	  defaultActiveKey: _react2['default'].PropTypes.any,
	  onSelect: _react2['default'].PropTypes.func,
	  role: _react2['default'].PropTypes.string
	};`

It looks like /dist wasn't updated to reflect the code refactor?

**Comment by ProtectedVoid** [comment] 2017-04-18 13:41
So, upon further review, it looks like https://github.com/react-bootstrap/react-bootstrap/pull/2552 has been merged, but not released yet?

**Comment by jharris4** [comment] 2017-04-18 13:57
+1 for getting a release with #2552 merged

**Comment by taion** [comment] 2017-04-18 23:12
released in v0.30.9

**Closed by taion** 2017-04-18 23:12 UTC

**Comment by Nabrok** [comment] 2017-04-19 01:38
I still get the PropTypes message when using a Dropdown, and the createClass message when using Modal.

**Comment by daveyx** [comment] 2017-04-19 01:43
me too, seems not be fixed in 0.30.9

**Comment by jharris4** [comment] 2017-04-19 03:29
I'm still getting warning from packages such as https://github.com/react-bootstrap/react-overlays and I think also https://github.com/jquense/uncontrollable

**Comment by bigkrp** [comment] 2017-04-19 05:42
It seems that the react-bootstrap depends on react-overlays
![default](https://cloud.githubusercontent.com/assets/11586744/25164856/0acb0e32-24dc-11e7-8340-013b44c1a45b.JPG)

**Comment by bigkrp** [comment] 2017-04-24 12:55
U should upgrade uncontrollable dependency for lates version, for prevent warnings like this
`
Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
`
https://github.com/jquense/uncontrollable/issues/23#issuecomment-296655369

**Comment by UX-Unicorn** [comment] 2017-05-01 17:53
I am still getting this same warning even after I updated to v0.31.0

**Comment by jharris4** [comment] 2017-05-01 18:22
@UX-Unicorn 0.31.0 fixed all issues for me. Maybe try clearing your node_modules and installing from a clean state?

Otherwise, a sample error message would help to pinpoint which component or dependency of react-bootstrap is causing the warning.

**Comment by azotova** [comment] 2017-05-16 23:40
I am getting the same warning after updating to v.0.31.0 too.
According to the error message, it looks like the issue is with line 8198 here in react-bootstrap build: https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.js, which seems to come from uncontrollable dependency but is different from 'createUncontrollable.js' file in v. 4.1.0 of uncontrollable.

**Comment by chaholl** [comment] 2017-06-07 18:06
Still not working for me with v0.31 and latest version of uncontrollable

`Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead.`

It's worth mentioning that I'm using the file from dist and in there I see:
```javascript
var component = _react2.default.createClass(_extends({
	      displayName: 'Uncontrolled(' + displayName + ')',
	      mixins: mixins,
	      propTypes: propTypes
	    }
```
