### ISSUE TITLE
Dropdown.Toggle forces the onClick attribute

### ISSUE THREAD

**Issue by BenMorel** [react-bootstrap/react-bootstrap#4972] opened 2020-02-06 16:33 UTC
I'm trying to use a custom dropdown toggle, as per the [docs](https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components). Using the same code as in the docs, I get an error:

> Error:(11, 18) TS2769: No overload matches this call.

> Overload 1 of 2, '(props: Readonly<ReplaceProps<typeof CustomDropdownToggle, BsPrefixProps<typeof CustomDropdownToggle> & DropdownToggleProps>>): DropdownToggle<...>', gave the following error.  
> Property 'onClick' is missing in type '{ as: typeof CustomDropdownToggle; id: string; }' but required in type 'Readonly<ReplaceProps<typeof CustomDropdownToggle, BsPrefixProps<typeof CustomDropdownToggle> & DropdownToggleProps>>'.

> Overload 2 of 2, '(props: ReplaceProps<typeof CustomDropdownToggle, BsPrefixProps<typeof CustomDropdownToggle> & DropdownToggleProps>, context?: any): DropdownToggle<...>', gave the following error.  
> Property 'onClick' is missing in type '{ as: typeof CustomDropdownToggle; id: string; }' but required in type 'Readonly<ReplaceProps<typeof CustomDropdownToggle, BsPrefixProps<typeof CustomDropdownToggle> & DropdownToggleProps>>'.

![image](https://user-images.githubusercontent.com/1952838/73956783-ba733d00-4905-11ea-851f-6acb5934abd7.png)

Notes:

- if I remove the `as={}`, the error disappears, and so does my customization
- if I provide an empty `onClick={() => {}}`, the error disappears, but the toggle doesn't work anymore
- if I ignore the error, the code still compiles, with a big red error, but it works

What's the issue here? **Why does `onClick` seem to be mandatory?**

**Comment by taion** [comment] 2020-02-06 17:01
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/4819; the answer is that our types are probably set up wrong, and we'd be happy to take a PR to fix them

**Closed by taion** 2020-02-06 17:01 UTC
