### ISSUE TITLE
Dropdown focus behaviour differs from standard bootstrap

### ISSUE THREAD

**Issue by dpwrussell** [react-bootstrap/react-bootstrap#2074] opened 2016-07-19 21:36 UTC
On standard bootstrap, when selecting an option, the button is not focused afterwards. In React-bootstrap, it is. It's minor, but it makes anything using dropdowns look messy.

Bootstrap: http://getbootstrap.com/components/#btn-dropdowns-single
React-Bootstrap: https://react-bootstrap.github.io/components.html#btn-dropdowns-single

1. Click button
2. Click an action
3. On Bootstrap, the button will not have focus. On React-Bootstrap, it will have focus,

**Comment by taion** [comment] 2016-07-19 21:41
Dupe of existing issues. The standard BS behavior violates ARIA guidelines. See previous discussion.

**Closed by taion** 2016-07-19 21:41 UTC
