### ISSUE TITLE
"Cannot read property 'scrollHeight'" error on resize after Modal unmount

### ISSUE THREAD

**Issue by mjomble** [react-bootstrap/react-bootstrap#1550] opened 2015-12-07 13:08 UTC
The error can be reproduced on this fiddle: https://jsfiddle.net/7vwzLjo2/

`_onShow` sets up the resize handler and `_onHide` removes it, but if you unmount the Modal from the DOM after `_onShow`, the resize handler remains active and runs code that references `this._modal` which is now null.

Adding a `componentWillUnmount` that removes the handler fixes the issue.
I would've made a pull request, but wasn't sure if the rest of the `_onHide` code needs to run as well, etc.

**Comment by taion** [comment] 2015-12-07 14:32
Dupe of https://github.com/react-bootstrap/react-bootstrap/issues/1538.

**Closed by taion** 2015-12-07 14:32 UTC
