### ISSUE TITLE
Allow more propTypes in FormControl.Static

### ISSUE THREAD

**Issue by ljconde** [react-bootstrap/react-bootstrap#1154] opened 2015-08-13 16:46 UTC
Currently, FormControl.Static is limited to only Strings or Numbers:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/childrenValueInputValidation.js#L5

I was trying to use it to render a component as a child, but have to live with a warning saying that I'm not passing the correct propType. 

Would it be useful to others to allow more propTypes?

**Comment by taion** [comment] 2015-08-13 17:09
Duplicate of https://github.com/react-bootstrap/react-bootstrap/issues/1023.

**Closed by taion** 2015-08-13 17:09 UTC
