### ISSUE TITLE
React Bootstrap Modal - Error: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by jasonchuot07** [react-bootstrap/react-bootstrap#5507] opened 2020-11-05 10:56 UTC
## React Bootstrap Modal - Error: findDOMNode is deprecated in StrictMode

I copied the Modal from 
https://react-bootstrap.netlify.app/components/modal/#modals
And on setShow(true) the Modal opened but there was an Error saying these

## Screenshots
![image](https://user-images.githubusercontent.com/63581947/98232331-1e5b8c80-1f90-11eb-9a2d-930d088a7b3b.png)

![image](https://user-images.githubusercontent.com/63581947/98232371-29162180-1f90-11eb-84de-2cb595918510.png)

**Comment by kyletsang** [comment] 2020-11-05 18:23
Dupe of #5075

**Closed by kyletsang** 2020-11-05 18:23 UTC
