### ISSUE TITLE
Can't split Navbar elements

### ISSUE THREAD

**Issue by alihammad-gist** [react-bootstrap/react-bootstrap#700] opened 2015-05-19 01:56 UTC
As a whole this markup works.
```
<Navbar inverse>
	<Nav right>
		<Dropdown title="Hello" noCaret>
			<h6>Login with</h6>
			<MenuItem href="/auth/facebook">
				<FbIcon />
				Facebook
			</MenuItem>
			<MenuItem href="/auth/twitter">
				<TwtIcon />
				Twitter
			</MenuItem>
		</Dropdown>
	</Nav>
</Navbar>
```

But when split, it doesn't

```
Auth = React.createClass {
	render: ->
		<Nav right>
			<Dropdown title="Hello" noCaret>
				<h6>Login with</h6>
				<MenuItem href="/auth/facebook">
					<FbIcon />
					Facebook
				</MenuItem>
				<MenuItem href="/auth/twitter">
					<TwtIcon />
					Twitter
				</MenuItem>
			</Dropdown>
		</Nav>
}

App = React.createClass {
	render: ->
		<Navbar inverse>
			<Auth />
		</Navbar>
}
```

This doesn't work either, It creates a div element instead of li
```
Auth = React.createClass {
	render: ->
		<Dropdown title="Hello" noCaret>
				<h6>Login with</h6>
				<MenuItem href="/auth/facebook">
					<FbIcon />
					Facebook
				</MenuItem>
				<MenuItem href="/auth/twitter">
					<TwtIcon />
					Twitter
				</MenuItem>
			</Dropdown>
}

App = React.createClass {
	render: ->
		<Navbar inverse>
                       <Nav>
			<Auth />
                        </Nav>
		</Navbar>
}
```

**Comment by mtscout6** [comment] 2015-05-19 02:20
`Dropdown`s don't currently play well with `Navbar`s when collapsed.

#526

**Comment by AlexKVal** [comment] 2015-05-22 08:48
I cannot reproduce it

Can you provide reproducible snippet ?
Or better yet, tests ? :cherries: 

https://gist.github.com/AlexKVal/f9c20ed2129a5779f1c1
![screen shot 2015-05-22 at 11 18 18 am](https://cloud.githubusercontent.com/assets/847572/7767074/2f4eb2ca-0078-11e5-94cf-1250e38a3105.png)

**Comment by alihammad-gist** [comment] 2015-05-22 22:33
Sorry for confusion. Dropdown is a reference to DropdownButton as used in the Navbar documentation not DropdownMenu. I believe the bug is reproduce-able with DropdownButton.

I tried running `npm test` as described in the README.md. It used so much CPU that my machine hanged (itself). I really want to contribute but it seems impossible. I haven't tested JS code before either.

Actually i didn't know about navItem prop for DropdownButton which could be used explicitly to produce `li.dropdown` instead of `div.btn-group` as in this test https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownButtonSpec.js#L162 . Problem is with Navbar and DropdownButton integration because Navbar wouldn't render DropdownButton as `li.dropdown` if it is nested inside another element like `Auth` in my case.

I think using navItem prop should be mentioned in documentation even better would be removing implicitly rendering DropdownButton as `li.dropdown` when in navbar and making navItem prop mandatory if user wants `li`.

**Comment by AlexKVal** [comment] 2015-05-23 22:23
> Sorry for confusion.

No worries. I ought to check `DropdownButton` too. :blush: 
As I can see `navItem` prop helps to solve your case. 
![screen shot 2015-05-24 at 12 55 28 am](https://cloud.githubusercontent.com/assets/847572/7785883/89947b14-01b0-11e5-8273-fc12e5ffbe20.png)

In #526 overhaul of `DropdownButton` your proposals will be addressed :+1: 
As you can see it is already added as:
- [ ] `Dropdown should work within a collapsed Navbar. Should resolve 421, and #700`

Should we close this issue now ?

**Comment by mtscout6** [comment] 2015-05-25 13:15
Sure

**Closed by mtscout6** 2015-05-25 13:15 UTC
Labels: 1 - Awaiting Response
