### ISSUE TITLE
Disabling button should disable onClick handler

### ISSUE THREAD

**Issue by akarve** [react-bootstrap/react-bootstrap#1780] opened 2016-04-06 16:56 UTC
Hi. I see the the [doc section](https://react-bootstrap.github.io/components.html#buttons-disabled) on "Event handler functionality not impacted." I humbly propose that 99% of the time if a `Button` is disabled, the developer will also want to disable it's `onClick` handler. So, to better address the common case, `disabled=true` should also disable `onClick`.

It seems odd to have to do the following with Buttons and related classes:
```jsx
<PageItem
  disabled={!hasPreviousPage}
  onClick={!hasPreviousPage ? NO_OP : previousClick}
  previous>
```

Perhaps I'm missing something or there's a previous discussion on this? Neither Google nor GitHub Issues turned up anything.

Thanks. Overall react-bootstrap is excellent.

**Comment by afraser** [comment] 2016-04-08 17:29
👍

**Comment by jquense** [comment] 2016-04-08 17:32
disabled buttons do disable clicks...Am I missing some browser quirk? disabled elements don't fire mouse events generally

**Comment by taion** [comment] 2016-04-08 17:34
We render an `<a>` when there's an `href`, so the disabling is handled via CSS, but you can still "click" them with e.g. keyboard. It might make sense for us to handle this in React-Bootstrap, and avoid the caveat from e.g. http://getbootstrap.com/css/#anchor-element-1.

**Comment by jquense** [comment] 2016-04-08 17:35
ah ok, yeah we should definately handle that

**Comment by akarve** [comment] 2016-04-08 17:51
I would add that `PageItem` at least as of version 0.28.3, allows mouse clicks as well, even when disabled. The Bootstrap doc, linked above, also suggests that disabling and onClick are orthogonal. Thanks, for looking into this.

**Comment by taion** [comment] 2016-04-08 20:53
This is actually a dupe of https://github.com/react-bootstrap/react-bootstrap/issues/1415.

**Closed by taion** 2016-04-08 20:53 UTC
Labels: enhancement
