### ISSUE TITLE
TabbedArea doesn't work

### ISSUE THREAD

**Issue by stefanvermaas** [react-bootstrap/react-bootstrap#332] opened 2015-01-12 13:18 UTC
Hi folks,

I've got some trouble implementing the react-bootstrap library in our new app. I've got a pretty simple piece of code, but clicking on the tabs doesn't actually make the tabs to switch. It stays on the defaultActiveKey tab.

```javascript
/** @jsx React.DOM */
var React = require('react');

/* Component */
var TabbedArea      = require('react-bootstrap').TabbedArea,
    TabPane         = require('react-bootstrap').TabPane,
    ColumnsPreview  = require('./ColumnsPreview.react'),
    DataPreview     = require('./DataPreview.react'),
    MetaDataPreview = require('./MetaDataPreview.react');

var TableInfo = React.createClass({
  displayName: 'TableInfo',
  render: function () {
    return (
      <section className="row spaced tables-selector-row">
        <div className="col-sm-12">
          <TabbedArea defaultActiveKey={1}>

            <TabPane eventKey={1} tab="Columns">
              <ColumnsPreview />
            </TabPane>

            <TabPane eventKey={2} tab="Data Preview">
              <DataPreview />
            </TabPane>

            <TabPane eventKey={3} tab="Meta data">
              <MetaDataPreview />
            </TabPane>

          </TabbedArea>
        </div>
      </section>
    );
  }
});
```

As you can see I've got the second tab selected, but the content of the first tab is showing up: ![](http://f.cl.ly/items/0v3g1n1V0k0T2u3T191f/Schermafbeelding%202015-01-12%20om%2014.17.16.png)

Any idea what I'm doing wrong?

Cheers!

**Comment by trentgrover-wf** [comment] 2015-01-12 14:47
If I paste your render code into 1 of the code windows on the React Bootstrap examples site (http://react-bootstrap.github.io/components.html#tabs), inserting normal divs in place of the React components that aren't defined in your snippet, the code works as expected.

```
var tabbedAreaInstance = (
      <section className="row spaced tables-selector-row">
        <div className="col-sm-12">
          <TabbedArea defaultActiveKey={1}>

            <TabPane eventKey={1} tab="Columns">
              <div>Columns View</div>
            </TabPane>

            <TabPane eventKey={2} tab="Data Preview">
              <div>Data View</div>
            </TabPane>

            <TabPane eventKey={3} tab="Meta data">
              <div>Meta View</div>
            </TabPane>

          </TabbedArea>
        </div>
      </section>
);

React.render(tabbedAreaInstance, mountNode);
```

There doesn't appear to be anything wrong with the code you've included here.

**Comment by stefanvermaas** [comment] 2015-01-12 16:53
Well the component renders fine, it seems the toggling is broken.. Will dig into this issue futher.

**Comment by cainus** [comment] 2015-02-02 18:47
I've got the same issue.  I haven't figured out how/why yet though.  :\

**Comment by stefanvermaas** [comment] 2015-02-02 19:43
Hmm me neither.. Class names are also changing, but the content doesn't change. Is this happening to you too?

**Comment by cainus** [comment] 2015-02-02 20:05
I'll have to check when I get back home.  Are you using rackt/react-router per chance?

**Comment by stefanvermaas** [comment] 2015-02-02 20:56
No I didn't.

**Comment by stefanvermaas** [comment] 2015-02-17 15:34
I've found that something goes wrong with the animation. If you set the animation to false, it does work.

**Comment by mtscout6** [comment] 2015-02-27 18:21
Is there any way you can provide a unit test here so we can know it's fixed once the test works?

**Comment by owenconti** [comment] 2015-07-03 14:30
+1 I had the same issue. No errors or any mention that anything was broken, apart from the tabs not switching. Setting animation={false} also fixed this for me.

**Comment by AlexKVal** [comment] 2015-07-05 16:54
We need a reproducible code snippet with an issue.
Otherwise it is not clear what exactly `isn't working` so far. :sweat: 
(let alone two mentions about animation)

As it already has been mentioned https://github.com/react-bootstrap/react-bootstrap/issues/332#issuecomment-69579798 provided code works fine.

Because it is not clear what the problem exactly is, 
I'm closing this issue. :sparkle: 

We re-open it and change issue name,
when `a reproducible code snippet with an issue` will be provided :wink:
:cherries:

**Closed by AlexKVal** 2015-07-05 16:54 UTC
Labels: 1 - Awaiting Response, bug, help wanted
