### ISSUE TITLE
Reposition a popover while it is open

### ISSUE THREAD

**Issue by thetimbanks** [react-bootstrap/react-bootstrap#1438] opened 2015-10-22 22:34 UTC
I am running in to a case where I am updating content inside a popover dynamically and the position of the popover ends up in the wrong place. I have put together a fiddle showing what I am experiencing.

https://jsfiddle.net/thetimbanks/L8yc6a3p/1/

I have dug through the code a little bit and it looks like the positioning of the popover is handled in the `updatePosition` method of the `Position` component. There are some checks to make sure to not try to reposition if the `placement` hasn't changed. In my case the placement hasn't changed, but the content has and therefor would need to be moved. Here is a proposed solution to the `updatePosition` method:

```javascript
updatePosition() {
    const target = this.getTargetSafe();

    if (!target) {
      this.setState({
        positionLeft: null,
        positionTop: null,
        arrowOffsetLeft: null,
        arrowOffsetTop: null
      });

      return;
    }    

    const overlay = ReactDOM.findDOMNode(this);
    const container = getContainer(this.props.container, ownerDocument(this).body);

    this.setState(calcOverlayPosition(
      this.props.placement,
      overlay,
      target,
      container,
      this.props.containerPadding
    ));
}
```

This gets rid of the `placementChanged` check and always updates the position as long as there is a target. Is the cost of calculating the position and setting a new position that costly?

I would be happy to throw together a PR for this if you would prefer to see it in action.

**Comment by taion** [comment] 2015-10-22 22:47
This has to be opt-in - the issue is that otherwise for whatever reason we end up with minor jitter in the popover positioning even when the popover itself is static.

**Comment by thetimbanks** [comment] 2015-10-23 16:23
@taion That makes sense. Would you see the setting as being a prop on the `Overlay/OverlayTrigger` components and then passed down through to the `Position` component similar to how the `placement` prop is handled?

**Comment by taion** [comment] 2015-10-23 16:26
Exactly so.

**Comment by taion** [comment] 2015-12-24 01:35
Closed by https://github.com/react-bootstrap/react-overlays/pull/42.

**Closed by taion** 2015-12-24 01:35 UTC
