### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bool' of undefined.

### ISSUE THREAD

**Issue by ycbayrak** [react-bootstrap/react-bootstrap#2883] opened 2017-11-16 21:40 UTC
I'm getting this error on runtime.

> Uncaught TypeError: Cannot read property 'bool' of undefined
    at Object.defineProperty.value (home.bundle.js:26353)
    at __webpack_require__ (home.bundle.js:20)
    at Object.defineProperty.value (home.bundle.js:25996)
    at __webpack_require__ (home.bundle.js:20)
    at Object.<anonymous> (home.bundle.js:25687)
    at Object.exports.__esModule (home.bundle.js:25957)
    at __webpack_require__ (home.bundle.js:20)
    at Object.exports.__esModule (home.bundle.js:25583)
    at __webpack_require__ (home.bundle.js:20)
    at Object.exports.__esModule (home.bundle.js:23124)

> 

> 
This is my package.json;
```
  "dependencies": {
    "prop-types": "^15.6.0",
    "prop-types-extra": "^1.0.1",
    "react": "^16.1.1",
    "react-bootstrap": "^0.30.10",
    "react-dom": "^16.1.1",
    "react-motion": "^0.5.2",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "^3.0.2",
    "node-sass": "^4.6.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.0",
    "webpack": "^3.8.1"
  }
```
This is my webpack.config.js;
```
var path = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var extractPlugin = new ExtractTextPlugin({
   filename: '[name]/[name].bundle.css'
});

module.exports = {
   entry: {
      home: "./src/pages/home/Home.jsx"
   },
   output: {
      path: path.resolve('dist'),
      filename: '[name]/[name].bundle.js'
   },
   module: {
      loaders: [
         {
            test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/
         },
         {
            test: /\.jsx$/, loader: 'babel-loader', exclude: /node_modules/
         },
         {
            test: /\.scss$/,
            use: extractPlugin.extract({
               use: ['css-loader', 'sass-loader']
            })
         },
         {
            test: /\.sass$/,
            use: extractPlugin.extract({
               use: ['css-loader', 'sass-loader']
            })
         }
      ]
   },
   resolve: {
      extensions: ['.js', '.jsx']
   },
   plugins: [
      extractPlugin
   ]
};

```
This is my `.babelrc`;
```
{
  "presets": [
    "stage-0",
    "stage-1",
    "stage-3",
    "es2016",
    "react"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```

**Comment by taion** [comment] 2017-11-16 21:42
You don't have a repro, and you don't have anything that even indicates that this is an issue here, nor any way to trace further.

Closing as non-actionable.

**Closed by taion** 2017-11-16 21:42 UTC

**Comment by natashache** [comment] 2017-12-24 06:21
@ycbayrak Did you find a solution for this? I'm facing the same issue after upgrading to react v16.

**Comment by cclifford3** [comment] 2018-01-08 23:36
Same issue here

**Comment by henriquejensen** [comment] 2018-01-09 19:12
the same issue here after upgrading to React 16
`VM348 mainfb6d056a5a0885108304.js:72171 Uncaught TypeError: Cannot read property 'bool' of undefined
    at Object.defineProperty.value (Transition.js:259)
    at __webpack_require__ (bootstrap fb6d056a5a0885108304:659)
    at fn (bootstrap fb6d056a5a0885108304:85)
    at Object.<anonymous> (ReactPropTypesSecret.js:12)
    at __webpack_require__ (bootstrap fb6d056a5a0885108304:659)
    at fn (bootstrap fb6d056a5a0885108304:85)
    at Object.<anonymous> (_export.js:43)
    at __webpack_require__ (bootstrap fb6d056a5a0885108304:659)
    at fn (bootstrap fb6d056a5a0885108304:85)
    at Object.defineProperty.value (app.js:7)`

**Comment by henriquejensen** [comment] 2018-01-09 19:24
I solved my problem changing updating some depencies in my package.json
```
"react": "latest",
"react-dom": "latest",
"react-bootstrap": "latest",
"react-router-dom": "latest",
```

**Comment by sm1990** [comment] 2018-02-12 07:53
I set up the codebase and tried again. @henriquejensen 's solution worked. Thanks :)

**Comment by prasadbe** [comment] 2018-03-05 13:36
@henriquejensen what you mean codebase.could you please explain that

**Comment by IzaGz** [comment] 2018-07-11 14:33
@sm1990 yes pls explain , what codebase? how u fixed it?

**Comment by nidhigadhavi** [comment] 2018-10-06 06:31
same issue is occure for me as well.

**Comment by sm1990** [comment] 2018-10-06 10:54
Hi @nidhigadhavi , @IzaGz, @henriquejensen 

Sorry for the late reply.

Don't get confused with the word "codebase". It simply means my project :)

I got the errors while I was trying to upgrade the react version from 15.3.1 - 16.0.2.

I had a copy with 15.3.1 react version with me. I used it to re-setup the project.

1st I updated the webpack to 3.10.0 (which was the latest stable version back then).
Once the webpack version was updated I modified the webpack.config.js according to the latest standards.
(some rules were depreciated such as the way you declare loaders etc.) Check the webpack config guidelines to make sure that you're using the correct standards.

Then I did the react upgrade.
Gradually updating the react version from 15.3.1 - 16.0.2 allows
provides a better understanding of the depreciated code and new
features.

After updating to react version to 15.6.0

Build runs with 2 depreciation warnings for prop-types & create-react-class packages.

Install jscodeshift to automate the code modification which is necessary once you install the above.

Again gradually upgrade to react 16.0.0
make sure to update react-dom to 16.0.0 as well.

There will be some errors again once you try to build your project.

Update react-router to fix the error.

Rebuild the project.
you'll get that "Uncaught TypeError: Cannot read property 'bool' of undefined" error

```
npm update -g react@latest react-dom@latest react-bootstrap@latest
react-router-dom@latest --save

npm install react@latest react-dom@latest react-bootstrap@latest
react-router-dom@latest --save
```

The above commands will update those packages to their latest
stable versions and will fix the error.

If there are any unmet dependencies, you'll get warnings for those. You can install them and get rid of those warnings.

At the end of the upgrade, installed react versions were as below.
react => 16.2.0
react-dom => 16.2.0
React-router-dom => 4.2.2
React-bootstrap =>0.32.1

However there was an issue with latest react-bootstrap version about a month ago. It caused our project build to fail as well.
Check and make sure your react-bootstrap version has no issues.
Hope this helps :)

**Comment by pvn6396** [comment] 2019-02-17 06:41
https://www.npmjs.com/package/react-jsonschema-form-layout-2
I think the issue is fixed in this package.

**Comment by bilal-rao** [comment] 2019-03-10 11:15
Hi @sm1990 i changed my package.json as suggest you , but still it is not works for me if you found any work around regarding to fixing the bool of undefined issues so share with me too. i appreciate your cooperation. Thanks

**Comment by charlbarrera** [comment] 2019-04-03 21:11
@bilal-rao  Do you have news about it?, I have the same issue, and I tried the solution of @sm1990 and @henriquejensen  without success.
