### ISSUE TITLE
Add option to collapse Navbar when item is selected

### ISSUE THREAD

**Issue by JCzz** [react-bootstrap/react-bootstrap#1301] opened 2015-09-08 08:57 UTC
How do you make the menu collapse after item is selected?

    import React from 'react';
    import {Navbar, Nav, NavItem, NavDropdown, DropdownButton, MenuItem, CollapsibleNav} from 'react-bootstrap';

    export default class App extends React.Component {

    constructor(props) {
      super(props);
      this.onSelect = this.onSelect.bind(this);
      this.toggleNav = this.toggleNav.bind(this);
      // this.state = {navExpanded: false};
    }

    onSelect(e){
        console.log('OnSelect')
        // console.log(this.state.navExpanded);
        // this.setState({navExpanded: false});
    }

    toggleNav(){console.log('toggle...')};

    // <Navbar inverse fixedTop toggleNavKey={0} navExpanded={this.state.navExpanded} onToggle={() => this.toggleNav()}>
    // <Navbar inverse fixedTop toggleNavKey={0} navExpanded={this.state.navExpanded} >

    render() {
        return (

          <Navbar inverse fixedTop toggleNavKey={0} >
            <Nav right eventKey={0} onSelect={this.onSelect} > {/* This is the eventKey referenced */}
              <NavItem eventKey={1} href="#">Link</NavItem>
              <NavItem eventKey={2} href="#">Link</NavItem>
            </Nav>
          </Navbar>     

      )

    }

    componentDidMount() {

    }
    }

    React.render(<App />, document.getElementById('example'));

**Comment by mtscout6** [comment] 2015-09-09 13:20
I have confirmed that this bug exists in our docs example.

![screen shot 2015-09-09 at 7 17 53 am](https://cloud.githubusercontent.com/assets/736870/9762838/35e92f10-56c3-11e5-80f7-99f3a2cae52c.png)

![screen shot 2015-09-09 at 7 18 01 am](https://cloud.githubusercontent.com/assets/736870/9762840/372e5936-56c3-11e5-8e5d-90faf3b50096.png)

Clicking on any of those NavItems does not collapse the Nav.

**Comment by mtscout6** [comment] 2015-09-09 13:21
@JCzz If you're up to tackling the bug we'd appreciate a pull request to fix the issue.

**Comment by JCzz** [comment] 2015-09-09 13:38
Cool, what branch?

**Comment by mtscout6** [comment] 2015-09-09 13:40
It's a bug fix so submit the PR against master.

**Comment by jquense** [comment] 2015-09-09 14:38
I might be misunderstanding but I don't think that's a bug, unless we are doing something different than upstream bootstrap, which also doesn't collapse when you select anything from a navbar, how would you handle inputs or buttons?

**Comment by taion** [comment] 2015-09-09 15:39
Oh. That's tough. Do we need a few feature for this then? I think you almost always want to collapse the nav hamburger when you're clicking on an actual link.

**Comment by mtscout6** [comment] 2015-09-09 17:02
I'd agree with @taion with this. Even if it's not done in upstream Bootstrap I think this is a desired feature. May be worth it to be behind a flag so people can opt out of that if they wish.

**Comment by jquense** [comment] 2015-09-09 17:20
maybe make the collapse part controllable? I don't mind enhancing bootstrap here but changing the default behavior for something like this seems like an overstep to me....I'd prefer opt in for the new behavior. I am willing to admit that we may be the exception to this, but we definitely don't want it to collapse on select in most cases.

**Comment by taion** [comment] 2015-09-09 17:37
It makes sense to me for this to be non-default given upstream behavior. We just need to make sure we have a callout in the docs, because most people will want the non-default behavior.

**Comment by JCzz** [comment] 2015-09-14 08:45
Sorry, I am unable to fix this. Hope someone else is up for it.

**Comment by barrystaes** [comment] 2015-09-15 12:36
Another example is the `CollabsibleNav` which is unusable due to this. A user clicks on a page -and it loads- but the menu does not collapse. Whats in a name eh?

**Comment by jquense** [comment] 2015-09-15 13:00
@barrystaes its not a bug, its the correct behavior of bootstrap navbars, we welcome an opt-in "fix" if ya are willing to put a PR together :)

**Comment by barrystaes** [comment] 2015-09-15 13:25
With all respect: if i could i would, and i tried.

Regarding labeling a bug or not, i understand in case of `<Dropdown>` its not, but for `<CollapsibleNav>` i do regard this a bug. In React navigation is not done by reloading the page: i believe the nav menu has to collapse after use.

I haven't found a workaround (that does not involve jquery) that works for my case https://github.com/react-bootstrap/react-bootstrap/issues/934

**Comment by taion** [comment] 2015-09-15 15:42
If you're unwilling or unable the contribute a patch to fix the issue, then you'll have to wait patiently for someone with the time and ability to actually do so. Aggravating all the contributors by complaining is not going to help your cause, especially when this just matches the upstream behavior and is not in fact a bug.

**Comment by barrystaes** [comment] 2015-09-16 08:50
You say i should collapse `collapsiblenav` manually, but how? I still want to contribute to a fix, and insights are welcome.

**Comment by rainyear** [comment] 2015-09-18 09:50
@barrystaes add "in" to `CollapsibleNav`'s className manually and it collapsed

**Comment by barrystaes** [comment] 2015-09-21 12:03
@rainyear thanks, i see that works using Chrome inspector. I'll try to make the react-router-bootstrap `MenuItemLink` do that workaround..

**Comment by lefant** [comment] 2015-10-26 17:33
this works for me to always hide the menu in case it helps someone:
https://github.com/lefant/react-bootstrap/commit/4c47a2ffcb

unfortunately also hides the menu if trying to open a nested NavDropdown. I'll keep looking into it to improve it further.

**Comment by taion** [comment] 2015-10-26 19:47
That's good progress.

You probably want to handle this via something like `onSelect`, maybe via parent context.

**Comment by barrystaes** [comment] 2015-10-27 10:31
We currently use @jchapple suggestion at https://github.com/react-bootstrap/react-router-bootstrap/issues/112#issuecomment-142599003

**Comment by lefant** [comment] 2016-02-23 18:29
I have taken another stab at this working against the current Navbar.Collapse.

https://github.com/lefant/react-bootstrap/commit/c68b46baea

maybe should have some kind of prop to opt into this behavior. also one might not want to pass on the onSelect to non-Navbar.Collapse children from Navbar, but it works for me and I was not sure how to do that best.

**Comment by olalonde** [comment] 2016-03-08 17:50
@lefant can you submit a PR? Also need to get this fixed :(

**Comment by pxpeterxu** [comment] 2016-10-04 02:41
I've managed to get a workaround working for this by using a controlled Navbar. Not the best, but probably the easiest until we have full support!

```javascript
setNavExpanded: function(expanded) {
  this.setState({ navExpanded: expanded });
},
closeNav: function() {
  this.setState({ navExpanded: false });
}
```

In render:
```javascript
<Navbar inverse={true}
        onToggle={this.setNavExpanded}
        expanded={this.state.navExpanded}>
  <Navbar.Header><Navbar.Toggle /></Navbar.Header>
  <Navbar.Collapse>
    <Nav onSelect={this.closeNav}>
      <NavItem href="#">Blah</NavItem>
      <NavItem href="#">Blah</NavItem>
    </Nav>
  </Navbar.Collapse>
</Navbar>
```

**Comment by olalonde** [comment] 2016-10-05 01:10
@pxpeterxu I also ended up doing that

**Comment by kevr** [comment] 2016-10-14 23:57
I ended up just simulating another click to close the navigation collapse, and I did it onEnter, though there's probably a better bind for this function.

```
const collapseNav = (nextState) => {
  var nav = $("nav");
  if(nav.find(".collapse").hasClass("in")) {
    nav.find(".navbar-toggle").click();
  }
}

...
<Route path="somePath" component={SomeComponent} onEnter={collapseNav} />
...
```

Hope this helps somebody.

**Comment by alemanuel** [comment] 2016-10-19 15:53
**Problem:** Data toggle not being triggered in mobile view after clicking in a menu item inside a link container.

**My Solution:**
Since I use JQuery for another API, I'm toggling the dropdown with it:

**Code:**
closeNavDropdown() {
    $('.navbar').find(".navbar-toggle").click();
  }
  <Nav onSelect={this.closeNavDropdown}>
            <NavDropdown eventKey={1} title="New" id="dropdown1">
            ... more code ...
</Nav>

**Comment by taion** [comment] 2016-10-27 21:25
Closed by https://github.com/react-bootstrap/react-bootstrap/pull/2280

**Closed by taion** 2016-10-27 21:25 UTC
Labels: enhancement, help wanted
