### ISSUE TITLE
missing `backdrop` attribute on `ModalProps` when using typescript

### ISSUE THREAD

**Issue by achmadk** [react-bootstrap/react-bootstrap#5732] opened 2021-03-22 10:43 UTC
## Describe the bug

I am using react-bootstrap with typescript. I want to prevent modal component from being clicked outside its own element, so I just set `backdrop` props value into `static`. Unfortunately, `backdrop` wasn't show when using vscode intellisense. 

## To Reproduce

1. Import `ModalProps` from `react-bootstrap`
2. create dummy type variable called `test`
3. assign `test` variable into `ModalProps['backdrop']`
4. When `test` variable is hovered, its type is `boolean | "static"`, but `any` is shown.

## Reproducible Example

https://codesandbox.io/s/busy-mirzakhani-1ly1w?file=/src/App.tsx.

## Expected behavior

backdrop props type is boolean | 'static' | undefined
```ts
  backdrop?: boolean | 'static'
```

## Screenshots

![Screenshot from 2021-03-22 17-29-49](https://user-images.githubusercontent.com/8057028/111977856-d18ae380-8b35-11eb-94ed-f78aaa40094d.png)

## Environment (please complete the following information)

- Operating System: ubuntu
- Browser, Version: Chrome 89
- React-Bootstrap Version: 1.5.2

**Comment by kyletsang** [comment] 2021-03-23 17:33
Looks like `Omit` doesn't play nice with index signatures.  We could use a `Pick` here and redefine the index signature in RB `ModalProps`?  Unsure if there's a cleaner way.

**Comment by golota60** [comment] 2021-06-18 21:30
@kyletsang  I got around to fixing it by using `Pick`, but an idea came to my mind, but I'd like to get it confirmed before implementing, cause it would require changes in `react-overlays`. 

So, in `react-overlays`, instead of having `ModalProps` we could split them like so:
```js

interface IndexSignature { [other: string]: any};

export interface ModalPropsWithoutIndexSignature {
    children?: React.ReactElement;
    role?: string;
    style?: React.CSSProperties;
    className?: string;
    show?: boolean;
    container?: DOMContainer;
    onShow?: () => void;
    onHide?: () => void;
    manager?: ModalManager;
    backdrop?: true | false | 'static';
    renderDialog?: (props: RenderModalDialogProps) => React.ReactNode;
    renderBackdrop?: (props: RenderModalBackdropProps) => React.ReactNode;
    onEscapeKeyDown?: (e: KeyboardEvent) => void;
    onBackdropClick?: (e: React.SyntheticEvent) => void;
    containerClassName?: string;
    keyboard?: boolean;
    transition?: ModalTransitionComponent;
    backdropTransition?: ModalTransitionComponent;
    autoFocus?: boolean;
    enforceFocus?: boolean;
    restoreFocus?: boolean;
    restoreFocusOptions?: {
        preventScroll: boolean;
    };
}

export type ModalProps = ModalPropsWithoutIndexSignature & IndexSignature;
```

Doing that would allow us to import `ModalPropsWithoutIndexSignature as BaseModalProps` instead of `ModalProps as BaseModalProps`, and then, in `react-bootstrap` we would just re-apply the index signature like so

```js

export interface ModalProps
  extends Omit<
    BaseModalProps,
    | 'role'
    | 'renderBackdrop'
    | 'renderDialog'
    | 'transition'
    | 'backdropTransition'
  > {
  size?: 'sm' | 'lg' | 'xl';
  fullscreen?:
    | true
    | 'sm-down'
    | 'md-down'
    | 'lg-down'
    | 'xl-down'
    | 'xxl-down';
  bsPrefix?: string;
  centered?: boolean;
  backdropClassName?: string;
  animation?: boolean;
  dialogClassName?: string;
  contentClassName?: string;
  dialogAs?: React.ElementType;
  scrollable?: boolean;
  [other: string]: any;
}
```

I think this way of handling it would be better - if `ModalProps` in `react-overlays` ever change, when using `Pick` we would need to update that, but if we apply the suggested solution it would take care of itself

**Comment by kyletsang** [comment] 2021-06-19 00:20
@golota60 yeah, I think fixing it in `react-overlays`/`@restart/ui` is the better option.  `Pick` was just a quick fix 😛

**Comment by golota60** [comment] 2021-06-22 18:54
Once both of those ^^ are reviewed & merged I'll make a PR that re-attaches index signatures

**Comment by golota60** [comment] 2021-06-23 22:45
might also need a release of `react-overlays` 🙏 no rush though

**Closed** 2021-07-13 00:09 UTC
Labels: bug, help wanted, types
