### ISSUE TITLE
Dynamically added Panels wont open

### ISSUE THREAD

**Issue by GiraffeCoding** [react-bootstrap/react-bootstrap#3300] opened 2018-10-03 15:33 UTC
Hi,
I'm trying to add Panels to a PanelGroup after the initial page has loaded. These are being loaded in via a map function and display as expected when a new instance is added to the array.

However when I click on the header which is set to be the 'toggle' attribute it doesn't do anything.

I've checked against the debug tools and the click event handlers are assigned but it just doesn't open the newly added panel.

Has anyone come across this behavior before? 

```
<PanelGroup accordion id="accordion-uncontrolled-example" defaultActiveKey="0">
{map(sections, (section, index) => <Panel key={index} eventKey={index}>
       <Panel.Heading>
               <Panel.Title toggle>Header</Panel.Title>
        </Panel.Heading>
         <Panel.Body collapsible>
                Content here
         </Panel.Body>
 </Panel>;
</PanelGroup>
```

**Comment by anonymous17** [comment] 2018-10-25 18:52
Having same issue, do any one has the solution to it ?

**Comment by CarlosBalladares** [comment] 2018-12-16 07:36
Hi I was not able to replicate the issue. Is it possible to provide more context?

<img width="717" alt="screen shot 2018-12-02 at 12 14 13 am" src="https://user-images.githubusercontent.com/14811752/50051151-3ba4ba80-00db-11e9-90af-95db2e8fb854.png">

The tabs worked fine this is my component.

```
import React from "react";
import Panel from "react-bootstrap/lib/Panel";
import PanelGroup from "react-bootstrap/lib/PanelGroup";

class PanelComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      names: ["hello", "world", "boot"]
    };

    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    this.setState({
      names: [...this.state.names, "f"]
    });
  }

  render() {
    const { names } = this.state;
    return (
      <PanelGroup
        accordion
        id="accordion-uncontrolled-example"
        defaultActiveKey="0"
        // onClick={this.handleClick}
      >
        {names.map((name, index) => (
          <Panel key={index} eventKey={index}>
            <Panel.Heading>
              <Panel.Title toggle>{name}</Panel.Title>
            </Panel.Heading>
            <Panel.Body collapsible>Content for {name}</Panel.Body>
          </Panel>
        ))}
      </PanelGroup>
    );
  }
}

export default PanelComponent;


```

**Comment by CarlosBalladares** [comment] 2018-12-16 07:37
I was not able to replicate the issue is it possible to provide more context?

<img width="1196" alt="screen shot 2018-12-16 at 2 33 46 am" src="https://user-images.githubusercontent.com/14811752/50051166-74dd2a80-00db-11e9-9bcb-117b02ef9376.png">

I used this code

```javascript
import React from "react";
import Panel from "react-bootstrap/lib/Panel";
import PanelGroup from "react-bootstrap/lib/PanelGroup";

class PanelComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      names: ["hello", "world", "boot"]
    };

    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    this.setState({
      names: [...this.state.names, "f"]
    });
  }

  render() {
    const { names } = this.state;
    return (
      <PanelGroup
        accordion
        id="accordion-uncontrolled-example"
        defaultActiveKey="0"
        // onClick={this.handleClick}
      >
        {names.map((name, index) => (
          <Panel key={index} eventKey={index}>
            <Panel.Heading>
              <Panel.Title toggle>{name}</Panel.Title>
            </Panel.Heading>
            <Panel.Body collapsible>Content for {name}</Panel.Body>
          </Panel>
        ))}
      </PanelGroup>
    );
  }
}

export default PanelComponent;

```

**Comment by kosmiq** [comment] 2020-03-11 10:16
Closing since no feedback has been given for a long time.

**Closed by kosmiq** 2020-03-11 10:16 UTC
Labels: Bootstrap 3, bug
