### ISSUE TITLE
Tooltip/Overlay generates findDOMNode is deprecated in StrictMode warning.

### ISSUE THREAD

**Issue by johnsetzer** [react-bootstrap/react-bootstrap#6149] opened 2021-12-13 19:34 UTC
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The code works, but it throws warnings in the browser console and will presumably break if a future version of React drops support for its deprecated behavior in a future version.

The following line of code needs to be updated to use refs instead of `ReactDOM.findDOMNode(componentOrElement);`
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/safeFindDOMNode.ts#L7

### Expected behavior

The code works as but does not throw warnings.

### To Reproduce

Here is a project that demonstrates the issue.
Follow the instructions on the README.
https://github.com/johnsetzer/find-dom-node-bug/blob/master/README.md

### Reproducible Example

Here is a project that demonstrates the issue.
Follow the instructions on the README.
https://github.com/johnsetzer/find-dom-node-bug/blob/master/README.md

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

1.6.4

### What version of Bootstrap are you using?

4.6.0

**Comment by kyletsang** [comment] 2021-12-13 21:13
Dupe of #5075.  This is fixed in v2 for bootstrap 5

**Closed by kyletsang** 2021-12-13 21:13 UTC
Labels: bug

**Comment by johnsetzer** [comment] 2021-12-20 19:51
Is there any plan to copy the fix to version 1.X?

**Comment by kyletsang** [comment] 2021-12-20 23:25
No plans to backport this.  There were some breaking changes involved in getting full strict mode support.  In your case, since you're using an overlay you might be able to get around the warning by following this:

https://react-bootstrap-v4.netlify.app/components/overlays/#customizing-trigger-behavior
