### ISSUE TITLE
'rootClose' attribute of 'OverlayTrigger' doesn't work on iOS Safari

### ISSUE THREAD

**Issue by jniederm** [react-bootstrap/react-bootstrap#2869] opened 2017-11-01 19:46 UTC
Code like this:

```
<OverlayTrigger trigger="click" rootClose ...
```

([official demo][1]) leaves popup opened when clicking aside of OverlayTrigger children on iOS Safari.

Applies to versions: 0.31.2, 0.31.2

[1]: https://react-bootstrap.github.io/components.html#popovers-trigger-behaviors

**Comment by taion** [comment] 2017-11-08 20:24
This is a dupe of https://github.com/react-bootstrap/react-overlays/issues/158

**Closed by taion** 2017-11-08 20:24 UTC
