### ISSUE TITLE
Compiler warning for esm builds in Webpack + Typescript

### ISSUE THREAD

**Issue by anandthanvi007** [react-bootstrap/react-bootstrap#5311] opened 2020-07-18 12:08 UTC
webpack : 4.43.0
typescript: 3.9.6
react-bootstrap : 1.1.0

This warning is coming for all componets please help
```
WARNING in ./node_modules/react-bootstrap/esm/index.js 3:0-91
"export 'AccordionCollapseProps' was not found in './AccordionCollapse'
 @ ./src/screens/index.tsx
 @ ./src/index.tsx
 @ multi @babel/polyfill ./src/index.tsx ./src/assets/sass/style.scss
```
webpack config 
  ```
module: {
    rules: [
      {
        test: /\.mjs$/,
        exclude: /node_modules/,
        loader: "babel-loader",
      },
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
					  loader: MiniCssExtractPlugin.loader,
					  options: {
              hmr: process.env.NODE_ENV === 'development',
					  },
          },
          'css-loader',
          'sass-loader'
				  ],
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        include: [
				  `${SRC_DIR}/assets/images/`,
        ],
        use: [
				  {
            loader: 'file-loader',
            options: {
					  name: '[name].[ext]',
					  outputPath: 'assets/images/',
					  publicPath: '../images/',
            },
				  },
        ],
			  },
			  {
        test: /\.(svg|woff|woff2|ttf|eot|otf)([\?]?.*)$/,
        include: [
          `${SRC_DIR}/assets/fonts/`,
				  ],
        use: [{
          loader: 'file-loader',
          options: {
					  name: '[name].[ext]',
					  outputPath: 'assets/css/fonts/',
					  publicPath: 'fonts/',
          },
				  }],
		   },
    ],
  },
```

**Comment by kyletsang** [comment] 2020-07-20 17:37
Dupe of #5267.

This is fixed in the latest release 1.2.2

**Closed by kyletsang** 2020-07-20 17:37 UTC
