### ISSUE TITLE
Fix arbitrary prop passthrough to DOM nodes.

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1994] opened 2016-06-30 12:04 UTC
@jimfb and @gaearon were kinda enough to reach out and warn us that RB will have a lot of warnings in React v15.2.0, of which, a release is imminent.

The problem is that in preparation for removing the DOM attribute whitelist, React has started to warn when props that are _not_ DOM attributes are passed through to DOM nodes. This (AFAIK) to help for folks to clean up code before those attributes are suddenly applied to the DOM nodes in a later version when the whitelist is removed.

@react-bootstrap/collaborators If anyone has time to start talking this in part (or whole) this might be less of a chore if a bunch of folks work on it. We also need to decide what the best way to ensure that we do not break existing API's by being too restrictive in what we pass through.

### Concerns

I'm not sure if any of these cases exist (here) but I am concerned about API's that require carte-blanche passthrough of props to a child that may or may not a DOM node. Presumably in those cases we can either defer to the User to use a component, or make sure to remove "own" props before passing through.

This also effectively means that API's like `dropdown` which allow for using the throwaway `bsRole` prop to indicate _type_ to the parent no longer work for DOM nodes. That sort of sucks, that was a really great side-effect feature of that API.

**Comment by jquense** [comment] 2016-06-30 12:05
as an aside this will also break, a common (for me) testing pattern of using throwaway props as selector targets `<div _testID='foo' />` and `find([_testID='foo').assert()`

**Comment by mxstbr** [comment] 2016-06-30 12:47
Is the problem with carte Blanche something we should fix on our side?

**Comment by gaearon** [comment] 2016-06-30 12:50
For more context, you can reproduce the warnings by:

1. Cloning this repo, running npm install and running the docs website (see instructions in docs folder)
2. Installing react and react-dom 15.2.0-rc.1
3. Opening "Components" page

You will see many warnings in console and you can start fixing them. If you work on this make sure to comment here so others don't do duplicate work. You may comment about particular 5 components you're taking to split the work more efficiently.

**Comment by jquense** [comment] 2016-06-30 12:53
hah in this case I was just using the phrase (albeit with somewhat liberal license with its actual meaning :p) 

I have been playing with Carter Blanche the proper now recently and it's :+1:

**Comment by mxstbr** [comment] 2016-06-30 12:55
Ah now that sentence makes more sense :grin: I guess that's what we get for choosing that name…

Glad to hear!

**Comment by moaazsidat** [comment] 2016-06-30 13:32
Hey folks, would love to help out fixing this. Going to get react-bootstrap set up later tonight/tomorrow, and will post  updates here about which components I'm working on, once I get to a point where I can start fixing the warnings 😀 

Cheers!

**Comment by taltk9** [comment] 2016-06-30 14:23
Actually I didn't understand the issue. For example: `Warning: Failed propType: The prop 'id' is required to make 'Popover' accessible for users using assistive technologies such as screen readers Check the render method of 'Example'`. I could define a default prop Id or simply put a id prop at example page. If it is the fix you are searching for, I can send a PR right now. 😄

**Comment by jquense** [comment] 2016-06-30 14:36
@taltk9 thats not what this issue is about. Those warnings are from react-bootstrap and intentional/correct. this is about a change in react v15.2 that warns when you pass a prop to a DOM node that isn't a valid html attribute.

**Comment by taltk9** [comment] 2016-06-30 14:48
Ohh ok @jquense, thanks! I will see better and try help. Sorry about wrong understanding.

**Comment by gaearon** [comment] 2016-06-30 15:06
These are the warnings in question:

![](https://cloud.githubusercontent.com/assets/810438/16473610/a5f6df06-3e66-11e6-964c-be482fdfeb27.png)

See https://github.com/facebook/react/pull/6800 for some more context.

**Comment by taion** [comment] 2016-06-30 15:07
Wait, how are library component authors supposed to fix this? Are we supposed to apply the whitelist ourselves?

Like, suppose I had:

```js
function MyDiv(props) {
  return <div {...props} />;
}
```

If one of my users does

```js
<MyDiv _testId={3} />
```

They're going to get warnings pointing at `<MyDiv>`; if this component is deeply nested, that component stack may not even point to the original use.

**Comment by jquense** [comment] 2016-06-30 15:19
@taion I think we just can't do: `<MyDiv _testId={3} />` anymore. In most cases though MyDiv should only pass through props less the ones it specifies, in which case its up to the user of MyDiv to to not pass props it doesn't know about...

I am concerned for cases where A component passes through none-html attributes for the sake of Composite components, but children could just as easily be DOM nodes. `<Position>` is a good example, it passes `arrowOffsetTop` and also `style` for a `div` that used to just work, now every child of Position will have to be a composite component to filter out the none html attributes which does suck.

We could presumable check if the type of the children is a string but yeah, thats applying a whitelist ourselves...

**Comment by taion** [comment] 2016-06-30 15:24
We'd just use `data-testId` instead.

For the sake of informative error messages if you have deep stacks of components with prop passthrough, it would be nice to have a way to emit the warning ourselves.

**Comment by jquense** [comment] 2016-06-30 15:26
> We'd just use data-testId instead.

sure, just noting that we longer can use props with the intent to never actually "render" them, a la `bsRole`

**Comment by gaearon** [comment] 2016-06-30 15:43
>Wait, how are library component authors supposed to fix this? Are we supposed to apply the whitelist ourselves?

If you are passing `props` through, you are only supposed to remove the props you *know* should not be passed down. Here’s an example example.

### Bad

```js
function MyDiv(props) {
  if (props.layout === 'horizontal') {
    // BAD! Because you know for sure "layout" is not a prop that <div> understands.
    return <div {...props} style={getHorizontalStyle()} />
  } else {
    // BAD! Because you know for sure "layout" is not a prop that <div> understands.
    return <div {...props} style={getVerticalStyle()} />
  }
}
```

### Good

```js
function MyDiv(props) {
  const { layout, ...rest } = props
  if (layout === 'horizontal') {
    return <div {...rest} style={getHorizontalStyle()} />
  } else {
    return <div {...rest} style={getVerticalStyle()} />
  }
}
```

Sure, it is still possible that the user might pass some additional non-existing props to `MyDiv`—but then it is **their** fault and they are in full control to remove these props (since neither `MyDiv` nor `div` understand them).

**Comment by gaearon** [comment] 2016-06-30 15:55
>They're going to get warnings pointing at <MyDiv>; if this component is deeply nested, that component stack may not even point to the original use.

There is no stack length restriction where the warning gets generated. I think `Overlay` is at the bottom because it is top-level component, not because we’re display top N entries.

Ideally we should probably cross parent tree boundaries in the stack trace as well, so `renderSubtreeInContainer` gets a better trace.

**Comment by jquense** [comment] 2016-06-30 16:04
> Ideally we should probably cross parent tree boundaries in the stack trace as well, so renderSubtreeInContainer gets a better trace.

some day I will have enough time to try and PR a better subtree concept :P

**Comment by timdorr** [comment] 2016-06-30 16:05
First, is there a @facebook/react issue open for this change? Didn't see anything obvious, but there are a lot of issues to search through over there 😄 

What about `data-*` attributes? For some, I may want to use an attribute selector in my CSS or when searching DOM nodes. The data attributes on DOM nodes were a spec-compliant (last I checked) way of doing that.

**Comment by jquense** [comment] 2016-06-30 16:08
@timdorr `data-*` are still fine, the issue here is that in _some_ cases we are **intentionally** leaning on the behavior to not push invalid html attributes to DOM nodes.

**Comment by timdorr** [comment] 2016-06-30 16:21
Yeah, it looks like the wholesale usage of `{...this.props}` is problematic. It makes working with things like `getClassSet` harder, because you can't just mutate the props object and call it a day (that would be problematic code regardless).

Maybe add a `removeBsProps()` (taking advantage of the project name for a humorous function name) that filters out any known props that you normally use in functions like `getClassSet`. Then you could use this pattern:
```js
const { children, otherThing, ...props } = removeBsProps(this.props)
return <div {...props}>{children}</div>
```

**Comment by gaearon** [comment] 2016-06-30 17:35
>First, is there a @facebook/react issue open for this change? 

Yes, I linked to it in https://github.com/react-bootstrap/react-bootstrap/issues/1994#issuecomment-229687624.
Here it is: https://github.com/facebook/react/pull/6800.

**Comment by kevinludwig** [comment] 2016-07-01 19:40
Well, that was fast:

> zpao zpao published 47 minutes ago
> 15.2.0 is the latest of 79 releases

**Comment by pointnet** [comment] 2016-07-02 22:02
#2001

**Comment by pgilad** [comment] 2016-07-03 12:37
How should components with `componentClass` be handled with passing props? It's unclear how to handle those cases. One can potentially want custom props such as `bsStyle` if he's passing a customClass

**Comment by alfredoreduarte** [comment] 2016-07-05 00:55
In case any of you want to silence these warnings for the time being, you can do so by filtering them out using a regex with chrome's console.

The regex I'm using is `^((?!Unknown props).)+$`

![screen shot 2016-07-04 at 8 52 35 pm](https://cloud.githubusercontent.com/assets/4633753/16571402/65d60372-4229-11e6-836f-43c98bd33080.png)

**Comment by jakimber** [comment] 2016-07-06 03:46
@alfredoreduarte Thanks for the regex, it set me on the path of hiding things whilst waiting for another way.

Just in case others find the issue too, i tweaked the regex to `^(?!.*?Unknown prop)` as this worked for my setup whereas yours filtered out even the ones i was interesting in seeing for some reason i don't have time to work out right now.  Hope it helps!

**Comment by taion** [comment] 2016-07-14 23:59
Fixed in #2026, #2036, and #2044.

We'll cut a release after we merge #2052.

**Closed by taion** 2016-07-14 23:59 UTC
Labels: help wanted, question

**Comment by austb25** [comment] 2016-07-20 17:05
@taion has the new release been cut?

**Comment by taion** [comment] 2016-07-21 04:27
Released as v0.30.0-rc.1. This is actually tagged `latest` instead of `next` on npm, and we've updated the docs site to show this version as well.

Please test it out and let us know how it goes.

**Comment by rloomans** [comment] 2016-07-21 04:56
Looks good to me so far. 

This RC seems to make the app noticeably faster to render.

**Comment by ottoo** [comment] 2016-07-21 06:12
Updated to the RC and don't see these unknown props anymore 👍

**Comment by leolicai** [comment] 2016-07-21 06:57
Is somebody can give a simple fix way?
I use react-bootstrap version 0.30.0rc-1 and react 0.15.2.1 
Just use a panel component. 
this is a warning 
Warning: Unknown props `header`

Who can help me ?
Thanks!

Is the react-bootstrap can use in production for now?

**Comment by rloomans** [comment] 2016-07-21 07:04
I have one remaining unknown props warning and it's from react-router-bootstrap complaining about the active attribute on an <a> element.

Are you going to do similar work in that module?

**Comment by barbalex** [comment] 2016-07-21 14:20
works for me, thanks

**Comment by barbalex** [comment] 2016-07-21 14:40
in another project I keep getting one warning:

    warning.js?8a56:44Warning: Unknown props `bsStyle`, `headerRole`, `panelRole`, `collapsible`, `expanded` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop in div (created by Actors)

**Comment by taion** [comment] 2016-07-21 14:45
Read the error message. "Actors" is not a React-Bootstrap component.

**Comment by barbalex** [comment] 2016-07-21 14:53
"Actors" is the displayName of a component that is basically a PanelGroup, see here: https://github.com/barbalex/bb/blob/master/src/components/actors/actors.js

The props mentioned in the error message are not added by the code in this module.

**Comment by taion** [comment] 2016-07-21 14:56
It's happening because you're rendering a `<div>` under an accordion panel group. Those components must be able to accept panel styling props.

**Comment by barbalex** [comment] 2016-07-21 14:59
Thanks!

Am 21.07.2016 4:56 nachm. schrieb "Jimmy Jia" <notifications@github.com>:

**Comment by medanat** [comment] 2016-07-21 18:48
Hey, still getting `Warning: Unknown props `bsRole`, `bsClass` on <button> tag. Remove these props from the element` for `Dropdown` component.

**Comment by tangent-tan** [comment] 2016-07-25 07:48
Updated to rc version and no more unknown props. Thanks.

**Comment by Siyfion** [comment] 2016-07-25 15:25
Awesome work @taion and others... Worked like a charm! 👍

**Comment by gary-menzel** [comment] 2016-07-26 13:34
I've just upgraded to 0.30.0 and there are still issues in SafeAnchor (at least when called from MenuItem - so it may be in MenuItem):
Unknown props `activeKey`, `activeHref` on <a> tag.

**Comment by Jaikant** [comment] 2016-07-26 13:50
Just upgraded to 0.30.0 and the warnings are a lot fewer. Great stuff. I still get the following warnings. 
Unknown props `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop'  possibly in Position/Transition/Fade/Overlay.
Unknown props `bsStyle`, `headerRole`, `panelRole`, `collapsible`, `expanded`
possibly in Accordion/PanelGroup/Grid

**Comment by brian-kellerheikkila** [comment] 2016-07-26 14:25
After upgrading to 0.30.0, this warning still appears: Unknown prop `nav` on <ul> tag.

**Comment by jquense** [comment] 2016-07-26 14:29
Ya'll The upgrade won't fix all of these errors in your app, you still have to not pass through props where appropriate or where you control the components. Please read your stack traces and see which components are actually adding the bad props and see if you own them. Please don't assume that because the bottom component in the stack is a Bootstrap component that it's injecting them.

@gary-menzel : you error looks like your component `RightNav` is spreading all it's props to MenuItems it creates

@brian-kellerheikkila: `nav` isn't a bootstrap prop so that's unlikely coming from a bootstrap component

**Comment by brian-kellerheikkila** [comment] 2016-07-26 14:57
Ok, you're correct. Ignore my previous comment.

**Comment by gary-menzel** [comment] 2016-07-27 12:51
I am reasonably new to react-bootstrap (but not to development).  I cannot find either "activeKey" or "activeHref" in any of my code at all.  Also, I am creating <MenuItem> with hard-coded tags and not passing ...props at all anywhere (my needs are fairly simple).  So, at this point, I have no idea how RightNav would be spreading it's properties to all the <MenuItem>s.  I'm not doing any lazy propagation.

**Comment by agilgur5** [comment] 2016-07-27 21:28
I seem to be getting an error with v30 for the  `onTouchTap` prop on `Sidebar`, which is a prop I don't currently even use in my own code:
```
warning.js?8a56**:44Warning: Unknown prop `onTouchTap` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Sidebar)
    in div (created by Sidebar)
    in Sidebar (created by MainNavSide)
    in MainNavSide
```

as well as on the `Alert`'s `bsStyle` prop, that I do use:
```
warning.js:44Warning: Unknown prop `bsStye` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Alert)
    in Alert (created by ConversationView)
    in div (created by ConversationView)
    in ConversationView
```

**Comment by jquense** [comment] 2016-07-27 21:38
@agilgur5 SideBar isn't a bootstrap component

**Comment by austb25** [comment] 2016-07-27 21:39
You have bsStye it should be bsStyle

•••
Austin S. Bloom

**Comment by agilgur5** [comment] 2016-07-27 21:50
@jquense my bad, remembered I had a single non-bootstrap element imported 😫 
thanks for catching my spelling error @austb25! didn't catch that as the default is `info` >.>

**Comment by kimmajor** [comment] 2016-07-28 21:33
I get the following in v0.30 and react 15.2.1

warning.js:44Warning: Unknown props `active`, `activeKey`, `activeHref` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by xyz)
    in ul (created by Nav)

**Comment by lo1tuma** [comment] 2016-07-29 15:57
I have the same problem as @Jaikant with react-bootstrap 0.30.0.
@jquense I don’t think this is related to the use of custom overlays. If you take a look at e.g. [the `Position` component](https://github.com/react-bootstrap/react-overlays/blob/796534697592a15328d6aaaed2f314fef61fa0b4/src/Position.js#L63) you can see that it passes every prop to the child component.

**Comment by jquense** [comment] 2016-07-29 16:09
@lo1tuma that's intentional, and the only way for the Position component to work. I meantion custom overlay's because it is the responsibility of the component _being_ positioned to not pass through the injects props from Position

For instance this no longer is valid if you don't want the warning:

```
<Overlay>
  <div>fooo</div>
</Overlay>
```

you need to wrap the div in a custom component that swallows the non-dom props.

**Comment by rstudner** [comment] 2016-08-01 20:55
Not to add noise, but doing <Col xs={2} type stuff is even showing me:

Unknown prop `xs` on <div>

(but reading above I got the sense I shouldn't be seeing this)

**Comment by gary-menzel** [comment] 2016-08-02 03:26
@kimmajor I had this problem and it was due to thinking that NavItem and MenuItem could be used interchangeably.  This is not the case.  MenuItem belongs under the drop-down menu.  NavItem must be used under Nav (NavItem removes the passed down properties from Nav - MenuItem is not aware of these, so they filter through).

@rstudner Since resolving my earlier problems referred to just above with MenuItem/NavItem nesting constraints, I am now "warning free" and am using <Col xs={} sm={} md={} etc.> all over the place without any issues.  As with my issue, reading back through the stack list in the warning can help you dig into the code to ensure you are nesting compatible components but you also need to make sure it is not something you are adding.  Having said that, I would not imagine that the xs= is being passed on to the DIV.  <Col> should be translating that to the appropriate CSS class definition (e.g. col-xs-*) as xs= has no meaning for a DIV.

**Comment by pauldotknopf** [comment] 2016-08-02 04:21
I am using ```0.30.1``` and getting some more errors.

```html
<Nav navbar pullRight>
  <LinkContainer to="/register">
    <NavItem>Register</NavItem>
  </LinkContainer>
  <LinkContainer to="/login">
    <NavItem>Login</NavItem>
  </LinkContainer>
</Nav>
```

```
warning.js:44Warning: Unknown props `active`, `activeKey`, `activeHref` on <li> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in li (created by App)
    in ul (created by Nav)
    in Nav (created by App)
    in div (created by NavbarCollapse)
    in Transition (created by Collapse)
    in Collapse (created by NavbarCollapse)
    in NavbarCollapse (created by App)
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
```

**Comment by pauldotknopf** [comment] 2016-08-02 04:23
I am using ```0.30.1``` and getting some more errors.

```html
<Nav navbar pullRight>
  <LinkContainer to="/register">
    <NavItem>Register</NavItem>
  </LinkContainer>
  <LinkContainer to="/login">
    <NavItem>Login</NavItem>
  </LinkContainer>
</Nav>
```

```
warning.js:44Warning: Unknown props `active`, `activeKey`, `activeHref` on <li> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in li (created by App)
    in ul (created by Nav)
    in Nav (created by App)
    in div (created by NavbarCollapse)
    in Transition (created by Collapse)
    in Collapse (created by NavbarCollapse)
    in NavbarCollapse (created by App)
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
```

**Comment by jonasostrom** [comment] 2016-08-03 09:07
warning.js:44 Warning: Unknown props `toastMessageFactory`, `toastType`, `preventDuplicates`, `newestOnTop` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ToastContainer)
    in ToastContainer (created by Notification)
    in Notification (created by ToolBar)
    in div (created by ToolBar)
    in ToolBar (created by BootstrapTable)
    in div (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by ListShipments)
    in div (created by ListShipments)
    in ListShipments (created by Dashboard)
    in div (created by Dashboard)
    in div (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard

**Comment by austb25** [comment] 2016-08-03 11:10
@jonasostrom ToastContainer is a react-toastr component, not react-bootstrap. You may want to ask them: https://github.com/tomchentw/react-toastr/blob/master/README.md

**Comment by townmulti** [comment] 2016-08-04 16:13
@pauldotknopf Were you able to figure out your issue with Unknown props `active`, `activeKey`, `activeHref` on <li> tag?

**Comment by pauldotknopf** [comment] 2016-08-04 16:14
@townmulti, nope.

**Comment by townmulti** [comment] 2016-08-04 16:23
I have the same issue. I was trying some edits with what gary-menzel said just before your last post here but couldn't get the warning to go away. Then I saw this gist https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b but it's more of a hack. Anyways still working on it also.

**Comment by bdwain** [comment] 2016-08-04 21:29
the componentClass attribute on Dropdown, Dropdown.menu, and Dropdown.toggle still seems to misbehave. it is being passed through to the dom, but it is necessary

**Comment by taion** [comment] 2016-08-04 21:31
What are you talking about? `<Dropdown>` does not pass down `componentClass`, and neither `Dropdown.Menu` nor `Dropdown.Toggle` even take that prop.

**Comment by bdwain** [comment] 2016-08-04 21:41
Ah sorry. You're right. I was using it incorrectly. componentClass is all good.

**Comment by bdwain** [comment] 2016-08-04 22:04
Is there a recommendation for how to use bsrole to indicate that a Dom element is a custom toggle or menu for a dropdown now? Do we just need to wrap the Dom element In a custom element so we can put bsrole on that?

**Comment by taion** [comment] 2016-08-04 22:15
Yes, that's correct. We were considering allowing `data-bs-role`, but in all cases where we allow `bsRole`, we inject extra props into those components anyway, so you'd be getting unknown prop warnings anyway.

**Comment by bdwain** [comment] 2016-08-05 02:59
that makes sense. thanks

**Comment by gary-menzel** [comment] 2016-08-05 04:22
@pauldotknopf What is LinkContainer?  That does not appear to be a react-bootstrap component.  The react-bootrap Nav component expects a NavItem so will pass down those props to children.  If you have your own component there, you need to filter these out yourself before renderding the HTML component class (e.g. the LI) - if LinkContainer is from another developer, you'd need to ask them to do the filtering or perform the update yourself and submit a pull-request for them to merge it.

You could also consider moving LinkContainer inside NavItem (which will filter out those props) - assuming you get the same behaviour (which I can imagine is just a smart wrapper around an A tag).

**Comment by dancron** [comment] 2016-08-16 21:43
@alfredoreduarte Thanks for the work-around to temporarily silence the warnings in the Chrome browser. I tweaked your suggested Regex filter a little to get it to work for me `^((?!Unknown prop)[\s\S])*$`

**Comment by MacKentoch** [comment] 2016-08-24 12:53
Apart from hiding browser warnings any fresh news about it (milestone, fix...)?

**Comment by taion** [comment] 2016-08-24 14:10
This has been fixed for a while now.

**Comment by danbovey** [comment] 2016-08-24 14:25
@taion So any `Unknown props` warning we get from now on are from our use of components using deprecated component props such as `noCaret`?? I mean if it's fixed 100% then why are props like that still being passed through?

I'm running `0.30.3`.

**Comment by taion** [comment] 2016-08-24 14:30
If _you_ pass in a prop this library doesn't recognize, then _we_ aren't going to do anything about those.

**Comment by danbovey** [comment] 2016-08-24 14:35
Is it possible the docs are out of date? https://react-bootstrap.github.io/components.html#btn-dropdowns-nocaret

**Comment by taion** [comment] 2016-08-24 14:36
They're up-to-date. You can see trivially that `<DropdownToggle>` does not pass through `noCaret`.

Again, this is an error on your end.

**Comment by taion** [comment] 2016-08-24 14:38
You can also see that our test suite fails on all warnings, and that we explicitly cover rendering a dropdown with `noCaret` set: https://github.com/react-bootstrap/react-bootstrap/blob/v0.30.3/test/index.js#L7-L23, https://github.com/react-bootstrap/react-bootstrap/blob/v0.30.3/test/DropdownSpec.js#L93-L102

**Comment by danbovey** [comment] 2016-08-24 14:43
Yep, great work with `<Dropdown.Toggle>` and `<Dropdown.Menu>`! I imagine this issue is so long because of the breaking (read: much needed) changes you're having to make :smile:

**Comment by townmulti** [comment] 2016-08-24 21:38
Maybe maybe this can be helpful to someone still having the unknown props issue. On the unknown props link from React website [](https://facebook.github.io/react/warnings/unknown-prop.html), you can pass your component though a function or another component and pull off the warned props and let the rest pass through.

This function is from that link:
```
function MyDiv(props) {
  const { layout, ...rest } = props
  if (layout === 'horizontal') {
    return <div {...rest} style={getHorizontalStyle()} />
  } else {
    return <div {...rest} style={getVerticalStyle()} />
  }
}
```
or use a component

```
const RowPass = (props) => {
  const { active, activeKey, activeHref, ...rest } = props;
  return <Row {...rest} />;
};
```
and use

 ` <RowPass></RowPass>` in place of `<Row></Row>`

**Comment by erlgry** [comment] 2016-08-26 13:50
After trying the suggestion at the https://facebook.github.io/react/warnings/unknown-prop.html, I am still running into the warning: 

`warning.js:44 Warning: Unknown prop `active` on <a> tag. Remove this prop from the element.`

Here is how my component is structured:

`
import React from 'react';
import Nav from 'react-bootstrap/lib/Nav';
import Navbar from 'react-bootstrap/lib/Navbar';
import NavItem from 'react-bootstrap/lib/NavItem';
import UserNav from './UserNav';
import {LinkContainer, IndexLinkContainer} from 'react-router-bootstrap';

function myBrandLink(props) {
  const linkProps = Object.assign({}, props);
  delete linkProps.active;
  delete linkProps.signedIn;
  delete linkProps.username;
  delete linkProps.handleLogout;
  return <a {...linkProps}>Home</a>
}

const TopNav = (props) => (
  <Navbar fixedTop inverse>
    <Navbar.Header>
        <Navbar.Brand>
          <IndexLinkContainer to="/">
            {myBrandLink(props)}
          </IndexLinkContainer>
        </Navbar.Brand>
      <Navbar.Toggle />
    </Navbar.Header>
    <Navbar.Collapse>
      <Nav>
        <LinkContainer to="/content">
          <NavItem eventKey={1}>Content 1</NavItem>
        </LinkContainer>
      </Nav>
      <UserNav {...props} />
    </Navbar.Collapse>
  </Navbar>
);

export default TopNav;
`
Any pointers would be greatly useful

**Comment by townmulti** [comment] 2016-08-26 14:25
@erlgry Maybe the warning is coming from a different <a> tag than the one you have edited.

**Comment by taion** [comment] 2016-08-26 14:28
I'm locking this issue because it's no longer productive. We've fixed all the prop passthrough issues in React-Bootstrap. Any issues you're still seeing are due to either an outdated version of React-Bootstrap, an error in your own code, or a different library.
