### ISSUE TITLE
Navbar doesn't collapse with transition in iOS

### ISSUE THREAD

**Issue by hershmire** [react-bootstrap/react-bootstrap#1407] opened 2015-10-15 15:46 UTC
I've noticed that the navbar component does not collapse with the expected smooth closing transition on iOS devices. It works fine on any desktop browser but when used on an iOS device, it will only open with the collapsible transition. You can see this bug in action by navigating to the navbar example section in the [docs site](https://react-bootstrap.github.io/components.html#navbars). The main nav on the docs site also demos this bug.

![screen shot 2015-10-15 at 8 36 10 am](https://cloud.githubusercontent.com/assets/757524/10518984/94080974-7318-11e5-948e-899ba18c5889.png)

**Comment by taion** [comment] 2015-10-15 16:06
Dupe of #1301

**Comment by hershmire** [comment] 2015-10-15 16:54
Apologies, this didn't seem like a duplication to #1301. That bug sounded like it wouldn't actually collapse based on clicking nav items.

> Clicking on any of those NavItems does not collapse the Nav.

I never got the sense that it was referring to the transitioning effect of the closing Collapse component.

**Comment by Sinistralis** [comment] 2016-01-31 03:05
This also occurs with Desktop Safari

**Comment by taion** [comment] 2016-02-01 13:40
https://github.com/react-bootstrap/react-bootstrap/issues/1638#issuecomment-177581104

**Closed by taion** 2016-02-01 13:40 UTC
