### ISSUE TITLE
input onClick doesn't work when input is inside DropdownButton or ButtonToolbar

### ISSUE THREAD

**Issue by andjarnic** [react-bootstrap/react-bootstrap#62] opened 2014-04-08 05:38 UTC
I am showing a login form with username and password input boxes when a user clicks on a Login button in a DropdownButton which is in a ButtonToolbar. I added onClick to put in a handler to prevent default and stop propagation because currently clicking on the input box causes the menu to close, so I can't type into user input boxes.

 <nav className="navbar navbar-default navbar-fixed-top" role="navigation">
    	        <div className="container-fluid">
    		      <div className="navbar-header">
    			    <a className="navbar-brand navbar-left" href="#">Company</a>
    		      </div>

                  <ul className="nav navbar-nav">
                	<li><Link href='/'>Home</Link></li>
                  	<li><Link href='/register'>Register</Link></li>
                  </ul>

                  <ul className="nav navbar-nav navbar-right">
	                <li>
	                	<ButtonToolbar>
	                		<DropdownButton bsStyle='default' bsSize='large' title='Login'>
	                			<form id="loginForm" accept-charset="UTF-8">
									<input id="login_username" style={inputStyle} onClick={this.inputClick} type="text" name="username" placeholder="Username" size="30" />
									<input id="login_password" style={inputStyle} onClick={this.inputClick} type="password" name="password" placeholder="Password" size="30" />
									<button type="button" className="btn btn-primary" onClick={this.login} style={inputStyle}>Login</button>
								</form>
							</DropdownButton>
						</ButtonToolbar>
	                </li>
                  </ul>
                </div>
              </nav>

**Comment by hedgerh** [comment] 2015-08-08 12:32
I looked into this issue, and was unable to reproduce.  It appears that the click behavior of the DropdownButton component was addressed in https://github.com/react-bootstrap/react-bootstrap/pull/86.

```
            <ul className="nav navbar-nav navbar-right">
              <li>
                <ButtonToolbar>
                    <DropdownButton bsStyle='default' bsSize='large' title='Login' onClick={ this.handleClick }>
                        <form id="loginForm" accept-charset="UTF-8">
                            <input id="login_username" style={inputStyle} onClick={this.inputClick} type="text" name="username" placeholder="Username" size="30" />
                            <input id="login_password" style={inputStyle} onClick={this.inputClick} type="password" name="password" placeholder="Password" size="30" />
                            <button type="button" className="btn btn-primary" onClick={this.login} style={inputStyle}>Login</button>
                        </form>
                    </DropdownButton>
                </ButtonToolbar>
              </li>
            </ul>
```

with click handlers:

```
  handleClick(e) {
    console.log('handleClick');
  };

  inputClick(e) {
    e.stopPropagation();
  };
```  

The input click handler was triggered, and the event did not propagate up to the DropdownButton.

**Comment by taion** [comment] 2015-08-10 14:29
@hedgerh Thank you! Closing this issue for now, then, especially with the dropdown rework.

**Closed by taion** 2015-08-10 14:29 UTC
Labels: 2 - Prioritized Backlog, bug, help wanted

**Comment by rulyotano** [comment] 2016-01-26 00:39
Why this is closed?? I still getting the same issue/error!

**Comment by jquense** [comment] 2016-01-26 00:44
@rulyotano because inputs aren't supported in dropdown menus. The current API though does allow you make a custom menu that does support it

**Comment by rulyotano** [comment] 2016-01-26 00:49
Ok, so the solution is creating your own drop down, and handle a lot of things that custom drop down doesn't, like closing on click out. What is the reason why inputs are not supported! Thanks for answering.
