### ISSUE TITLE
Links in NavItems don't navigate to href url

### ISSUE THREAD

**Issue by elliotec** [react-bootstrap/react-bootstrap#2559] opened 2017-04-12 00:56 UTC
`<NavItem className="nav-link" href="/about">About</NavItem>`
or
`<NavItem className="nav-link" href="https://google.com">Google</NavItem>`

Doesn't matter if internal or external, the links never work no matter what. Tried with and without react-router. 

Also tried editing the href in browser dev tools on the demo site, and it wont even work in the docs/demo. 

Latest version of Bootstrap, react-bootstrap, and React.

**Comment by jquense** [comment] 2017-04-12 00:58
sorry not sure what you mean by not working. our docs use NavItems and they work fine. you might have something else that's breaking navigation like an extension or code

**Comment by elliotec** [comment] 2017-04-12 01:07
Thanks for the quick response. By not working I mean they don't navigate anywhere. I've tried on incognito in Chrome as well as Firefox, on 3 computers. No extensions. We are using the Nav exactly like here: https://react-bootstrap.github.io/components.html#navbars-basic. Even editing that example in dev tools doesn't navigate.

**Comment by taion** [comment] 2017-04-12 01:19
Are you using `toggleOnSelect`?

**Comment by elliotec** [comment] 2017-04-12 01:25
@taion No, here is my whole (edited) Navbar, with my own solution that got it working: 

```
  <Navbar className="header-menu" collapseOnSelect>
     <Navbar.Header>
       <Navbar.Brand>
         <a className="logo" href="#">
           Brand
         </a>
       </Navbar.Brand>
       <Navbar.Toggle />
     </Navbar.Header>
     <Navbar.Collapse>
       <Nav>
         <LinkContainer to='/products/'>
           <NavItem className="nav-link">Products</NavItem>
         </LinkContainer>
         <LinkContainer to='/about/'>
           <NavItem className="nav-link">About</NavItem>
         </LinkContainer>
         <LinkContainer to='/how-to-use/'>
           <NavItem className="nav-link">How to Use</NavItem>
         </LinkContainer>
       </Nav>
       <Nav pullRight>
         <NavItem>
           <FaShoppingCart className='cart-button' />
         </NavItem>
       </Nav>
       <a className="custom-style" href="https://www.facebook.com">
          <FaFacebookSquare className='fb-button' />
       </a>
     </Navbar.Collapse>
  </Navbar>
```

That uses react-router which is the only way I could get internal links working, and regular `<a>` tags to get the external link to navigate. Adding any `href`s to the `NavItem`s break this.

**Comment by taion** [comment] 2017-04-12 01:42
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/2365

**Closed by taion** 2017-04-12 01:42 UTC

**Comment by elliotec** [comment] 2017-04-12 02:30
@taion Ah yes, you're correct, it is a duplicate of that issue. Thanks for pointing me to it. One thing to be clear though, that issue mentions only external links, I've had the problem with any link at all, even stubs. Thanks again.

**Comment by chongdog83** [comment] 2017-09-28 04:45
I had this problem and when I looked at the documentation, there is something that is a little counterintuitive.

This works:
            <Nav pullRight>
              <NavDropdown title={this._renderCompanyName()} id="UserDropdown">
                <MenuItem href="#">Edit Profile</MenuItem>
                <MenuItem href="#">Manage Company</MenuItem>
                <MenuItem href="/listcompanies">Link Goes Here</MenuItem>
                <MenuItem divider />
                <MenuItem href="/logout">Log Out</MenuItem>
              </NavDropdown>
            </Nav>

Notice that its <MenuItem> not <NavItem>.  This seems wrong, but it does work and is how it shows on the demo page.

**Comment by rimatla** [comment] 2018-02-01 21:49
Thank you @chongdog83

**Comment by toonikolai** [comment] 2018-02-07 18:31
@chongdog83 what a catch thanks
