### ISSUE TITLE
Modal Null Exception when react-bootstrap is loaded before the Body tag

### ISSUE THREAD

**Issue by volkanunsal** [react-bootstrap/react-bootstrap#3645] opened 2019-04-14 15:27 UTC
I'm experiencing this issue from the modal component. Here is a screenshot of the error trace.

![Screen Shot 2019-04-14 at 11 08 22 AM](https://user-images.githubusercontent.com/151600/56095199-4fed9e00-5ea8-11e9-8dfb-46d9368a5ed6.png)

**Comment by taion** [comment] 2019-04-15 14:38
Do you have a stack trace here? I don't think we calculate these values until the component mounts.

**Comment by volkanunsal** [comment] 2019-04-15 15:02
Is this helpful?

![Screen Shot 2019-04-15 at 11 01 37 AM](https://user-images.githubusercontent.com/151600/56143082-e20baa00-5f6d-11e9-944b-68228f24582c.png)

**Comment by marc0n3** [comment] 2019-05-14 08:39
I can reproduce the issue by loading the javascript in the head tag.

The function is called before the DOM is ready.
Is it related to the old #849?

**Comment by clmz** [comment] 2019-05-17 09:22
@marc0n3 
where/how can I manipulate the location of scripts in a react project? I mean, afaik webpack build the html file, so how can I change the location of the JS and which JS file do you mean exactly? (I'm pretty new to react and getting the same error (as above) while migrating to latest react-bootstrap verion from 0.32...)
Thanks!

**Comment by marc0n3** [comment] 2019-05-17 09:33
@clmz In my project, I can move the inclusion of generated files in the head or in the body, but I've a custom project creation script so I think it depends on how your webpack is configured.
Maybe there is a template somewhere from which HTML is generated, my suggestion is to search for it.

**Comment by billychan** [comment] 2019-06-12 12:31
I can reproduce this too. 

Just:
1. Put script on head
2. Simply write an import statement aka `import Modal from 'react-boostrap/Modal'; 

Error will show.

I won't say putting script tag in head or body is better, but either way has people using that and the component should not require such hidden dependency.

The problem as I feel, is dom computation should not happen on module import time by any means.

**Comment by billychan** [comment] 2019-06-12 12:50
It looks like problem happens in such order:

1. https://github.com/react-bootstrap/react-overlays/blob/master/src/ModalManager.js#L67 a new instance of BoostrapeModalManager created at requiring time.
2. DOM query happened instantly on manager initialization when there is nothing in DOM yet https://github.com/react-bootstrap/react-overlays/blob/master/src/ModalManager.js#L39

I feel the fix might be removing that `this.scrollbarSize` on initialization and call `getScrollbarSize` directly here https://github.com/react-bootstrap/react-overlays/blob/master/src/ModalManager.js#L67 which looks the only usage.

I'm not familiar the code base, checking. If you maintainers have quick insights that would be great, thanks!

**Comment by billychan** [comment] 2019-06-12 12:52
Same issue reported on https://github.com/react-bootstrap/react-overlays/issues/283

**Comment by nitzien** [comment] 2019-08-13 09:04
Do we know when fix for this will be available? It may not be always possible to load bootstrap script from body.

**Comment by texonidas** [comment] 2019-12-18 04:21
Any word on when this is going to be merged into latest? This is a pretty major issue given it completely breaks any project without any indication of why it is breaking.

**Comment by jotacervan** [comment] 2020-02-03 02:18
Any updates about this issue guys? I agree with @texonidas. This is a pretty major issue.

**Comment by eweitz** [comment] 2020-02-03 21:24
Hi @taion, thanks for developing this fantastic library.

It seems @billychan fixed this issue in react-bootstrap/react-overlays#297, which you [merged](https://github.com/react-bootstrap/react-overlays/commit/e022e9c2b66fb7a0f8ef0c172a1b12c986dbcc75) into `react-bootstrap/react-overlays:master` on 2019-10-19.

However, I just encountered this bug in [react-bootstrap v1.0.0-beta.16](https://github.com/react-bootstrap/react-bootstrap/releases/tag/v1.0.0-beta.16).  I see `package.json` [specifies](https://github.com/react-bootstrap/react-bootstrap/blob/4820bcd98431e5ff2393f741032c4b781eefdedc/package.json#L76) `"react-overlays": "^2.1.0"`, which was [released](https://github.com/react-bootstrap/react-overlays/releases) on 2019-10-11, about a week before you merged Billy's fix.

When is the next 2.x release of `react-overlays`?  That should fix this in `react-bootstrap`.

**Comment by taion** [comment] 2020-02-03 22:54
@eweitz @billychan oh, my bad. i just released 2.1.1 of react-overlays.

i think i lazied out on releasing that earlier because we hadn't upgraded R-B to use R-O v2 yet

**Comment by kosmiq** [comment] 2020-03-11 11:01
@taion can we close this since a fix has been committed in react-overlays?

**Comment by taion** [comment] 2020-03-11 13:48
yup, thanks!

**Closed by taion** 2020-03-11 13:48 UTC
Labels: needs more info
