### ISSUE TITLE
Can't run npm run build with react bootstrap + ts + sass

### ISSUE THREAD

**Issue by ikkerens** [react-bootstrap/react-bootstrap#6039] opened 2021-09-16 15:39 UTC
## Describe the bug

With the latest version, it is not possible to run the build script. It gives a syntax error (see screenshots). The mentioned line and column in the error is consistent irregardless of where the bootstrap import line is.

## To Reproduce

```sh
# 1. Create a basic react typescript template
npx create-react-app my-app --template typescript
# 2. Install react-bootstrap, bootstrap and sass
npm install react-bootstrap@next bootstrap@5.1.0 sass
# 3. Change the template css to scss
mv src/App.css src/App.scss
# 4. Add @import "~bootstrap/scss/bootstrap"; to the top of App.scss
# 5. Change the import from css to scss in App.tsx
```

## Reproducible Example

Cannot reproduce on CodeSandbox, since you can't run builds there (or I'm blind)

## Expected behavior

The build script to complete successfully and filling the build folder.

## Screenshots

![image](https://user-images.githubusercontent.com/1952177/133642315-a864ac34-c4ad-49dc-a635-0b4deb0b1075.png)

## Environment (please complete the following information)

- Operating System: Windows, also tested on Debian Linux
- Browser: Irrelevant
- React-Bootstrap Version: 2.0.0-beta.6

## Additional context

Tried talking about this in the Discord channel, at least one other user has the same issue.

**Comment by obrunopolo** [comment] 2021-09-17 18:19
I am actually using this setup and it works fine, using webpack to build. Of course, some configuration might be needed.

**Comment by kyletsang** [comment] 2021-09-18 19:59
Seems like it's caused by the margin values inside `make-row` in `mixins/_grid.scss`.  

It'll compile if I change this:

```
margin-top: calc(var(--#{$variable-prefix}gutter-y) * -1); // stylelint-disable-line function-disallowed-list
margin-right: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
margin-left: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
```

to this:

```
margin-top: calc(-1 * var(--#{$variable-prefix}gutter-y)); // stylelint-disable-line function-disallowed-list
margin-right: calc(-.5 * var(--#{$variable-prefix}gutter-x)); // stylelint-disable-line function-disallowed-list
margin-left: calc(-.5 * var(--#{$variable-prefix}gutter-x)); // stylelint-disable-line function-disallowed-list
```

**Comment by frankverhorst** [comment] 2021-09-20 21:37
Most likely an issue with `sass` as it does work with `node-sass` (which is discontinued unfortunately).

**Comment by djcolon** [comment] 2021-09-21 09:50
I've been battling this same issue and can confirm that kyletsang's change fixed it for me.
I'll have to write a custom bootstrap import scss for now as a work-around.
The error message (adding as text to be searchable)
```
./src/App.scss
ParserError: Syntax Error at line: 1, column 25
```
Was particularly unhelpful.
For reference, I'm on:
* sass@1.42.0
* react-scripts@4.0.3
* bootstrap@5.1.1
* react-bootstrap@2.0.0-beta.6

**Comment by axelra82** [comment] 2021-09-24 21:41
Can confirm the same issue. Also double checked with steps to reproduce, same problem.

Solution from @kyletsang  solves the issue for me as well. We be great if we could get a PR up for this. Seems like a major issue (not being able to build) with a minor change 😃 

I'm on the same versions as @djcolon **with the exception of react-bootstrap** which is on **2.0.0-rc.0**

**Comment by ikkerens** [comment] 2021-09-24 22:07
Seems like @kyletsang already set up a PR here: https://github.com/twbs/bootstrap/pull/35033
Chances are that when this PR gets merged the fix in this lib is as simple as changing the bootstrap version in your own project.

**Comment by kyletsang** [comment] 2021-10-05 16:34
Bootstrap 5.1.2 has been released with the workaround

**Closed by kyletsang** 2021-10-05 16:34 UTC
Labels: bug, upstream
